// Code generated by the LoginRadius SDK generator; DO NOT EDIT.
//
// Behaviour is declared in the shared SDK manifest and rendered through
// the SDK generator templates Edit those and regenerate —
// changes made here are lost on the next run and never reach the other SDKs.

package loginradius

// Version is the semver of the v12 SDK release. Stamped into the User-Agent
// header on every outgoing request. Set from the shared SDK manifest `sdkVersion`,
// so every LoginRadius SDK reports the same number.
const Version = "12.0.0-rc.1"
