/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

type DomainAccessRestrictionsAPI interface {

	/*
		GetDomainAccessRestrictionsByAppID Retrieve Domain Access Restrictions

		Retrieves the domain access restrictions configured for the Tenant.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiGetDomainAccessRestrictionsByAppIDRequest
	*/
	GetDomainAccessRestrictionsByAppID(ctx context.Context) ApiGetDomainAccessRestrictionsByAppIDRequest

	// GetDomainAccessRestrictionsByAppIDExecute executes the request
	//  @return DomainAccessRestrictions
	GetDomainAccessRestrictionsByAppIDExecute(r ApiGetDomainAccessRestrictionsByAppIDRequest) (*DomainAccessRestrictions, *http.Response, error)

	/*
		UpdateDomainAccessRestrictionsByAppID Update Domain Access Restrictions

		Updates the domain access restrictions for the Tenant.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiUpdateDomainAccessRestrictionsByAppIDRequest
	*/
	UpdateDomainAccessRestrictionsByAppID(ctx context.Context) ApiUpdateDomainAccessRestrictionsByAppIDRequest

	// UpdateDomainAccessRestrictionsByAppIDExecute executes the request
	//  @return DomainAccessRestrictions
	UpdateDomainAccessRestrictionsByAppIDExecute(r ApiUpdateDomainAccessRestrictionsByAppIDRequest) (*DomainAccessRestrictions, *http.Response, error)
}

// DomainAccessRestrictionsAPIService DomainAccessRestrictionsAPI service
type DomainAccessRestrictionsAPIService service

type ApiGetDomainAccessRestrictionsByAppIDRequest struct {
	ctx        context.Context
	ApiService DomainAccessRestrictionsAPI
}

func (r ApiGetDomainAccessRestrictionsByAppIDRequest) Execute() (*DomainAccessRestrictions, *http.Response, error) {
	return r.ApiService.GetDomainAccessRestrictionsByAppIDExecute(r)
}

/*
GetDomainAccessRestrictionsByAppID Retrieve Domain Access Restrictions

Retrieves the domain access restrictions configured for the Tenant.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetDomainAccessRestrictionsByAppIDRequest
*/
func (a *DomainAccessRestrictionsAPIService) GetDomainAccessRestrictionsByAppID(ctx context.Context) ApiGetDomainAccessRestrictionsByAppIDRequest {
	return ApiGetDomainAccessRestrictionsByAppIDRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return DomainAccessRestrictions
func (a *DomainAccessRestrictionsAPIService) GetDomainAccessRestrictionsByAppIDExecute(r ApiGetDomainAccessRestrictionsByAppIDRequest) (*DomainAccessRestrictions, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *DomainAccessRestrictions
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DomainAccessRestrictionsAPIService.GetDomainAccessRestrictionsByAppID")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v2/manage/restrictions/domain-access"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateDomainAccessRestrictionsByAppIDRequest struct {
	ctx                      context.Context
	ApiService               DomainAccessRestrictionsAPI
	domainAccessRestrictions *DomainAccessRestrictions
}

func (r ApiUpdateDomainAccessRestrictionsByAppIDRequest) DomainAccessRestrictions(domainAccessRestrictions DomainAccessRestrictions) ApiUpdateDomainAccessRestrictionsByAppIDRequest {
	r.domainAccessRestrictions = &domainAccessRestrictions
	return r
}

func (r ApiUpdateDomainAccessRestrictionsByAppIDRequest) Execute() (*DomainAccessRestrictions, *http.Response, error) {
	return r.ApiService.UpdateDomainAccessRestrictionsByAppIDExecute(r)
}

/*
UpdateDomainAccessRestrictionsByAppID Update Domain Access Restrictions

Updates the domain access restrictions for the Tenant.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiUpdateDomainAccessRestrictionsByAppIDRequest
*/
func (a *DomainAccessRestrictionsAPIService) UpdateDomainAccessRestrictionsByAppID(ctx context.Context) ApiUpdateDomainAccessRestrictionsByAppIDRequest {
	return ApiUpdateDomainAccessRestrictionsByAppIDRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return DomainAccessRestrictions
func (a *DomainAccessRestrictionsAPIService) UpdateDomainAccessRestrictionsByAppIDExecute(r ApiUpdateDomainAccessRestrictionsByAppIDRequest) (*DomainAccessRestrictions, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *DomainAccessRestrictions
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DomainAccessRestrictionsAPIService.UpdateDomainAccessRestrictionsByAppID")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v2/manage/restrictions/domain-access"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.domainAccessRestrictions
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
