/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DomainAccessRestrictions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainAccessRestrictions{}

// DomainAccessRestrictions struct for DomainAccessRestrictions
type DomainAccessRestrictions struct {
	// List of allowed domains/emails
	Allowlist []string `json:"Allowlist,omitempty"`
	// List of blocked domains/emails
	Blocklist []string `json:"Blocklist,omitempty"`
}

// NewDomainAccessRestrictions instantiates a new DomainAccessRestrictions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainAccessRestrictions() *DomainAccessRestrictions {
	this := DomainAccessRestrictions{}
	return &this
}

// NewDomainAccessRestrictionsWithDefaults instantiates a new DomainAccessRestrictions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainAccessRestrictionsWithDefaults() *DomainAccessRestrictions {
	this := DomainAccessRestrictions{}
	return &this
}

// GetAllowlist returns the Allowlist field value if set, zero value otherwise.
func (o *DomainAccessRestrictions) GetAllowlist() []string {
	if o == nil || IsNil(o.Allowlist) {
		var ret []string
		return ret
	}
	return o.Allowlist
}

// GetAllowlistOk returns a tuple with the Allowlist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainAccessRestrictions) GetAllowlistOk() ([]string, bool) {
	if o == nil || IsNil(o.Allowlist) {
		return nil, false
	}
	return o.Allowlist, true
}

// HasAllowlist returns a boolean if a field has been set.
func (o *DomainAccessRestrictions) HasAllowlist() bool {
	if o != nil && !IsNil(o.Allowlist) {
		return true
	}

	return false
}

// SetAllowlist gets a reference to the given []string and assigns it to the Allowlist field.
func (o *DomainAccessRestrictions) SetAllowlist(v []string) {
	o.Allowlist = v
}

// GetBlocklist returns the Blocklist field value if set, zero value otherwise.
func (o *DomainAccessRestrictions) GetBlocklist() []string {
	if o == nil || IsNil(o.Blocklist) {
		var ret []string
		return ret
	}
	return o.Blocklist
}

// GetBlocklistOk returns a tuple with the Blocklist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainAccessRestrictions) GetBlocklistOk() ([]string, bool) {
	if o == nil || IsNil(o.Blocklist) {
		return nil, false
	}
	return o.Blocklist, true
}

// HasBlocklist returns a boolean if a field has been set.
func (o *DomainAccessRestrictions) HasBlocklist() bool {
	if o != nil && !IsNil(o.Blocklist) {
		return true
	}

	return false
}

// SetBlocklist gets a reference to the given []string and assigns it to the Blocklist field.
func (o *DomainAccessRestrictions) SetBlocklist(v []string) {
	o.Blocklist = v
}

func (o DomainAccessRestrictions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainAccessRestrictions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Allowlist) {
		toSerialize["Allowlist"] = o.Allowlist
	}
	if !IsNil(o.Blocklist) {
		toSerialize["Blocklist"] = o.Blocklist
	}
	return toSerialize, nil
}

type NullableDomainAccessRestrictions struct {
	value *DomainAccessRestrictions
	isSet bool
}

func (v NullableDomainAccessRestrictions) Get() *DomainAccessRestrictions {
	return v.value
}

func (v *NullableDomainAccessRestrictions) Set(val *DomainAccessRestrictions) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainAccessRestrictions) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainAccessRestrictions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainAccessRestrictions(val *DomainAccessRestrictions) *NullableDomainAccessRestrictions {
	return &NullableDomainAccessRestrictions{value: val, isSet: true}
}

func (v NullableDomainAccessRestrictions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainAccessRestrictions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
