/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OAuthM2MIntrospectResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuthM2MIntrospectResponse{}

// OAuthM2MIntrospectResponse M2M Token Introspect Response
type OAuthM2MIntrospectResponse struct {
	Active *bool    `json:"active,omitempty"`
	Aud    []string `json:"aud,omitempty"`
	Cid    *string  `json:"cid,omitempty"`
	Exp    *int32   `json:"exp,omitempty"`
	Gty    *string  `json:"gty,omitempty"`
	Iat    *int32   `json:"iat,omitempty"`
	Iss    *string  `json:"iss,omitempty"`
	Jti    *string  `json:"jti,omitempty"`
	Nbf    *int32   `json:"nbf,omitempty"`
	Scp    []string `json:"scp,omitempty"`
	Sub    *string  `json:"sub,omitempty"`
}

// NewOAuthM2MIntrospectResponse instantiates a new OAuthM2MIntrospectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuthM2MIntrospectResponse() *OAuthM2MIntrospectResponse {
	this := OAuthM2MIntrospectResponse{}
	return &this
}

// NewOAuthM2MIntrospectResponseWithDefaults instantiates a new OAuthM2MIntrospectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuthM2MIntrospectResponseWithDefaults() *OAuthM2MIntrospectResponse {
	this := OAuthM2MIntrospectResponse{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *OAuthM2MIntrospectResponse) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthM2MIntrospectResponse) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *OAuthM2MIntrospectResponse) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *OAuthM2MIntrospectResponse) SetActive(v bool) {
	o.Active = &v
}

// GetAud returns the Aud field value if set, zero value otherwise.
func (o *OAuthM2MIntrospectResponse) GetAud() []string {
	if o == nil || IsNil(o.Aud) {
		var ret []string
		return ret
	}
	return o.Aud
}

// GetAudOk returns a tuple with the Aud field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthM2MIntrospectResponse) GetAudOk() ([]string, bool) {
	if o == nil || IsNil(o.Aud) {
		return nil, false
	}
	return o.Aud, true
}

// HasAud returns a boolean if a field has been set.
func (o *OAuthM2MIntrospectResponse) HasAud() bool {
	if o != nil && !IsNil(o.Aud) {
		return true
	}

	return false
}

// SetAud gets a reference to the given []string and assigns it to the Aud field.
func (o *OAuthM2MIntrospectResponse) SetAud(v []string) {
	o.Aud = v
}

// GetCid returns the Cid field value if set, zero value otherwise.
func (o *OAuthM2MIntrospectResponse) GetCid() string {
	if o == nil || IsNil(o.Cid) {
		var ret string
		return ret
	}
	return *o.Cid
}

// GetCidOk returns a tuple with the Cid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthM2MIntrospectResponse) GetCidOk() (*string, bool) {
	if o == nil || IsNil(o.Cid) {
		return nil, false
	}
	return o.Cid, true
}

// HasCid returns a boolean if a field has been set.
func (o *OAuthM2MIntrospectResponse) HasCid() bool {
	if o != nil && !IsNil(o.Cid) {
		return true
	}

	return false
}

// SetCid gets a reference to the given string and assigns it to the Cid field.
func (o *OAuthM2MIntrospectResponse) SetCid(v string) {
	o.Cid = &v
}

// GetExp returns the Exp field value if set, zero value otherwise.
func (o *OAuthM2MIntrospectResponse) GetExp() int32 {
	if o == nil || IsNil(o.Exp) {
		var ret int32
		return ret
	}
	return *o.Exp
}

// GetExpOk returns a tuple with the Exp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthM2MIntrospectResponse) GetExpOk() (*int32, bool) {
	if o == nil || IsNil(o.Exp) {
		return nil, false
	}
	return o.Exp, true
}

// HasExp returns a boolean if a field has been set.
func (o *OAuthM2MIntrospectResponse) HasExp() bool {
	if o != nil && !IsNil(o.Exp) {
		return true
	}

	return false
}

// SetExp gets a reference to the given int32 and assigns it to the Exp field.
func (o *OAuthM2MIntrospectResponse) SetExp(v int32) {
	o.Exp = &v
}

// GetGty returns the Gty field value if set, zero value otherwise.
func (o *OAuthM2MIntrospectResponse) GetGty() string {
	if o == nil || IsNil(o.Gty) {
		var ret string
		return ret
	}
	return *o.Gty
}

// GetGtyOk returns a tuple with the Gty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthM2MIntrospectResponse) GetGtyOk() (*string, bool) {
	if o == nil || IsNil(o.Gty) {
		return nil, false
	}
	return o.Gty, true
}

// HasGty returns a boolean if a field has been set.
func (o *OAuthM2MIntrospectResponse) HasGty() bool {
	if o != nil && !IsNil(o.Gty) {
		return true
	}

	return false
}

// SetGty gets a reference to the given string and assigns it to the Gty field.
func (o *OAuthM2MIntrospectResponse) SetGty(v string) {
	o.Gty = &v
}

// GetIat returns the Iat field value if set, zero value otherwise.
func (o *OAuthM2MIntrospectResponse) GetIat() int32 {
	if o == nil || IsNil(o.Iat) {
		var ret int32
		return ret
	}
	return *o.Iat
}

// GetIatOk returns a tuple with the Iat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthM2MIntrospectResponse) GetIatOk() (*int32, bool) {
	if o == nil || IsNil(o.Iat) {
		return nil, false
	}
	return o.Iat, true
}

// HasIat returns a boolean if a field has been set.
func (o *OAuthM2MIntrospectResponse) HasIat() bool {
	if o != nil && !IsNil(o.Iat) {
		return true
	}

	return false
}

// SetIat gets a reference to the given int32 and assigns it to the Iat field.
func (o *OAuthM2MIntrospectResponse) SetIat(v int32) {
	o.Iat = &v
}

// GetIss returns the Iss field value if set, zero value otherwise.
func (o *OAuthM2MIntrospectResponse) GetIss() string {
	if o == nil || IsNil(o.Iss) {
		var ret string
		return ret
	}
	return *o.Iss
}

// GetIssOk returns a tuple with the Iss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthM2MIntrospectResponse) GetIssOk() (*string, bool) {
	if o == nil || IsNil(o.Iss) {
		return nil, false
	}
	return o.Iss, true
}

// HasIss returns a boolean if a field has been set.
func (o *OAuthM2MIntrospectResponse) HasIss() bool {
	if o != nil && !IsNil(o.Iss) {
		return true
	}

	return false
}

// SetIss gets a reference to the given string and assigns it to the Iss field.
func (o *OAuthM2MIntrospectResponse) SetIss(v string) {
	o.Iss = &v
}

// GetJti returns the Jti field value if set, zero value otherwise.
func (o *OAuthM2MIntrospectResponse) GetJti() string {
	if o == nil || IsNil(o.Jti) {
		var ret string
		return ret
	}
	return *o.Jti
}

// GetJtiOk returns a tuple with the Jti field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthM2MIntrospectResponse) GetJtiOk() (*string, bool) {
	if o == nil || IsNil(o.Jti) {
		return nil, false
	}
	return o.Jti, true
}

// HasJti returns a boolean if a field has been set.
func (o *OAuthM2MIntrospectResponse) HasJti() bool {
	if o != nil && !IsNil(o.Jti) {
		return true
	}

	return false
}

// SetJti gets a reference to the given string and assigns it to the Jti field.
func (o *OAuthM2MIntrospectResponse) SetJti(v string) {
	o.Jti = &v
}

// GetNbf returns the Nbf field value if set, zero value otherwise.
func (o *OAuthM2MIntrospectResponse) GetNbf() int32 {
	if o == nil || IsNil(o.Nbf) {
		var ret int32
		return ret
	}
	return *o.Nbf
}

// GetNbfOk returns a tuple with the Nbf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthM2MIntrospectResponse) GetNbfOk() (*int32, bool) {
	if o == nil || IsNil(o.Nbf) {
		return nil, false
	}
	return o.Nbf, true
}

// HasNbf returns a boolean if a field has been set.
func (o *OAuthM2MIntrospectResponse) HasNbf() bool {
	if o != nil && !IsNil(o.Nbf) {
		return true
	}

	return false
}

// SetNbf gets a reference to the given int32 and assigns it to the Nbf field.
func (o *OAuthM2MIntrospectResponse) SetNbf(v int32) {
	o.Nbf = &v
}

// GetScp returns the Scp field value if set, zero value otherwise.
func (o *OAuthM2MIntrospectResponse) GetScp() []string {
	if o == nil || IsNil(o.Scp) {
		var ret []string
		return ret
	}
	return o.Scp
}

// GetScpOk returns a tuple with the Scp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthM2MIntrospectResponse) GetScpOk() ([]string, bool) {
	if o == nil || IsNil(o.Scp) {
		return nil, false
	}
	return o.Scp, true
}

// HasScp returns a boolean if a field has been set.
func (o *OAuthM2MIntrospectResponse) HasScp() bool {
	if o != nil && !IsNil(o.Scp) {
		return true
	}

	return false
}

// SetScp gets a reference to the given []string and assigns it to the Scp field.
func (o *OAuthM2MIntrospectResponse) SetScp(v []string) {
	o.Scp = v
}

// GetSub returns the Sub field value if set, zero value otherwise.
func (o *OAuthM2MIntrospectResponse) GetSub() string {
	if o == nil || IsNil(o.Sub) {
		var ret string
		return ret
	}
	return *o.Sub
}

// GetSubOk returns a tuple with the Sub field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthM2MIntrospectResponse) GetSubOk() (*string, bool) {
	if o == nil || IsNil(o.Sub) {
		return nil, false
	}
	return o.Sub, true
}

// HasSub returns a boolean if a field has been set.
func (o *OAuthM2MIntrospectResponse) HasSub() bool {
	if o != nil && !IsNil(o.Sub) {
		return true
	}

	return false
}

// SetSub gets a reference to the given string and assigns it to the Sub field.
func (o *OAuthM2MIntrospectResponse) SetSub(v string) {
	o.Sub = &v
}

func (o OAuthM2MIntrospectResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuthM2MIntrospectResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Aud) {
		toSerialize["aud"] = o.Aud
	}
	if !IsNil(o.Cid) {
		toSerialize["cid"] = o.Cid
	}
	if !IsNil(o.Exp) {
		toSerialize["exp"] = o.Exp
	}
	if !IsNil(o.Gty) {
		toSerialize["gty"] = o.Gty
	}
	if !IsNil(o.Iat) {
		toSerialize["iat"] = o.Iat
	}
	if !IsNil(o.Iss) {
		toSerialize["iss"] = o.Iss
	}
	if !IsNil(o.Jti) {
		toSerialize["jti"] = o.Jti
	}
	if !IsNil(o.Nbf) {
		toSerialize["nbf"] = o.Nbf
	}
	if !IsNil(o.Scp) {
		toSerialize["scp"] = o.Scp
	}
	if !IsNil(o.Sub) {
		toSerialize["sub"] = o.Sub
	}
	return toSerialize, nil
}

type NullableOAuthM2MIntrospectResponse struct {
	value *OAuthM2MIntrospectResponse
	isSet bool
}

func (v NullableOAuthM2MIntrospectResponse) Get() *OAuthM2MIntrospectResponse {
	return v.value
}

func (v *NullableOAuthM2MIntrospectResponse) Set(val *OAuthM2MIntrospectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuthM2MIntrospectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuthM2MIntrospectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuthM2MIntrospectResponse(val *OAuthM2MIntrospectResponse) *NullableOAuthM2MIntrospectResponse {
	return &NullableOAuthM2MIntrospectResponse{value: val, isSet: true}
}

func (v NullableOAuthM2MIntrospectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuthM2MIntrospectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
