/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// UserProfileFavoriteThings - Favorite things or object.
type UserProfileFavoriteThings struct {
	ArrayOfAny        *[]interface{}
	MapmapOfStringAny *map[string]interface{}
}

// []interface{}AsUserProfileFavoriteThings is a convenience function that returns []interface{} wrapped in UserProfileFavoriteThings
func ArrayOfAnyAsUserProfileFavoriteThings(v *[]interface{}) UserProfileFavoriteThings {
	return UserProfileFavoriteThings{
		ArrayOfAny: v,
	}
}

// map[string]interface{}AsUserProfileFavoriteThings is a convenience function that returns map[string]interface{} wrapped in UserProfileFavoriteThings
func MapmapOfStringAnyAsUserProfileFavoriteThings(v *map[string]interface{}) UserProfileFavoriteThings {
	return UserProfileFavoriteThings{
		MapmapOfStringAny: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct.
//
// CUSTOMIZED for LoginRadius (codegen/templates/model_oneof.mustache):
// the upstream template requires EXACTLY ONE branch to match — if multiple
// branches decode to non-empty structs the unmarshal fails with
// "data matches more than one schema in oneOf(...)". Several LoginRadius
// response schemas declare overlapping fields across branches (e.g.
// `access_token` appears on both AuthResponseOptionalMfa AND
// AuthResponseRequiredMfa for EmailByLoginUserNamePhone200Response), so
// strict uniqueness produces false ambiguity errors on perfectly valid
// payloads. We change the semantics to FIRST NON-EMPTY MATCH WINS:
// each branch is tried in declaration order, and once any branch
// populates a non-empty struct the remaining branches are skipped.
// Branch order in the generator output therefore = priority order;
// keep the common case first when you author or edit the spec.
func (dst *UserProfileFavoriteThings) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfAny
	if match == 0 {
		err = newStrictDecoder(data).Decode(&dst.ArrayOfAny)
		if err == nil {
			jsonArrayOfAny, _ := json.Marshal(dst.ArrayOfAny)
			if string(jsonArrayOfAny) == "{}" { // empty struct
				dst.ArrayOfAny = nil
			} else {
				if err = validator.Validate(dst.ArrayOfAny); err != nil {
					dst.ArrayOfAny = nil
				} else {
					match++
				}
			}
		} else {
			dst.ArrayOfAny = nil
		}
	} else {
		dst.ArrayOfAny = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	if match == 0 {
		err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
		if err == nil {
			jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
			if string(jsonMapmapOfStringAny) == "{}" { // empty struct
				dst.MapmapOfStringAny = nil
			} else {
				if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
					dst.MapmapOfStringAny = nil
				} else {
					match++
				}
			}
		} else {
			dst.MapmapOfStringAny = nil
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	if match >= 1 {
		return nil
	}
	return fmt.Errorf("data failed to match schemas in oneOf(UserProfileFavoriteThings)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UserProfileFavoriteThings) MarshalJSON() ([]byte, error) {
	if src.ArrayOfAny != nil {
		return json.Marshal(&src.ArrayOfAny)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *UserProfileFavoriteThings) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfAny != nil {
		return obj.ArrayOfAny
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

type NullableUserProfileFavoriteThings struct {
	value *UserProfileFavoriteThings
	isSet bool
}

func (v NullableUserProfileFavoriteThings) Get() *UserProfileFavoriteThings {
	return v.value
}

func (v *NullableUserProfileFavoriteThings) Set(val *UserProfileFavoriteThings) {
	v.value = val
	v.isSet = true
}

func (v NullableUserProfileFavoriteThings) IsSet() bool {
	return v.isSet
}

func (v *NullableUserProfileFavoriteThings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserProfileFavoriteThings(val *UserProfileFavoriteThings) *NullableUserProfileFavoriteThings {
	return &NullableUserProfileFavoriteThings{value: val, isSet: true}
}

func (v NullableUserProfileFavoriteThings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserProfileFavoriteThings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
