/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAllTenantRoles200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAllTenantRoles200Response{}

// GetAllTenantRoles200Response struct for GetAllTenantRoles200Response
type GetAllTenantRoles200Response struct {
	Data []TenantRole `json:"Data,omitempty"`
}

// NewGetAllTenantRoles200Response instantiates a new GetAllTenantRoles200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllTenantRoles200Response() *GetAllTenantRoles200Response {
	this := GetAllTenantRoles200Response{}
	return &this
}

// NewGetAllTenantRoles200ResponseWithDefaults instantiates a new GetAllTenantRoles200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllTenantRoles200ResponseWithDefaults() *GetAllTenantRoles200Response {
	this := GetAllTenantRoles200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetAllTenantRoles200Response) GetData() []TenantRole {
	if o == nil || IsNil(o.Data) {
		var ret []TenantRole
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllTenantRoles200Response) GetDataOk() ([]TenantRole, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetAllTenantRoles200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []TenantRole and assigns it to the Data field.
func (o *GetAllTenantRoles200Response) SetData(v []TenantRole) {
	o.Data = v
}

func (o GetAllTenantRoles200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAllTenantRoles200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["Data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetAllTenantRoles200Response struct {
	value *GetAllTenantRoles200Response
	isSet bool
}

func (v NullableGetAllTenantRoles200Response) Get() *GetAllTenantRoles200Response {
	return v.value
}

func (v *NullableGetAllTenantRoles200Response) Set(val *GetAllTenantRoles200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllTenantRoles200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllTenantRoles200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllTenantRoles200Response(val *GetAllTenantRoles200Response) *NullableGetAllTenantRoles200Response {
	return &NullableGetAllTenantRoles200Response{value: val, isSet: true}
}

func (v NullableGetAllTenantRoles200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAllTenantRoles200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
