/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PhoneOTPModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PhoneOTPModel{}

// PhoneOTPModel struct for PhoneOTPModel
type PhoneOTPModel struct {
	// The Google reCAPTCHA response which is sent to the server for verification.
	GRecaptchaResponse NullableString `json:"g-recaptcha-response,omitempty"`
	// The QQ Captcha ticket which is sent to the server for verification.
	QqCaptchaTicket NullableString `json:"qq_captcha_ticket,omitempty"`
	// The QQ Captcha random string which is sent to the server for verification.
	QqCaptchaRandstr NullableString `json:"qq_captcha_randstr,omitempty"`
	// The hCaptcha response which is sent to the server for verification.
	HCaptchaResponse NullableString `json:"h-captcha-response,omitempty"`
	// The one-time Password (OTP).
	OTP string `json:"OTP"`
	// The Phone number associated with the OTP.
	Phone string `json:"Phone"`
	// Optional security answers for additional verification.
	SecurityAnswer *map[string]string `json:"SecurityAnswer,omitempty"`
}

type _PhoneOTPModel PhoneOTPModel

// NewPhoneOTPModel instantiates a new PhoneOTPModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPhoneOTPModel(oTP string, phone string) *PhoneOTPModel {
	this := PhoneOTPModel{}
	this.OTP = oTP
	this.Phone = phone
	return &this
}

// NewPhoneOTPModelWithDefaults instantiates a new PhoneOTPModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPhoneOTPModelWithDefaults() *PhoneOTPModel {
	this := PhoneOTPModel{}
	return &this
}

// GetGRecaptchaResponse returns the GRecaptchaResponse field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PhoneOTPModel) GetGRecaptchaResponse() string {
	if o == nil || IsNil(o.GRecaptchaResponse.Get()) {
		var ret string
		return ret
	}
	return *o.GRecaptchaResponse.Get()
}

// GetGRecaptchaResponseOk returns a tuple with the GRecaptchaResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PhoneOTPModel) GetGRecaptchaResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GRecaptchaResponse.Get(), o.GRecaptchaResponse.IsSet()
}

// HasGRecaptchaResponse returns a boolean if a field has been set.
func (o *PhoneOTPModel) HasGRecaptchaResponse() bool {
	if o != nil && o.GRecaptchaResponse.IsSet() {
		return true
	}

	return false
}

// SetGRecaptchaResponse gets a reference to the given NullableString and assigns it to the GRecaptchaResponse field.
func (o *PhoneOTPModel) SetGRecaptchaResponse(v string) {
	o.GRecaptchaResponse.Set(&v)
}

// SetGRecaptchaResponseNil sets the value for GRecaptchaResponse to be an explicit nil
func (o *PhoneOTPModel) SetGRecaptchaResponseNil() {
	o.GRecaptchaResponse.Set(nil)
}

// UnsetGRecaptchaResponse ensures that no value is present for GRecaptchaResponse, not even an explicit nil
func (o *PhoneOTPModel) UnsetGRecaptchaResponse() {
	o.GRecaptchaResponse.Unset()
}

// GetQqCaptchaTicket returns the QqCaptchaTicket field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PhoneOTPModel) GetQqCaptchaTicket() string {
	if o == nil || IsNil(o.QqCaptchaTicket.Get()) {
		var ret string
		return ret
	}
	return *o.QqCaptchaTicket.Get()
}

// GetQqCaptchaTicketOk returns a tuple with the QqCaptchaTicket field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PhoneOTPModel) GetQqCaptchaTicketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QqCaptchaTicket.Get(), o.QqCaptchaTicket.IsSet()
}

// HasQqCaptchaTicket returns a boolean if a field has been set.
func (o *PhoneOTPModel) HasQqCaptchaTicket() bool {
	if o != nil && o.QqCaptchaTicket.IsSet() {
		return true
	}

	return false
}

// SetQqCaptchaTicket gets a reference to the given NullableString and assigns it to the QqCaptchaTicket field.
func (o *PhoneOTPModel) SetQqCaptchaTicket(v string) {
	o.QqCaptchaTicket.Set(&v)
}

// SetQqCaptchaTicketNil sets the value for QqCaptchaTicket to be an explicit nil
func (o *PhoneOTPModel) SetQqCaptchaTicketNil() {
	o.QqCaptchaTicket.Set(nil)
}

// UnsetQqCaptchaTicket ensures that no value is present for QqCaptchaTicket, not even an explicit nil
func (o *PhoneOTPModel) UnsetQqCaptchaTicket() {
	o.QqCaptchaTicket.Unset()
}

// GetQqCaptchaRandstr returns the QqCaptchaRandstr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PhoneOTPModel) GetQqCaptchaRandstr() string {
	if o == nil || IsNil(o.QqCaptchaRandstr.Get()) {
		var ret string
		return ret
	}
	return *o.QqCaptchaRandstr.Get()
}

// GetQqCaptchaRandstrOk returns a tuple with the QqCaptchaRandstr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PhoneOTPModel) GetQqCaptchaRandstrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QqCaptchaRandstr.Get(), o.QqCaptchaRandstr.IsSet()
}

// HasQqCaptchaRandstr returns a boolean if a field has been set.
func (o *PhoneOTPModel) HasQqCaptchaRandstr() bool {
	if o != nil && o.QqCaptchaRandstr.IsSet() {
		return true
	}

	return false
}

// SetQqCaptchaRandstr gets a reference to the given NullableString and assigns it to the QqCaptchaRandstr field.
func (o *PhoneOTPModel) SetQqCaptchaRandstr(v string) {
	o.QqCaptchaRandstr.Set(&v)
}

// SetQqCaptchaRandstrNil sets the value for QqCaptchaRandstr to be an explicit nil
func (o *PhoneOTPModel) SetQqCaptchaRandstrNil() {
	o.QqCaptchaRandstr.Set(nil)
}

// UnsetQqCaptchaRandstr ensures that no value is present for QqCaptchaRandstr, not even an explicit nil
func (o *PhoneOTPModel) UnsetQqCaptchaRandstr() {
	o.QqCaptchaRandstr.Unset()
}

// GetHCaptchaResponse returns the HCaptchaResponse field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PhoneOTPModel) GetHCaptchaResponse() string {
	if o == nil || IsNil(o.HCaptchaResponse.Get()) {
		var ret string
		return ret
	}
	return *o.HCaptchaResponse.Get()
}

// GetHCaptchaResponseOk returns a tuple with the HCaptchaResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PhoneOTPModel) GetHCaptchaResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HCaptchaResponse.Get(), o.HCaptchaResponse.IsSet()
}

// HasHCaptchaResponse returns a boolean if a field has been set.
func (o *PhoneOTPModel) HasHCaptchaResponse() bool {
	if o != nil && o.HCaptchaResponse.IsSet() {
		return true
	}

	return false
}

// SetHCaptchaResponse gets a reference to the given NullableString and assigns it to the HCaptchaResponse field.
func (o *PhoneOTPModel) SetHCaptchaResponse(v string) {
	o.HCaptchaResponse.Set(&v)
}

// SetHCaptchaResponseNil sets the value for HCaptchaResponse to be an explicit nil
func (o *PhoneOTPModel) SetHCaptchaResponseNil() {
	o.HCaptchaResponse.Set(nil)
}

// UnsetHCaptchaResponse ensures that no value is present for HCaptchaResponse, not even an explicit nil
func (o *PhoneOTPModel) UnsetHCaptchaResponse() {
	o.HCaptchaResponse.Unset()
}

// GetOTP returns the OTP field value
func (o *PhoneOTPModel) GetOTP() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OTP
}

// GetOTPOk returns a tuple with the OTP field value
// and a boolean to check if the value has been set.
func (o *PhoneOTPModel) GetOTPOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OTP, true
}

// SetOTP sets field value
func (o *PhoneOTPModel) SetOTP(v string) {
	o.OTP = v
}

// GetPhone returns the Phone field value
func (o *PhoneOTPModel) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *PhoneOTPModel) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *PhoneOTPModel) SetPhone(v string) {
	o.Phone = v
}

// GetSecurityAnswer returns the SecurityAnswer field value if set, zero value otherwise.
func (o *PhoneOTPModel) GetSecurityAnswer() map[string]string {
	if o == nil || IsNil(o.SecurityAnswer) {
		var ret map[string]string
		return ret
	}
	return *o.SecurityAnswer
}

// GetSecurityAnswerOk returns a tuple with the SecurityAnswer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PhoneOTPModel) GetSecurityAnswerOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.SecurityAnswer) {
		return nil, false
	}
	return o.SecurityAnswer, true
}

// HasSecurityAnswer returns a boolean if a field has been set.
func (o *PhoneOTPModel) HasSecurityAnswer() bool {
	if o != nil && !IsNil(o.SecurityAnswer) {
		return true
	}

	return false
}

// SetSecurityAnswer gets a reference to the given map[string]string and assigns it to the SecurityAnswer field.
func (o *PhoneOTPModel) SetSecurityAnswer(v map[string]string) {
	o.SecurityAnswer = &v
}

func (o PhoneOTPModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PhoneOTPModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.GRecaptchaResponse.IsSet() {
		toSerialize["g-recaptcha-response"] = o.GRecaptchaResponse.Get()
	}
	if o.QqCaptchaTicket.IsSet() {
		toSerialize["qq_captcha_ticket"] = o.QqCaptchaTicket.Get()
	}
	if o.QqCaptchaRandstr.IsSet() {
		toSerialize["qq_captcha_randstr"] = o.QqCaptchaRandstr.Get()
	}
	if o.HCaptchaResponse.IsSet() {
		toSerialize["h-captcha-response"] = o.HCaptchaResponse.Get()
	}
	toSerialize["OTP"] = o.OTP
	toSerialize["Phone"] = o.Phone
	if !IsNil(o.SecurityAnswer) {
		toSerialize["SecurityAnswer"] = o.SecurityAnswer
	}
	return toSerialize, nil
}

func (o *PhoneOTPModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"OTP",
		"Phone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPhoneOTPModel := _PhoneOTPModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPhoneOTPModel)

	if err != nil {
		return err
	}

	*o = PhoneOTPModel(varPhoneOTPModel)

	return err
}

type NullablePhoneOTPModel struct {
	value *PhoneOTPModel
	isSet bool
}

func (v NullablePhoneOTPModel) Get() *PhoneOTPModel {
	return v.value
}

func (v *NullablePhoneOTPModel) Set(val *PhoneOTPModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePhoneOTPModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePhoneOTPModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePhoneOTPModel(val *PhoneOTPModel) *NullablePhoneOTPModel {
	return &NullablePhoneOTPModel{value: val, isSet: true}
}

func (v NullablePhoneOTPModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePhoneOTPModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
