/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WorkflowDataInnerNodesValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowDataInnerNodesValue{}

// WorkflowDataInnerNodesValue struct for WorkflowDataInnerNodesValue
type WorkflowDataInnerNodesValue struct {
	Id            *string                                          `json:"id,omitempty"`
	UID           *string                                          `json:"UID,omitempty"`
	Type          *string                                          `json:"type,omitempty"`
	ChildType     *string                                          `json:"childType,omitempty"`
	Data          map[string]interface{}                           `json:"data,omitempty"`
	Formnodeprops NullableWorkflowDataInnerNodesValueFormnodeprops `json:"formnodeprops,omitempty"`
}

// NewWorkflowDataInnerNodesValue instantiates a new WorkflowDataInnerNodesValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowDataInnerNodesValue() *WorkflowDataInnerNodesValue {
	this := WorkflowDataInnerNodesValue{}
	return &this
}

// NewWorkflowDataInnerNodesValueWithDefaults instantiates a new WorkflowDataInnerNodesValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowDataInnerNodesValueWithDefaults() *WorkflowDataInnerNodesValue {
	this := WorkflowDataInnerNodesValue{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WorkflowDataInnerNodesValue) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowDataInnerNodesValue) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WorkflowDataInnerNodesValue) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WorkflowDataInnerNodesValue) SetId(v string) {
	o.Id = &v
}

// GetUID returns the UID field value if set, zero value otherwise.
func (o *WorkflowDataInnerNodesValue) GetUID() string {
	if o == nil || IsNil(o.UID) {
		var ret string
		return ret
	}
	return *o.UID
}

// GetUIDOk returns a tuple with the UID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowDataInnerNodesValue) GetUIDOk() (*string, bool) {
	if o == nil || IsNil(o.UID) {
		return nil, false
	}
	return o.UID, true
}

// HasUID returns a boolean if a field has been set.
func (o *WorkflowDataInnerNodesValue) HasUID() bool {
	if o != nil && !IsNil(o.UID) {
		return true
	}

	return false
}

// SetUID gets a reference to the given string and assigns it to the UID field.
func (o *WorkflowDataInnerNodesValue) SetUID(v string) {
	o.UID = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *WorkflowDataInnerNodesValue) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowDataInnerNodesValue) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *WorkflowDataInnerNodesValue) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *WorkflowDataInnerNodesValue) SetType(v string) {
	o.Type = &v
}

// GetChildType returns the ChildType field value if set, zero value otherwise.
func (o *WorkflowDataInnerNodesValue) GetChildType() string {
	if o == nil || IsNil(o.ChildType) {
		var ret string
		return ret
	}
	return *o.ChildType
}

// GetChildTypeOk returns a tuple with the ChildType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowDataInnerNodesValue) GetChildTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ChildType) {
		return nil, false
	}
	return o.ChildType, true
}

// HasChildType returns a boolean if a field has been set.
func (o *WorkflowDataInnerNodesValue) HasChildType() bool {
	if o != nil && !IsNil(o.ChildType) {
		return true
	}

	return false
}

// SetChildType gets a reference to the given string and assigns it to the ChildType field.
func (o *WorkflowDataInnerNodesValue) SetChildType(v string) {
	o.ChildType = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *WorkflowDataInnerNodesValue) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowDataInnerNodesValue) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *WorkflowDataInnerNodesValue) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *WorkflowDataInnerNodesValue) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetFormnodeprops returns the Formnodeprops field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowDataInnerNodesValue) GetFormnodeprops() WorkflowDataInnerNodesValueFormnodeprops {
	if o == nil || IsNil(o.Formnodeprops.Get()) {
		var ret WorkflowDataInnerNodesValueFormnodeprops
		return ret
	}
	return *o.Formnodeprops.Get()
}

// GetFormnodepropsOk returns a tuple with the Formnodeprops field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowDataInnerNodesValue) GetFormnodepropsOk() (*WorkflowDataInnerNodesValueFormnodeprops, bool) {
	if o == nil {
		return nil, false
	}
	return o.Formnodeprops.Get(), o.Formnodeprops.IsSet()
}

// HasFormnodeprops returns a boolean if a field has been set.
func (o *WorkflowDataInnerNodesValue) HasFormnodeprops() bool {
	if o != nil && o.Formnodeprops.IsSet() {
		return true
	}

	return false
}

// SetFormnodeprops gets a reference to the given NullableWorkflowDataInnerNodesValueFormnodeprops and assigns it to the Formnodeprops field.
func (o *WorkflowDataInnerNodesValue) SetFormnodeprops(v WorkflowDataInnerNodesValueFormnodeprops) {
	o.Formnodeprops.Set(&v)
}

// SetFormnodepropsNil sets the value for Formnodeprops to be an explicit nil
func (o *WorkflowDataInnerNodesValue) SetFormnodepropsNil() {
	o.Formnodeprops.Set(nil)
}

// UnsetFormnodeprops ensures that no value is present for Formnodeprops, not even an explicit nil
func (o *WorkflowDataInnerNodesValue) UnsetFormnodeprops() {
	o.Formnodeprops.Unset()
}

func (o WorkflowDataInnerNodesValue) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowDataInnerNodesValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.UID) {
		toSerialize["UID"] = o.UID
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.ChildType) {
		toSerialize["childType"] = o.ChildType
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.Formnodeprops.IsSet() {
		toSerialize["formnodeprops"] = o.Formnodeprops.Get()
	}
	return toSerialize, nil
}

type NullableWorkflowDataInnerNodesValue struct {
	value *WorkflowDataInnerNodesValue
	isSet bool
}

func (v NullableWorkflowDataInnerNodesValue) Get() *WorkflowDataInnerNodesValue {
	return v.value
}

func (v *NullableWorkflowDataInnerNodesValue) Set(val *WorkflowDataInnerNodesValue) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowDataInnerNodesValue) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowDataInnerNodesValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowDataInnerNodesValue(val *WorkflowDataInnerNodesValue) *NullableWorkflowDataInnerNodesValue {
	return &NullableWorkflowDataInnerNodesValue{value: val, isSet: true}
}

func (v NullableWorkflowDataInnerNodesValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowDataInnerNodesValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
