/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OrganizationsPolicyBasePasswordPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsPolicyBasePasswordPolicy{}

// OrganizationsPolicyBasePasswordPolicy Password policy for the organization
type OrganizationsPolicyBasePasswordPolicy struct {
	// Number of days after which the Password expires
	ExpiryDays *int32 `json:"ExpiryDays,omitempty"`
	// Maximum length of the Password
	MaxLength *int32 `json:"MaxLength,omitempty"`
	// Minimum length of the Password
	MinLength *int32 `json:"MinLength,omitempty"`
	// Indicates if at least one lowercase letter is required in the Password
	RequireLowercase *bool `json:"RequireLowercase,omitempty"`
	// Indicates if at least one number is required in the Password
	RequireNumber *bool `json:"RequireNumber,omitempty"`
	// Indicates if at least one special character is required in the Password
	RequireSpecialChar *bool `json:"RequireSpecialChar,omitempty"`
	// Indicates if at least one uppercase letter is required in the Password
	RequireUppercase *bool `json:"RequireUppercase,omitempty"`
}

// NewOrganizationsPolicyBasePasswordPolicy instantiates a new OrganizationsPolicyBasePasswordPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsPolicyBasePasswordPolicy() *OrganizationsPolicyBasePasswordPolicy {
	this := OrganizationsPolicyBasePasswordPolicy{}
	return &this
}

// NewOrganizationsPolicyBasePasswordPolicyWithDefaults instantiates a new OrganizationsPolicyBasePasswordPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsPolicyBasePasswordPolicyWithDefaults() *OrganizationsPolicyBasePasswordPolicy {
	this := OrganizationsPolicyBasePasswordPolicy{}
	return &this
}

// GetExpiryDays returns the ExpiryDays field value if set, zero value otherwise.
func (o *OrganizationsPolicyBasePasswordPolicy) GetExpiryDays() int32 {
	if o == nil || IsNil(o.ExpiryDays) {
		var ret int32
		return ret
	}
	return *o.ExpiryDays
}

// GetExpiryDaysOk returns a tuple with the ExpiryDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) GetExpiryDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpiryDays) {
		return nil, false
	}
	return o.ExpiryDays, true
}

// HasExpiryDays returns a boolean if a field has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) HasExpiryDays() bool {
	if o != nil && !IsNil(o.ExpiryDays) {
		return true
	}

	return false
}

// SetExpiryDays gets a reference to the given int32 and assigns it to the ExpiryDays field.
func (o *OrganizationsPolicyBasePasswordPolicy) SetExpiryDays(v int32) {
	o.ExpiryDays = &v
}

// GetMaxLength returns the MaxLength field value if set, zero value otherwise.
func (o *OrganizationsPolicyBasePasswordPolicy) GetMaxLength() int32 {
	if o == nil || IsNil(o.MaxLength) {
		var ret int32
		return ret
	}
	return *o.MaxLength
}

// GetMaxLengthOk returns a tuple with the MaxLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) GetMaxLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxLength) {
		return nil, false
	}
	return o.MaxLength, true
}

// HasMaxLength returns a boolean if a field has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) HasMaxLength() bool {
	if o != nil && !IsNil(o.MaxLength) {
		return true
	}

	return false
}

// SetMaxLength gets a reference to the given int32 and assigns it to the MaxLength field.
func (o *OrganizationsPolicyBasePasswordPolicy) SetMaxLength(v int32) {
	o.MaxLength = &v
}

// GetMinLength returns the MinLength field value if set, zero value otherwise.
func (o *OrganizationsPolicyBasePasswordPolicy) GetMinLength() int32 {
	if o == nil || IsNil(o.MinLength) {
		var ret int32
		return ret
	}
	return *o.MinLength
}

// GetMinLengthOk returns a tuple with the MinLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) GetMinLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.MinLength) {
		return nil, false
	}
	return o.MinLength, true
}

// HasMinLength returns a boolean if a field has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) HasMinLength() bool {
	if o != nil && !IsNil(o.MinLength) {
		return true
	}

	return false
}

// SetMinLength gets a reference to the given int32 and assigns it to the MinLength field.
func (o *OrganizationsPolicyBasePasswordPolicy) SetMinLength(v int32) {
	o.MinLength = &v
}

// GetRequireLowercase returns the RequireLowercase field value if set, zero value otherwise.
func (o *OrganizationsPolicyBasePasswordPolicy) GetRequireLowercase() bool {
	if o == nil || IsNil(o.RequireLowercase) {
		var ret bool
		return ret
	}
	return *o.RequireLowercase
}

// GetRequireLowercaseOk returns a tuple with the RequireLowercase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) GetRequireLowercaseOk() (*bool, bool) {
	if o == nil || IsNil(o.RequireLowercase) {
		return nil, false
	}
	return o.RequireLowercase, true
}

// HasRequireLowercase returns a boolean if a field has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) HasRequireLowercase() bool {
	if o != nil && !IsNil(o.RequireLowercase) {
		return true
	}

	return false
}

// SetRequireLowercase gets a reference to the given bool and assigns it to the RequireLowercase field.
func (o *OrganizationsPolicyBasePasswordPolicy) SetRequireLowercase(v bool) {
	o.RequireLowercase = &v
}

// GetRequireNumber returns the RequireNumber field value if set, zero value otherwise.
func (o *OrganizationsPolicyBasePasswordPolicy) GetRequireNumber() bool {
	if o == nil || IsNil(o.RequireNumber) {
		var ret bool
		return ret
	}
	return *o.RequireNumber
}

// GetRequireNumberOk returns a tuple with the RequireNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) GetRequireNumberOk() (*bool, bool) {
	if o == nil || IsNil(o.RequireNumber) {
		return nil, false
	}
	return o.RequireNumber, true
}

// HasRequireNumber returns a boolean if a field has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) HasRequireNumber() bool {
	if o != nil && !IsNil(o.RequireNumber) {
		return true
	}

	return false
}

// SetRequireNumber gets a reference to the given bool and assigns it to the RequireNumber field.
func (o *OrganizationsPolicyBasePasswordPolicy) SetRequireNumber(v bool) {
	o.RequireNumber = &v
}

// GetRequireSpecialChar returns the RequireSpecialChar field value if set, zero value otherwise.
func (o *OrganizationsPolicyBasePasswordPolicy) GetRequireSpecialChar() bool {
	if o == nil || IsNil(o.RequireSpecialChar) {
		var ret bool
		return ret
	}
	return *o.RequireSpecialChar
}

// GetRequireSpecialCharOk returns a tuple with the RequireSpecialChar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) GetRequireSpecialCharOk() (*bool, bool) {
	if o == nil || IsNil(o.RequireSpecialChar) {
		return nil, false
	}
	return o.RequireSpecialChar, true
}

// HasRequireSpecialChar returns a boolean if a field has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) HasRequireSpecialChar() bool {
	if o != nil && !IsNil(o.RequireSpecialChar) {
		return true
	}

	return false
}

// SetRequireSpecialChar gets a reference to the given bool and assigns it to the RequireSpecialChar field.
func (o *OrganizationsPolicyBasePasswordPolicy) SetRequireSpecialChar(v bool) {
	o.RequireSpecialChar = &v
}

// GetRequireUppercase returns the RequireUppercase field value if set, zero value otherwise.
func (o *OrganizationsPolicyBasePasswordPolicy) GetRequireUppercase() bool {
	if o == nil || IsNil(o.RequireUppercase) {
		var ret bool
		return ret
	}
	return *o.RequireUppercase
}

// GetRequireUppercaseOk returns a tuple with the RequireUppercase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) GetRequireUppercaseOk() (*bool, bool) {
	if o == nil || IsNil(o.RequireUppercase) {
		return nil, false
	}
	return o.RequireUppercase, true
}

// HasRequireUppercase returns a boolean if a field has been set.
func (o *OrganizationsPolicyBasePasswordPolicy) HasRequireUppercase() bool {
	if o != nil && !IsNil(o.RequireUppercase) {
		return true
	}

	return false
}

// SetRequireUppercase gets a reference to the given bool and assigns it to the RequireUppercase field.
func (o *OrganizationsPolicyBasePasswordPolicy) SetRequireUppercase(v bool) {
	o.RequireUppercase = &v
}

func (o OrganizationsPolicyBasePasswordPolicy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsPolicyBasePasswordPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExpiryDays) {
		toSerialize["ExpiryDays"] = o.ExpiryDays
	}
	if !IsNil(o.MaxLength) {
		toSerialize["MaxLength"] = o.MaxLength
	}
	if !IsNil(o.MinLength) {
		toSerialize["MinLength"] = o.MinLength
	}
	if !IsNil(o.RequireLowercase) {
		toSerialize["RequireLowercase"] = o.RequireLowercase
	}
	if !IsNil(o.RequireNumber) {
		toSerialize["RequireNumber"] = o.RequireNumber
	}
	if !IsNil(o.RequireSpecialChar) {
		toSerialize["RequireSpecialChar"] = o.RequireSpecialChar
	}
	if !IsNil(o.RequireUppercase) {
		toSerialize["RequireUppercase"] = o.RequireUppercase
	}
	return toSerialize, nil
}

type NullableOrganizationsPolicyBasePasswordPolicy struct {
	value *OrganizationsPolicyBasePasswordPolicy
	isSet bool
}

func (v NullableOrganizationsPolicyBasePasswordPolicy) Get() *OrganizationsPolicyBasePasswordPolicy {
	return v.value
}

func (v *NullableOrganizationsPolicyBasePasswordPolicy) Set(val *OrganizationsPolicyBasePasswordPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsPolicyBasePasswordPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsPolicyBasePasswordPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsPolicyBasePasswordPolicy(val *OrganizationsPolicyBasePasswordPolicy) *NullableOrganizationsPolicyBasePasswordPolicy {
	return &NullableOrganizationsPolicyBasePasswordPolicy{value: val, isSet: true}
}

func (v NullableOrganizationsPolicyBasePasswordPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsPolicyBasePasswordPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
