/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IsDeletedResponseWithCount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IsDeletedResponseWithCount{}

// IsDeletedResponseWithCount struct for IsDeletedResponseWithCount
type IsDeletedResponseWithCount struct {
	// Indicates whether the Account was successfully deleted.
	IsDeleted *bool `json:"IsDeleted,omitempty"`
	// The number of records that were deleted.
	RecordsDeleted *int32 `json:"RecordsDeleted,omitempty"`
}

// NewIsDeletedResponseWithCount instantiates a new IsDeletedResponseWithCount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIsDeletedResponseWithCount() *IsDeletedResponseWithCount {
	this := IsDeletedResponseWithCount{}
	return &this
}

// NewIsDeletedResponseWithCountWithDefaults instantiates a new IsDeletedResponseWithCount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIsDeletedResponseWithCountWithDefaults() *IsDeletedResponseWithCount {
	this := IsDeletedResponseWithCount{}
	return &this
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *IsDeletedResponseWithCount) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsDeletedResponseWithCount) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *IsDeletedResponseWithCount) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *IsDeletedResponseWithCount) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

// GetRecordsDeleted returns the RecordsDeleted field value if set, zero value otherwise.
func (o *IsDeletedResponseWithCount) GetRecordsDeleted() int32 {
	if o == nil || IsNil(o.RecordsDeleted) {
		var ret int32
		return ret
	}
	return *o.RecordsDeleted
}

// GetRecordsDeletedOk returns a tuple with the RecordsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsDeletedResponseWithCount) GetRecordsDeletedOk() (*int32, bool) {
	if o == nil || IsNil(o.RecordsDeleted) {
		return nil, false
	}
	return o.RecordsDeleted, true
}

// HasRecordsDeleted returns a boolean if a field has been set.
func (o *IsDeletedResponseWithCount) HasRecordsDeleted() bool {
	if o != nil && !IsNil(o.RecordsDeleted) {
		return true
	}

	return false
}

// SetRecordsDeleted gets a reference to the given int32 and assigns it to the RecordsDeleted field.
func (o *IsDeletedResponseWithCount) SetRecordsDeleted(v int32) {
	o.RecordsDeleted = &v
}

func (o IsDeletedResponseWithCount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IsDeletedResponseWithCount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsDeleted) {
		toSerialize["IsDeleted"] = o.IsDeleted
	}
	if !IsNil(o.RecordsDeleted) {
		toSerialize["RecordsDeleted"] = o.RecordsDeleted
	}
	return toSerialize, nil
}

type NullableIsDeletedResponseWithCount struct {
	value *IsDeletedResponseWithCount
	isSet bool
}

func (v NullableIsDeletedResponseWithCount) Get() *IsDeletedResponseWithCount {
	return v.value
}

func (v *NullableIsDeletedResponseWithCount) Set(val *IsDeletedResponseWithCount) {
	v.value = val
	v.isSet = true
}

func (v NullableIsDeletedResponseWithCount) IsSet() bool {
	return v.isSet
}

func (v *NullableIsDeletedResponseWithCount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIsDeletedResponseWithCount(val *IsDeletedResponseWithCount) *NullableIsDeletedResponseWithCount {
	return &NullableIsDeletedResponseWithCount{value: val, isSet: true}
}

func (v NullableIsDeletedResponseWithCount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIsDeletedResponseWithCount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
