/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateOAuthClientConfigurationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOAuthClientConfigurationRequest{}

// CreateOAuthClientConfigurationRequest struct for CreateOAuthClientConfigurationRequest
type CreateOAuthClientConfigurationRequest struct {
	AppName           string                                      `json:"AppName"`
	AllowedCorsOrigin []string                                    `json:"AllowedCorsOrigin,omitempty"`
	AllowedScopes     []string                                    `json:"AllowedScopes,omitempty"`
	AudienceScopes    *map[string][]string                        `json:"AudienceScopes,omitempty"`
	BackChannelLogout NullableOAuthClientRequestBackChannelLogout `json:"BackChannelLogout,omitempty"`
	// Whether the client can keep a secret confidential. `confidential` clients (server-side / M2M) authenticate with their secret; `public` clients (SPA / native) default to token endpoint auth method `none` and rely on PKCE. When omitted it is derived server-side from the resolved token endpoint auth method.
	ClientType  *string                        `json:"ClientType,omitempty"`
	Connections *OAuthClientRequestConnections `json:"Connections,omitempty"`
	// Optional free-text description of the application, shown only in the admin console (never exposed to end users).
	Description                *string                                         `json:"Description,omitempty"`
	DeviceCodeConfig           NullableOAuthClientRequestDeviceCodeConfig      `json:"DeviceCodeConfig,omitempty"`
	EnableCorsOrigin           *bool                                           `json:"EnableCorsOrigin,omitempty"`
	ForceReAuthentication      *bool                                           `json:"ForceReAuthentication,omitempty"`
	GrantTypes                 []string                                        `json:"GrantTypes,omitempty"`
	IdTokenAudiences           []string                                        `json:"IdTokenAudiences,omitempty"`
	JwtTokenConfig             NullableOAuthClientRequestJwtTokenConfig        `json:"JwtTokenConfig,omitempty"`
	LoginUrl                   NullableString                                  `json:"LoginUrl,omitempty"`
	LoginRedirectUri           []string                                        `json:"LoginRedirectUri,omitempty"`
	LogoutRedirectUri          []string                                        `json:"LogoutRedirectUri,omitempty"`
	AccessTokenMappingTemplate *string                                         `json:"AccessTokenMappingTemplate,omitempty"`
	IdTokenMappingTemplate     *string                                         `json:"IdTokenMappingTemplate,omitempty"`
	Mapping                    *map[string]string                              `json:"Mapping,omitempty"`
	Metadata                   *map[string]string                              `json:"Metadata,omitempty"`
	RedirectURIExactMatch      *bool                                           `json:"RedirectURIExactMatch,omitempty"`
	RefreshTokenRotation       NullableOAuthClientResponseRefreshTokenRotation `json:"RefreshTokenRotation,omitempty"`
	RefreshTokenTTL            NullableInt32                                   `json:"RefreshTokenTTL,omitempty"`
	SessionTokenTTL            NullableInt32                                   `json:"SessionTokenTTL,omitempty"`
	Secret                     *string                                         `json:"Secret,omitempty"`
	SignedUserInfo             *bool                                           `json:"SignedUserInfo,omitempty"`
	TokenAuthMethod            string                                          `json:"TokenAuthMethod"`
}

type _CreateOAuthClientConfigurationRequest CreateOAuthClientConfigurationRequest

// NewCreateOAuthClientConfigurationRequest instantiates a new CreateOAuthClientConfigurationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOAuthClientConfigurationRequest(appName string, tokenAuthMethod string) *CreateOAuthClientConfigurationRequest {
	this := CreateOAuthClientConfigurationRequest{}
	this.AppName = appName
	this.TokenAuthMethod = tokenAuthMethod
	return &this
}

// NewCreateOAuthClientConfigurationRequestWithDefaults instantiates a new CreateOAuthClientConfigurationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOAuthClientConfigurationRequestWithDefaults() *CreateOAuthClientConfigurationRequest {
	this := CreateOAuthClientConfigurationRequest{}
	return &this
}

// GetAppName returns the AppName field value
func (o *CreateOAuthClientConfigurationRequest) GetAppName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppName
}

// GetAppNameOk returns a tuple with the AppName field value
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetAppNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppName, true
}

// SetAppName sets field value
func (o *CreateOAuthClientConfigurationRequest) SetAppName(v string) {
	o.AppName = v
}

// GetAllowedCorsOrigin returns the AllowedCorsOrigin field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetAllowedCorsOrigin() []string {
	if o == nil || IsNil(o.AllowedCorsOrigin) {
		var ret []string
		return ret
	}
	return o.AllowedCorsOrigin
}

// GetAllowedCorsOriginOk returns a tuple with the AllowedCorsOrigin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetAllowedCorsOriginOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedCorsOrigin) {
		return nil, false
	}
	return o.AllowedCorsOrigin, true
}

// HasAllowedCorsOrigin returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasAllowedCorsOrigin() bool {
	if o != nil && !IsNil(o.AllowedCorsOrigin) {
		return true
	}

	return false
}

// SetAllowedCorsOrigin gets a reference to the given []string and assigns it to the AllowedCorsOrigin field.
func (o *CreateOAuthClientConfigurationRequest) SetAllowedCorsOrigin(v []string) {
	o.AllowedCorsOrigin = v
}

// GetAllowedScopes returns the AllowedScopes field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetAllowedScopes() []string {
	if o == nil || IsNil(o.AllowedScopes) {
		var ret []string
		return ret
	}
	return o.AllowedScopes
}

// GetAllowedScopesOk returns a tuple with the AllowedScopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetAllowedScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedScopes) {
		return nil, false
	}
	return o.AllowedScopes, true
}

// HasAllowedScopes returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasAllowedScopes() bool {
	if o != nil && !IsNil(o.AllowedScopes) {
		return true
	}

	return false
}

// SetAllowedScopes gets a reference to the given []string and assigns it to the AllowedScopes field.
func (o *CreateOAuthClientConfigurationRequest) SetAllowedScopes(v []string) {
	o.AllowedScopes = v
}

// GetAudienceScopes returns the AudienceScopes field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetAudienceScopes() map[string][]string {
	if o == nil || IsNil(o.AudienceScopes) {
		var ret map[string][]string
		return ret
	}
	return *o.AudienceScopes
}

// GetAudienceScopesOk returns a tuple with the AudienceScopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetAudienceScopesOk() (*map[string][]string, bool) {
	if o == nil || IsNil(o.AudienceScopes) {
		return nil, false
	}
	return o.AudienceScopes, true
}

// HasAudienceScopes returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasAudienceScopes() bool {
	if o != nil && !IsNil(o.AudienceScopes) {
		return true
	}

	return false
}

// SetAudienceScopes gets a reference to the given map[string][]string and assigns it to the AudienceScopes field.
func (o *CreateOAuthClientConfigurationRequest) SetAudienceScopes(v map[string][]string) {
	o.AudienceScopes = &v
}

// GetBackChannelLogout returns the BackChannelLogout field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOAuthClientConfigurationRequest) GetBackChannelLogout() OAuthClientRequestBackChannelLogout {
	if o == nil || IsNil(o.BackChannelLogout.Get()) {
		var ret OAuthClientRequestBackChannelLogout
		return ret
	}
	return *o.BackChannelLogout.Get()
}

// GetBackChannelLogoutOk returns a tuple with the BackChannelLogout field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOAuthClientConfigurationRequest) GetBackChannelLogoutOk() (*OAuthClientRequestBackChannelLogout, bool) {
	if o == nil {
		return nil, false
	}
	return o.BackChannelLogout.Get(), o.BackChannelLogout.IsSet()
}

// HasBackChannelLogout returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasBackChannelLogout() bool {
	if o != nil && o.BackChannelLogout.IsSet() {
		return true
	}

	return false
}

// SetBackChannelLogout gets a reference to the given NullableOAuthClientRequestBackChannelLogout and assigns it to the BackChannelLogout field.
func (o *CreateOAuthClientConfigurationRequest) SetBackChannelLogout(v OAuthClientRequestBackChannelLogout) {
	o.BackChannelLogout.Set(&v)
}

// SetBackChannelLogoutNil sets the value for BackChannelLogout to be an explicit nil
func (o *CreateOAuthClientConfigurationRequest) SetBackChannelLogoutNil() {
	o.BackChannelLogout.Set(nil)
}

// UnsetBackChannelLogout ensures that no value is present for BackChannelLogout, not even an explicit nil
func (o *CreateOAuthClientConfigurationRequest) UnsetBackChannelLogout() {
	o.BackChannelLogout.Unset()
}

// GetClientType returns the ClientType field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetClientType() string {
	if o == nil || IsNil(o.ClientType) {
		var ret string
		return ret
	}
	return *o.ClientType
}

// GetClientTypeOk returns a tuple with the ClientType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetClientTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ClientType) {
		return nil, false
	}
	return o.ClientType, true
}

// HasClientType returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasClientType() bool {
	if o != nil && !IsNil(o.ClientType) {
		return true
	}

	return false
}

// SetClientType gets a reference to the given string and assigns it to the ClientType field.
func (o *CreateOAuthClientConfigurationRequest) SetClientType(v string) {
	o.ClientType = &v
}

// GetConnections returns the Connections field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetConnections() OAuthClientRequestConnections {
	if o == nil || IsNil(o.Connections) {
		var ret OAuthClientRequestConnections
		return ret
	}
	return *o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetConnectionsOk() (*OAuthClientRequestConnections, bool) {
	if o == nil || IsNil(o.Connections) {
		return nil, false
	}
	return o.Connections, true
}

// HasConnections returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasConnections() bool {
	if o != nil && !IsNil(o.Connections) {
		return true
	}

	return false
}

// SetConnections gets a reference to the given OAuthClientRequestConnections and assigns it to the Connections field.
func (o *CreateOAuthClientConfigurationRequest) SetConnections(v OAuthClientRequestConnections) {
	o.Connections = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateOAuthClientConfigurationRequest) SetDescription(v string) {
	o.Description = &v
}

// GetDeviceCodeConfig returns the DeviceCodeConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOAuthClientConfigurationRequest) GetDeviceCodeConfig() OAuthClientRequestDeviceCodeConfig {
	if o == nil || IsNil(o.DeviceCodeConfig.Get()) {
		var ret OAuthClientRequestDeviceCodeConfig
		return ret
	}
	return *o.DeviceCodeConfig.Get()
}

// GetDeviceCodeConfigOk returns a tuple with the DeviceCodeConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOAuthClientConfigurationRequest) GetDeviceCodeConfigOk() (*OAuthClientRequestDeviceCodeConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceCodeConfig.Get(), o.DeviceCodeConfig.IsSet()
}

// HasDeviceCodeConfig returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasDeviceCodeConfig() bool {
	if o != nil && o.DeviceCodeConfig.IsSet() {
		return true
	}

	return false
}

// SetDeviceCodeConfig gets a reference to the given NullableOAuthClientRequestDeviceCodeConfig and assigns it to the DeviceCodeConfig field.
func (o *CreateOAuthClientConfigurationRequest) SetDeviceCodeConfig(v OAuthClientRequestDeviceCodeConfig) {
	o.DeviceCodeConfig.Set(&v)
}

// SetDeviceCodeConfigNil sets the value for DeviceCodeConfig to be an explicit nil
func (o *CreateOAuthClientConfigurationRequest) SetDeviceCodeConfigNil() {
	o.DeviceCodeConfig.Set(nil)
}

// UnsetDeviceCodeConfig ensures that no value is present for DeviceCodeConfig, not even an explicit nil
func (o *CreateOAuthClientConfigurationRequest) UnsetDeviceCodeConfig() {
	o.DeviceCodeConfig.Unset()
}

// GetEnableCorsOrigin returns the EnableCorsOrigin field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetEnableCorsOrigin() bool {
	if o == nil || IsNil(o.EnableCorsOrigin) {
		var ret bool
		return ret
	}
	return *o.EnableCorsOrigin
}

// GetEnableCorsOriginOk returns a tuple with the EnableCorsOrigin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetEnableCorsOriginOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableCorsOrigin) {
		return nil, false
	}
	return o.EnableCorsOrigin, true
}

// HasEnableCorsOrigin returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasEnableCorsOrigin() bool {
	if o != nil && !IsNil(o.EnableCorsOrigin) {
		return true
	}

	return false
}

// SetEnableCorsOrigin gets a reference to the given bool and assigns it to the EnableCorsOrigin field.
func (o *CreateOAuthClientConfigurationRequest) SetEnableCorsOrigin(v bool) {
	o.EnableCorsOrigin = &v
}

// GetForceReAuthentication returns the ForceReAuthentication field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetForceReAuthentication() bool {
	if o == nil || IsNil(o.ForceReAuthentication) {
		var ret bool
		return ret
	}
	return *o.ForceReAuthentication
}

// GetForceReAuthenticationOk returns a tuple with the ForceReAuthentication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetForceReAuthenticationOk() (*bool, bool) {
	if o == nil || IsNil(o.ForceReAuthentication) {
		return nil, false
	}
	return o.ForceReAuthentication, true
}

// HasForceReAuthentication returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasForceReAuthentication() bool {
	if o != nil && !IsNil(o.ForceReAuthentication) {
		return true
	}

	return false
}

// SetForceReAuthentication gets a reference to the given bool and assigns it to the ForceReAuthentication field.
func (o *CreateOAuthClientConfigurationRequest) SetForceReAuthentication(v bool) {
	o.ForceReAuthentication = &v
}

// GetGrantTypes returns the GrantTypes field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetGrantTypes() []string {
	if o == nil || IsNil(o.GrantTypes) {
		var ret []string
		return ret
	}
	return o.GrantTypes
}

// GetGrantTypesOk returns a tuple with the GrantTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetGrantTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.GrantTypes) {
		return nil, false
	}
	return o.GrantTypes, true
}

// HasGrantTypes returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasGrantTypes() bool {
	if o != nil && !IsNil(o.GrantTypes) {
		return true
	}

	return false
}

// SetGrantTypes gets a reference to the given []string and assigns it to the GrantTypes field.
func (o *CreateOAuthClientConfigurationRequest) SetGrantTypes(v []string) {
	o.GrantTypes = v
}

// GetIdTokenAudiences returns the IdTokenAudiences field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetIdTokenAudiences() []string {
	if o == nil || IsNil(o.IdTokenAudiences) {
		var ret []string
		return ret
	}
	return o.IdTokenAudiences
}

// GetIdTokenAudiencesOk returns a tuple with the IdTokenAudiences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetIdTokenAudiencesOk() ([]string, bool) {
	if o == nil || IsNil(o.IdTokenAudiences) {
		return nil, false
	}
	return o.IdTokenAudiences, true
}

// HasIdTokenAudiences returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasIdTokenAudiences() bool {
	if o != nil && !IsNil(o.IdTokenAudiences) {
		return true
	}

	return false
}

// SetIdTokenAudiences gets a reference to the given []string and assigns it to the IdTokenAudiences field.
func (o *CreateOAuthClientConfigurationRequest) SetIdTokenAudiences(v []string) {
	o.IdTokenAudiences = v
}

// GetJwtTokenConfig returns the JwtTokenConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOAuthClientConfigurationRequest) GetJwtTokenConfig() OAuthClientRequestJwtTokenConfig {
	if o == nil || IsNil(o.JwtTokenConfig.Get()) {
		var ret OAuthClientRequestJwtTokenConfig
		return ret
	}
	return *o.JwtTokenConfig.Get()
}

// GetJwtTokenConfigOk returns a tuple with the JwtTokenConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOAuthClientConfigurationRequest) GetJwtTokenConfigOk() (*OAuthClientRequestJwtTokenConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.JwtTokenConfig.Get(), o.JwtTokenConfig.IsSet()
}

// HasJwtTokenConfig returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasJwtTokenConfig() bool {
	if o != nil && o.JwtTokenConfig.IsSet() {
		return true
	}

	return false
}

// SetJwtTokenConfig gets a reference to the given NullableOAuthClientRequestJwtTokenConfig and assigns it to the JwtTokenConfig field.
func (o *CreateOAuthClientConfigurationRequest) SetJwtTokenConfig(v OAuthClientRequestJwtTokenConfig) {
	o.JwtTokenConfig.Set(&v)
}

// SetJwtTokenConfigNil sets the value for JwtTokenConfig to be an explicit nil
func (o *CreateOAuthClientConfigurationRequest) SetJwtTokenConfigNil() {
	o.JwtTokenConfig.Set(nil)
}

// UnsetJwtTokenConfig ensures that no value is present for JwtTokenConfig, not even an explicit nil
func (o *CreateOAuthClientConfigurationRequest) UnsetJwtTokenConfig() {
	o.JwtTokenConfig.Unset()
}

// GetLoginUrl returns the LoginUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOAuthClientConfigurationRequest) GetLoginUrl() string {
	if o == nil || IsNil(o.LoginUrl.Get()) {
		var ret string
		return ret
	}
	return *o.LoginUrl.Get()
}

// GetLoginUrlOk returns a tuple with the LoginUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOAuthClientConfigurationRequest) GetLoginUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LoginUrl.Get(), o.LoginUrl.IsSet()
}

// HasLoginUrl returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasLoginUrl() bool {
	if o != nil && o.LoginUrl.IsSet() {
		return true
	}

	return false
}

// SetLoginUrl gets a reference to the given NullableString and assigns it to the LoginUrl field.
func (o *CreateOAuthClientConfigurationRequest) SetLoginUrl(v string) {
	o.LoginUrl.Set(&v)
}

// SetLoginUrlNil sets the value for LoginUrl to be an explicit nil
func (o *CreateOAuthClientConfigurationRequest) SetLoginUrlNil() {
	o.LoginUrl.Set(nil)
}

// UnsetLoginUrl ensures that no value is present for LoginUrl, not even an explicit nil
func (o *CreateOAuthClientConfigurationRequest) UnsetLoginUrl() {
	o.LoginUrl.Unset()
}

// GetLoginRedirectUri returns the LoginRedirectUri field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetLoginRedirectUri() []string {
	if o == nil || IsNil(o.LoginRedirectUri) {
		var ret []string
		return ret
	}
	return o.LoginRedirectUri
}

// GetLoginRedirectUriOk returns a tuple with the LoginRedirectUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetLoginRedirectUriOk() ([]string, bool) {
	if o == nil || IsNil(o.LoginRedirectUri) {
		return nil, false
	}
	return o.LoginRedirectUri, true
}

// HasLoginRedirectUri returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasLoginRedirectUri() bool {
	if o != nil && !IsNil(o.LoginRedirectUri) {
		return true
	}

	return false
}

// SetLoginRedirectUri gets a reference to the given []string and assigns it to the LoginRedirectUri field.
func (o *CreateOAuthClientConfigurationRequest) SetLoginRedirectUri(v []string) {
	o.LoginRedirectUri = v
}

// GetLogoutRedirectUri returns the LogoutRedirectUri field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetLogoutRedirectUri() []string {
	if o == nil || IsNil(o.LogoutRedirectUri) {
		var ret []string
		return ret
	}
	return o.LogoutRedirectUri
}

// GetLogoutRedirectUriOk returns a tuple with the LogoutRedirectUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetLogoutRedirectUriOk() ([]string, bool) {
	if o == nil || IsNil(o.LogoutRedirectUri) {
		return nil, false
	}
	return o.LogoutRedirectUri, true
}

// HasLogoutRedirectUri returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasLogoutRedirectUri() bool {
	if o != nil && !IsNil(o.LogoutRedirectUri) {
		return true
	}

	return false
}

// SetLogoutRedirectUri gets a reference to the given []string and assigns it to the LogoutRedirectUri field.
func (o *CreateOAuthClientConfigurationRequest) SetLogoutRedirectUri(v []string) {
	o.LogoutRedirectUri = v
}

// GetAccessTokenMappingTemplate returns the AccessTokenMappingTemplate field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetAccessTokenMappingTemplate() string {
	if o == nil || IsNil(o.AccessTokenMappingTemplate) {
		var ret string
		return ret
	}
	return *o.AccessTokenMappingTemplate
}

// GetAccessTokenMappingTemplateOk returns a tuple with the AccessTokenMappingTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetAccessTokenMappingTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.AccessTokenMappingTemplate) {
		return nil, false
	}
	return o.AccessTokenMappingTemplate, true
}

// HasAccessTokenMappingTemplate returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasAccessTokenMappingTemplate() bool {
	if o != nil && !IsNil(o.AccessTokenMappingTemplate) {
		return true
	}

	return false
}

// SetAccessTokenMappingTemplate gets a reference to the given string and assigns it to the AccessTokenMappingTemplate field.
func (o *CreateOAuthClientConfigurationRequest) SetAccessTokenMappingTemplate(v string) {
	o.AccessTokenMappingTemplate = &v
}

// GetIdTokenMappingTemplate returns the IdTokenMappingTemplate field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetIdTokenMappingTemplate() string {
	if o == nil || IsNil(o.IdTokenMappingTemplate) {
		var ret string
		return ret
	}
	return *o.IdTokenMappingTemplate
}

// GetIdTokenMappingTemplateOk returns a tuple with the IdTokenMappingTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetIdTokenMappingTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.IdTokenMappingTemplate) {
		return nil, false
	}
	return o.IdTokenMappingTemplate, true
}

// HasIdTokenMappingTemplate returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasIdTokenMappingTemplate() bool {
	if o != nil && !IsNil(o.IdTokenMappingTemplate) {
		return true
	}

	return false
}

// SetIdTokenMappingTemplate gets a reference to the given string and assigns it to the IdTokenMappingTemplate field.
func (o *CreateOAuthClientConfigurationRequest) SetIdTokenMappingTemplate(v string) {
	o.IdTokenMappingTemplate = &v
}

// GetMapping returns the Mapping field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetMapping() map[string]string {
	if o == nil || IsNil(o.Mapping) {
		var ret map[string]string
		return ret
	}
	return *o.Mapping
}

// GetMappingOk returns a tuple with the Mapping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetMappingOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Mapping) {
		return nil, false
	}
	return o.Mapping, true
}

// HasMapping returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasMapping() bool {
	if o != nil && !IsNil(o.Mapping) {
		return true
	}

	return false
}

// SetMapping gets a reference to the given map[string]string and assigns it to the Mapping field.
func (o *CreateOAuthClientConfigurationRequest) SetMapping(v map[string]string) {
	o.Mapping = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *CreateOAuthClientConfigurationRequest) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetRedirectURIExactMatch returns the RedirectURIExactMatch field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetRedirectURIExactMatch() bool {
	if o == nil || IsNil(o.RedirectURIExactMatch) {
		var ret bool
		return ret
	}
	return *o.RedirectURIExactMatch
}

// GetRedirectURIExactMatchOk returns a tuple with the RedirectURIExactMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetRedirectURIExactMatchOk() (*bool, bool) {
	if o == nil || IsNil(o.RedirectURIExactMatch) {
		return nil, false
	}
	return o.RedirectURIExactMatch, true
}

// HasRedirectURIExactMatch returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasRedirectURIExactMatch() bool {
	if o != nil && !IsNil(o.RedirectURIExactMatch) {
		return true
	}

	return false
}

// SetRedirectURIExactMatch gets a reference to the given bool and assigns it to the RedirectURIExactMatch field.
func (o *CreateOAuthClientConfigurationRequest) SetRedirectURIExactMatch(v bool) {
	o.RedirectURIExactMatch = &v
}

// GetRefreshTokenRotation returns the RefreshTokenRotation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOAuthClientConfigurationRequest) GetRefreshTokenRotation() OAuthClientResponseRefreshTokenRotation {
	if o == nil || IsNil(o.RefreshTokenRotation.Get()) {
		var ret OAuthClientResponseRefreshTokenRotation
		return ret
	}
	return *o.RefreshTokenRotation.Get()
}

// GetRefreshTokenRotationOk returns a tuple with the RefreshTokenRotation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOAuthClientConfigurationRequest) GetRefreshTokenRotationOk() (*OAuthClientResponseRefreshTokenRotation, bool) {
	if o == nil {
		return nil, false
	}
	return o.RefreshTokenRotation.Get(), o.RefreshTokenRotation.IsSet()
}

// HasRefreshTokenRotation returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasRefreshTokenRotation() bool {
	if o != nil && o.RefreshTokenRotation.IsSet() {
		return true
	}

	return false
}

// SetRefreshTokenRotation gets a reference to the given NullableOAuthClientResponseRefreshTokenRotation and assigns it to the RefreshTokenRotation field.
func (o *CreateOAuthClientConfigurationRequest) SetRefreshTokenRotation(v OAuthClientResponseRefreshTokenRotation) {
	o.RefreshTokenRotation.Set(&v)
}

// SetRefreshTokenRotationNil sets the value for RefreshTokenRotation to be an explicit nil
func (o *CreateOAuthClientConfigurationRequest) SetRefreshTokenRotationNil() {
	o.RefreshTokenRotation.Set(nil)
}

// UnsetRefreshTokenRotation ensures that no value is present for RefreshTokenRotation, not even an explicit nil
func (o *CreateOAuthClientConfigurationRequest) UnsetRefreshTokenRotation() {
	o.RefreshTokenRotation.Unset()
}

// GetRefreshTokenTTL returns the RefreshTokenTTL field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOAuthClientConfigurationRequest) GetRefreshTokenTTL() int32 {
	if o == nil || IsNil(o.RefreshTokenTTL.Get()) {
		var ret int32
		return ret
	}
	return *o.RefreshTokenTTL.Get()
}

// GetRefreshTokenTTLOk returns a tuple with the RefreshTokenTTL field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOAuthClientConfigurationRequest) GetRefreshTokenTTLOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RefreshTokenTTL.Get(), o.RefreshTokenTTL.IsSet()
}

// HasRefreshTokenTTL returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasRefreshTokenTTL() bool {
	if o != nil && o.RefreshTokenTTL.IsSet() {
		return true
	}

	return false
}

// SetRefreshTokenTTL gets a reference to the given NullableInt32 and assigns it to the RefreshTokenTTL field.
func (o *CreateOAuthClientConfigurationRequest) SetRefreshTokenTTL(v int32) {
	o.RefreshTokenTTL.Set(&v)
}

// SetRefreshTokenTTLNil sets the value for RefreshTokenTTL to be an explicit nil
func (o *CreateOAuthClientConfigurationRequest) SetRefreshTokenTTLNil() {
	o.RefreshTokenTTL.Set(nil)
}

// UnsetRefreshTokenTTL ensures that no value is present for RefreshTokenTTL, not even an explicit nil
func (o *CreateOAuthClientConfigurationRequest) UnsetRefreshTokenTTL() {
	o.RefreshTokenTTL.Unset()
}

// GetSessionTokenTTL returns the SessionTokenTTL field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOAuthClientConfigurationRequest) GetSessionTokenTTL() int32 {
	if o == nil || IsNil(o.SessionTokenTTL.Get()) {
		var ret int32
		return ret
	}
	return *o.SessionTokenTTL.Get()
}

// GetSessionTokenTTLOk returns a tuple with the SessionTokenTTL field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOAuthClientConfigurationRequest) GetSessionTokenTTLOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SessionTokenTTL.Get(), o.SessionTokenTTL.IsSet()
}

// HasSessionTokenTTL returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasSessionTokenTTL() bool {
	if o != nil && o.SessionTokenTTL.IsSet() {
		return true
	}

	return false
}

// SetSessionTokenTTL gets a reference to the given NullableInt32 and assigns it to the SessionTokenTTL field.
func (o *CreateOAuthClientConfigurationRequest) SetSessionTokenTTL(v int32) {
	o.SessionTokenTTL.Set(&v)
}

// SetSessionTokenTTLNil sets the value for SessionTokenTTL to be an explicit nil
func (o *CreateOAuthClientConfigurationRequest) SetSessionTokenTTLNil() {
	o.SessionTokenTTL.Set(nil)
}

// UnsetSessionTokenTTL ensures that no value is present for SessionTokenTTL, not even an explicit nil
func (o *CreateOAuthClientConfigurationRequest) UnsetSessionTokenTTL() {
	o.SessionTokenTTL.Unset()
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *CreateOAuthClientConfigurationRequest) SetSecret(v string) {
	o.Secret = &v
}

// GetSignedUserInfo returns the SignedUserInfo field value if set, zero value otherwise.
func (o *CreateOAuthClientConfigurationRequest) GetSignedUserInfo() bool {
	if o == nil || IsNil(o.SignedUserInfo) {
		var ret bool
		return ret
	}
	return *o.SignedUserInfo
}

// GetSignedUserInfoOk returns a tuple with the SignedUserInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetSignedUserInfoOk() (*bool, bool) {
	if o == nil || IsNil(o.SignedUserInfo) {
		return nil, false
	}
	return o.SignedUserInfo, true
}

// HasSignedUserInfo returns a boolean if a field has been set.
func (o *CreateOAuthClientConfigurationRequest) HasSignedUserInfo() bool {
	if o != nil && !IsNil(o.SignedUserInfo) {
		return true
	}

	return false
}

// SetSignedUserInfo gets a reference to the given bool and assigns it to the SignedUserInfo field.
func (o *CreateOAuthClientConfigurationRequest) SetSignedUserInfo(v bool) {
	o.SignedUserInfo = &v
}

// GetTokenAuthMethod returns the TokenAuthMethod field value
func (o *CreateOAuthClientConfigurationRequest) GetTokenAuthMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenAuthMethod
}

// GetTokenAuthMethodOk returns a tuple with the TokenAuthMethod field value
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientConfigurationRequest) GetTokenAuthMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenAuthMethod, true
}

// SetTokenAuthMethod sets field value
func (o *CreateOAuthClientConfigurationRequest) SetTokenAuthMethod(v string) {
	o.TokenAuthMethod = v
}

func (o CreateOAuthClientConfigurationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOAuthClientConfigurationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["AppName"] = o.AppName
	if !IsNil(o.AllowedCorsOrigin) {
		toSerialize["AllowedCorsOrigin"] = o.AllowedCorsOrigin
	}
	if !IsNil(o.AllowedScopes) {
		toSerialize["AllowedScopes"] = o.AllowedScopes
	}
	if !IsNil(o.AudienceScopes) {
		toSerialize["AudienceScopes"] = o.AudienceScopes
	}
	if o.BackChannelLogout.IsSet() {
		toSerialize["BackChannelLogout"] = o.BackChannelLogout.Get()
	}
	if !IsNil(o.ClientType) {
		toSerialize["ClientType"] = o.ClientType
	}
	if !IsNil(o.Connections) {
		toSerialize["Connections"] = o.Connections
	}
	if !IsNil(o.Description) {
		toSerialize["Description"] = o.Description
	}
	if o.DeviceCodeConfig.IsSet() {
		toSerialize["DeviceCodeConfig"] = o.DeviceCodeConfig.Get()
	}
	if !IsNil(o.EnableCorsOrigin) {
		toSerialize["EnableCorsOrigin"] = o.EnableCorsOrigin
	}
	if !IsNil(o.ForceReAuthentication) {
		toSerialize["ForceReAuthentication"] = o.ForceReAuthentication
	}
	if !IsNil(o.GrantTypes) {
		toSerialize["GrantTypes"] = o.GrantTypes
	}
	if !IsNil(o.IdTokenAudiences) {
		toSerialize["IdTokenAudiences"] = o.IdTokenAudiences
	}
	if o.JwtTokenConfig.IsSet() {
		toSerialize["JwtTokenConfig"] = o.JwtTokenConfig.Get()
	}
	if o.LoginUrl.IsSet() {
		toSerialize["LoginUrl"] = o.LoginUrl.Get()
	}
	if !IsNil(o.LoginRedirectUri) {
		toSerialize["LoginRedirectUri"] = o.LoginRedirectUri
	}
	if !IsNil(o.LogoutRedirectUri) {
		toSerialize["LogoutRedirectUri"] = o.LogoutRedirectUri
	}
	if !IsNil(o.AccessTokenMappingTemplate) {
		toSerialize["AccessTokenMappingTemplate"] = o.AccessTokenMappingTemplate
	}
	if !IsNil(o.IdTokenMappingTemplate) {
		toSerialize["IdTokenMappingTemplate"] = o.IdTokenMappingTemplate
	}
	if !IsNil(o.Mapping) {
		toSerialize["Mapping"] = o.Mapping
	}
	if !IsNil(o.Metadata) {
		toSerialize["Metadata"] = o.Metadata
	}
	if !IsNil(o.RedirectURIExactMatch) {
		toSerialize["RedirectURIExactMatch"] = o.RedirectURIExactMatch
	}
	if o.RefreshTokenRotation.IsSet() {
		toSerialize["RefreshTokenRotation"] = o.RefreshTokenRotation.Get()
	}
	if o.RefreshTokenTTL.IsSet() {
		toSerialize["RefreshTokenTTL"] = o.RefreshTokenTTL.Get()
	}
	if o.SessionTokenTTL.IsSet() {
		toSerialize["SessionTokenTTL"] = o.SessionTokenTTL.Get()
	}
	if !IsNil(o.Secret) {
		toSerialize["Secret"] = o.Secret
	}
	if !IsNil(o.SignedUserInfo) {
		toSerialize["SignedUserInfo"] = o.SignedUserInfo
	}
	toSerialize["TokenAuthMethod"] = o.TokenAuthMethod
	return toSerialize, nil
}

func (o *CreateOAuthClientConfigurationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"AppName",
		"TokenAuthMethod",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOAuthClientConfigurationRequest := _CreateOAuthClientConfigurationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOAuthClientConfigurationRequest)

	if err != nil {
		return err
	}

	*o = CreateOAuthClientConfigurationRequest(varCreateOAuthClientConfigurationRequest)

	return err
}

type NullableCreateOAuthClientConfigurationRequest struct {
	value *CreateOAuthClientConfigurationRequest
	isSet bool
}

func (v NullableCreateOAuthClientConfigurationRequest) Get() *CreateOAuthClientConfigurationRequest {
	return v.value
}

func (v *NullableCreateOAuthClientConfigurationRequest) Set(val *CreateOAuthClientConfigurationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOAuthClientConfigurationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOAuthClientConfigurationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOAuthClientConfigurationRequest(val *CreateOAuthClientConfigurationRequest) *NullableCreateOAuthClientConfigurationRequest {
	return &NullableCreateOAuthClientConfigurationRequest{value: val, isSet: true}
}

func (v NullableCreateOAuthClientConfigurationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOAuthClientConfigurationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
