/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OAuthClientRequestConnectionsCustomIdpInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuthClientRequestConnectionsCustomIdpInner{}

// OAuthClientRequestConnectionsCustomIdpInner struct for OAuthClientRequestConnectionsCustomIdpInner
type OAuthClientRequestConnectionsCustomIdpInner struct {
	IsEnabled    *bool   `json:"IsEnabled,omitempty"`
	ProviderName *string `json:"ProviderName,omitempty"`
}

// NewOAuthClientRequestConnectionsCustomIdpInner instantiates a new OAuthClientRequestConnectionsCustomIdpInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuthClientRequestConnectionsCustomIdpInner() *OAuthClientRequestConnectionsCustomIdpInner {
	this := OAuthClientRequestConnectionsCustomIdpInner{}
	return &this
}

// NewOAuthClientRequestConnectionsCustomIdpInnerWithDefaults instantiates a new OAuthClientRequestConnectionsCustomIdpInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuthClientRequestConnectionsCustomIdpInnerWithDefaults() *OAuthClientRequestConnectionsCustomIdpInner {
	this := OAuthClientRequestConnectionsCustomIdpInner{}
	return &this
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *OAuthClientRequestConnectionsCustomIdpInner) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthClientRequestConnectionsCustomIdpInner) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *OAuthClientRequestConnectionsCustomIdpInner) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *OAuthClientRequestConnectionsCustomIdpInner) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

// GetProviderName returns the ProviderName field value if set, zero value otherwise.
func (o *OAuthClientRequestConnectionsCustomIdpInner) GetProviderName() string {
	if o == nil || IsNil(o.ProviderName) {
		var ret string
		return ret
	}
	return *o.ProviderName
}

// GetProviderNameOk returns a tuple with the ProviderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthClientRequestConnectionsCustomIdpInner) GetProviderNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderName) {
		return nil, false
	}
	return o.ProviderName, true
}

// HasProviderName returns a boolean if a field has been set.
func (o *OAuthClientRequestConnectionsCustomIdpInner) HasProviderName() bool {
	if o != nil && !IsNil(o.ProviderName) {
		return true
	}

	return false
}

// SetProviderName gets a reference to the given string and assigns it to the ProviderName field.
func (o *OAuthClientRequestConnectionsCustomIdpInner) SetProviderName(v string) {
	o.ProviderName = &v
}

func (o OAuthClientRequestConnectionsCustomIdpInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuthClientRequestConnectionsCustomIdpInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsEnabled) {
		toSerialize["IsEnabled"] = o.IsEnabled
	}
	if !IsNil(o.ProviderName) {
		toSerialize["ProviderName"] = o.ProviderName
	}
	return toSerialize, nil
}

type NullableOAuthClientRequestConnectionsCustomIdpInner struct {
	value *OAuthClientRequestConnectionsCustomIdpInner
	isSet bool
}

func (v NullableOAuthClientRequestConnectionsCustomIdpInner) Get() *OAuthClientRequestConnectionsCustomIdpInner {
	return v.value
}

func (v *NullableOAuthClientRequestConnectionsCustomIdpInner) Set(val *OAuthClientRequestConnectionsCustomIdpInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuthClientRequestConnectionsCustomIdpInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuthClientRequestConnectionsCustomIdpInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuthClientRequestConnectionsCustomIdpInner(val *OAuthClientRequestConnectionsCustomIdpInner) *NullableOAuthClientRequestConnectionsCustomIdpInner {
	return &NullableOAuthClientRequestConnectionsCustomIdpInner{value: val, isSet: true}
}

func (v NullableOAuthClientRequestConnectionsCustomIdpInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuthClientRequestConnectionsCustomIdpInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
