/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DuoVerifyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DuoVerifyRequest{}

// DuoVerifyRequest struct for DuoVerifyRequest
type DuoVerifyRequest struct {
	// The state which is received from Duo authenticator.
	State string `json:"State"`
	// The code which is received from Duo authenticator.
	Code string `json:"Code"`
}

type _DuoVerifyRequest DuoVerifyRequest

// NewDuoVerifyRequest instantiates a new DuoVerifyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDuoVerifyRequest(state string, code string) *DuoVerifyRequest {
	this := DuoVerifyRequest{}
	this.State = state
	this.Code = code
	return &this
}

// NewDuoVerifyRequestWithDefaults instantiates a new DuoVerifyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDuoVerifyRequestWithDefaults() *DuoVerifyRequest {
	this := DuoVerifyRequest{}
	return &this
}

// GetState returns the State field value
func (o *DuoVerifyRequest) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *DuoVerifyRequest) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *DuoVerifyRequest) SetState(v string) {
	o.State = v
}

// GetCode returns the Code field value
func (o *DuoVerifyRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *DuoVerifyRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *DuoVerifyRequest) SetCode(v string) {
	o.Code = v
}

func (o DuoVerifyRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DuoVerifyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["State"] = o.State
	toSerialize["Code"] = o.Code
	return toSerialize, nil
}

func (o *DuoVerifyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"State",
		"Code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDuoVerifyRequest := _DuoVerifyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDuoVerifyRequest)

	if err != nil {
		return err
	}

	*o = DuoVerifyRequest(varDuoVerifyRequest)

	return err
}

type NullableDuoVerifyRequest struct {
	value *DuoVerifyRequest
	isSet bool
}

func (v NullableDuoVerifyRequest) Get() *DuoVerifyRequest {
	return v.value
}

func (v *NullableDuoVerifyRequest) Set(val *DuoVerifyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDuoVerifyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDuoVerifyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDuoVerifyRequest(val *DuoVerifyRequest) *NullableDuoVerifyRequest {
	return &NullableDuoVerifyRequest{value: val, isSet: true}
}

func (v NullableDuoVerifyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDuoVerifyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
