/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SecurityQuestionsRender type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecurityQuestionsRender{}

// SecurityQuestionsRender struct for SecurityQuestionsRender
type SecurityQuestionsRender struct {
	// The number of security questions to render.
	RenderQuestionCount int32 `json:"RenderQuestionCount"`
}

type _SecurityQuestionsRender SecurityQuestionsRender

// NewSecurityQuestionsRender instantiates a new SecurityQuestionsRender object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecurityQuestionsRender(renderQuestionCount int32) *SecurityQuestionsRender {
	this := SecurityQuestionsRender{}
	this.RenderQuestionCount = renderQuestionCount
	return &this
}

// NewSecurityQuestionsRenderWithDefaults instantiates a new SecurityQuestionsRender object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecurityQuestionsRenderWithDefaults() *SecurityQuestionsRender {
	this := SecurityQuestionsRender{}
	return &this
}

// GetRenderQuestionCount returns the RenderQuestionCount field value
func (o *SecurityQuestionsRender) GetRenderQuestionCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RenderQuestionCount
}

// GetRenderQuestionCountOk returns a tuple with the RenderQuestionCount field value
// and a boolean to check if the value has been set.
func (o *SecurityQuestionsRender) GetRenderQuestionCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RenderQuestionCount, true
}

// SetRenderQuestionCount sets field value
func (o *SecurityQuestionsRender) SetRenderQuestionCount(v int32) {
	o.RenderQuestionCount = v
}

func (o SecurityQuestionsRender) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecurityQuestionsRender) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["RenderQuestionCount"] = o.RenderQuestionCount
	return toSerialize, nil
}

func (o *SecurityQuestionsRender) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"RenderQuestionCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecurityQuestionsRender := _SecurityQuestionsRender{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecurityQuestionsRender)

	if err != nil {
		return err
	}

	*o = SecurityQuestionsRender(varSecurityQuestionsRender)

	return err
}

type NullableSecurityQuestionsRender struct {
	value *SecurityQuestionsRender
	isSet bool
}

func (v NullableSecurityQuestionsRender) Get() *SecurityQuestionsRender {
	return v.value
}

func (v *NullableSecurityQuestionsRender) Set(val *SecurityQuestionsRender) {
	v.value = val
	v.isSet = true
}

func (v NullableSecurityQuestionsRender) IsSet() bool {
	return v.isSet
}

func (v *NullableSecurityQuestionsRender) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecurityQuestionsRender(val *SecurityQuestionsRender) *NullableSecurityQuestionsRender {
	return &NullableSecurityQuestionsRender{value: val, isSet: true}
}

func (v NullableSecurityQuestionsRender) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecurityQuestionsRender) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
