/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ShopifyLoginUrlResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShopifyLoginUrlResponse{}

// ShopifyLoginUrlResponse struct for ShopifyLoginUrlResponse
type ShopifyLoginUrlResponse struct {
	// Shopify Multipass login URL for the customer.
	Url *string `json:"url,omitempty"`
}

// NewShopifyLoginUrlResponse instantiates a new ShopifyLoginUrlResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShopifyLoginUrlResponse() *ShopifyLoginUrlResponse {
	this := ShopifyLoginUrlResponse{}
	return &this
}

// NewShopifyLoginUrlResponseWithDefaults instantiates a new ShopifyLoginUrlResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShopifyLoginUrlResponseWithDefaults() *ShopifyLoginUrlResponse {
	this := ShopifyLoginUrlResponse{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ShopifyLoginUrlResponse) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShopifyLoginUrlResponse) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ShopifyLoginUrlResponse) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ShopifyLoginUrlResponse) SetUrl(v string) {
	o.Url = &v
}

func (o ShopifyLoginUrlResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShopifyLoginUrlResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableShopifyLoginUrlResponse struct {
	value *ShopifyLoginUrlResponse
	isSet bool
}

func (v NullableShopifyLoginUrlResponse) Get() *ShopifyLoginUrlResponse {
	return v.value
}

func (v *NullableShopifyLoginUrlResponse) Set(val *ShopifyLoginUrlResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableShopifyLoginUrlResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableShopifyLoginUrlResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShopifyLoginUrlResponse(val *ShopifyLoginUrlResponse) *NullableShopifyLoginUrlResponse {
	return &NullableShopifyLoginUrlResponse{value: val, isSet: true}
}

func (v NullableShopifyLoginUrlResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShopifyLoginUrlResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
