/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProfileSuggestionsPeopleToFollowInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileSuggestionsPeopleToFollowInner{}

// ProfileSuggestionsPeopleToFollowInner struct for ProfileSuggestionsPeopleToFollowInner
type ProfileSuggestionsPeopleToFollowInner struct {
	// The unique identifier.
	Id NullableString `json:"Id,omitempty"`
	// The name of the person.
	Name NullableString `json:"Name,omitempty"`
}

// NewProfileSuggestionsPeopleToFollowInner instantiates a new ProfileSuggestionsPeopleToFollowInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileSuggestionsPeopleToFollowInner() *ProfileSuggestionsPeopleToFollowInner {
	this := ProfileSuggestionsPeopleToFollowInner{}
	return &this
}

// NewProfileSuggestionsPeopleToFollowInnerWithDefaults instantiates a new ProfileSuggestionsPeopleToFollowInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileSuggestionsPeopleToFollowInnerWithDefaults() *ProfileSuggestionsPeopleToFollowInner {
	this := ProfileSuggestionsPeopleToFollowInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProfileSuggestionsPeopleToFollowInner) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProfileSuggestionsPeopleToFollowInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ProfileSuggestionsPeopleToFollowInner) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *ProfileSuggestionsPeopleToFollowInner) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *ProfileSuggestionsPeopleToFollowInner) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ProfileSuggestionsPeopleToFollowInner) UnsetId() {
	o.Id.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProfileSuggestionsPeopleToFollowInner) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProfileSuggestionsPeopleToFollowInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ProfileSuggestionsPeopleToFollowInner) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ProfileSuggestionsPeopleToFollowInner) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ProfileSuggestionsPeopleToFollowInner) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ProfileSuggestionsPeopleToFollowInner) UnsetName() {
	o.Name.Unset()
}

func (o ProfileSuggestionsPeopleToFollowInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileSuggestionsPeopleToFollowInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["Id"] = o.Id.Get()
	}
	if o.Name.IsSet() {
		toSerialize["Name"] = o.Name.Get()
	}
	return toSerialize, nil
}

type NullableProfileSuggestionsPeopleToFollowInner struct {
	value *ProfileSuggestionsPeopleToFollowInner
	isSet bool
}

func (v NullableProfileSuggestionsPeopleToFollowInner) Get() *ProfileSuggestionsPeopleToFollowInner {
	return v.value
}

func (v *NullableProfileSuggestionsPeopleToFollowInner) Set(val *ProfileSuggestionsPeopleToFollowInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileSuggestionsPeopleToFollowInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileSuggestionsPeopleToFollowInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileSuggestionsPeopleToFollowInner(val *ProfileSuggestionsPeopleToFollowInner) *NullableProfileSuggestionsPeopleToFollowInner {
	return &NullableProfileSuggestionsPeopleToFollowInner{value: val, isSet: true}
}

func (v NullableProfileSuggestionsPeopleToFollowInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileSuggestionsPeopleToFollowInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
