/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SecondFactorAuthenticationCore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecondFactorAuthenticationCore{}

// SecondFactorAuthenticationCore struct for SecondFactorAuthenticationCore
type SecondFactorAuthenticationCore struct {
	SecurityQuestionAuthenticator *SecondFactorAuthenticator `json:"SecurityQuestionAuthenticator,omitempty"`
}

// NewSecondFactorAuthenticationCore instantiates a new SecondFactorAuthenticationCore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecondFactorAuthenticationCore() *SecondFactorAuthenticationCore {
	this := SecondFactorAuthenticationCore{}
	return &this
}

// NewSecondFactorAuthenticationCoreWithDefaults instantiates a new SecondFactorAuthenticationCore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecondFactorAuthenticationCoreWithDefaults() *SecondFactorAuthenticationCore {
	this := SecondFactorAuthenticationCore{}
	return &this
}

// GetSecurityQuestionAuthenticator returns the SecurityQuestionAuthenticator field value if set, zero value otherwise.
func (o *SecondFactorAuthenticationCore) GetSecurityQuestionAuthenticator() SecondFactorAuthenticator {
	if o == nil || IsNil(o.SecurityQuestionAuthenticator) {
		var ret SecondFactorAuthenticator
		return ret
	}
	return *o.SecurityQuestionAuthenticator
}

// GetSecurityQuestionAuthenticatorOk returns a tuple with the SecurityQuestionAuthenticator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecondFactorAuthenticationCore) GetSecurityQuestionAuthenticatorOk() (*SecondFactorAuthenticator, bool) {
	if o == nil || IsNil(o.SecurityQuestionAuthenticator) {
		return nil, false
	}
	return o.SecurityQuestionAuthenticator, true
}

// HasSecurityQuestionAuthenticator returns a boolean if a field has been set.
func (o *SecondFactorAuthenticationCore) HasSecurityQuestionAuthenticator() bool {
	if o != nil && !IsNil(o.SecurityQuestionAuthenticator) {
		return true
	}

	return false
}

// SetSecurityQuestionAuthenticator gets a reference to the given SecondFactorAuthenticator and assigns it to the SecurityQuestionAuthenticator field.
func (o *SecondFactorAuthenticationCore) SetSecurityQuestionAuthenticator(v SecondFactorAuthenticator) {
	o.SecurityQuestionAuthenticator = &v
}

func (o SecondFactorAuthenticationCore) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecondFactorAuthenticationCore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SecurityQuestionAuthenticator) {
		toSerialize["SecurityQuestionAuthenticator"] = o.SecurityQuestionAuthenticator
	}
	return toSerialize, nil
}

type NullableSecondFactorAuthenticationCore struct {
	value *SecondFactorAuthenticationCore
	isSet bool
}

func (v NullableSecondFactorAuthenticationCore) Get() *SecondFactorAuthenticationCore {
	return v.value
}

func (v *NullableSecondFactorAuthenticationCore) Set(val *SecondFactorAuthenticationCore) {
	v.value = val
	v.isSet = true
}

func (v NullableSecondFactorAuthenticationCore) IsSet() bool {
	return v.isSet
}

func (v *NullableSecondFactorAuthenticationCore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecondFactorAuthenticationCore(val *SecondFactorAuthenticationCore) *NullableSecondFactorAuthenticationCore {
	return &NullableSecondFactorAuthenticationCore{value: val, isSet: true}
}

func (v NullableSecondFactorAuthenticationCore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecondFactorAuthenticationCore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
