/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PasswordLessEmailOTPModelCore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PasswordLessEmailOTPModelCore{}

// PasswordLessEmailOTPModelCore struct for PasswordLessEmailOTPModelCore
type PasswordLessEmailOTPModelCore struct {
	// The security answers which is set for the User, this will be used when the User is blocked for the security question.
	SecurityAnswer map[string]string `json:"SecurityAnswer,omitempty"`
	// The template for the welcome Email.
	WelcomeEmailTemplate *string `json:"WelcomeEmailTemplate,omitempty"`
	// The one-time Password (OTP) for verification.
	Otp string `json:"Otp"`
	// The Email associated with the Account.
	Email string `json:"Email"`
}

type _PasswordLessEmailOTPModelCore PasswordLessEmailOTPModelCore

// NewPasswordLessEmailOTPModelCore instantiates a new PasswordLessEmailOTPModelCore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPasswordLessEmailOTPModelCore(otp string, email string) *PasswordLessEmailOTPModelCore {
	this := PasswordLessEmailOTPModelCore{}
	this.Otp = otp
	this.Email = email
	return &this
}

// NewPasswordLessEmailOTPModelCoreWithDefaults instantiates a new PasswordLessEmailOTPModelCore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPasswordLessEmailOTPModelCoreWithDefaults() *PasswordLessEmailOTPModelCore {
	this := PasswordLessEmailOTPModelCore{}
	return &this
}

// GetSecurityAnswer returns the SecurityAnswer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PasswordLessEmailOTPModelCore) GetSecurityAnswer() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.SecurityAnswer
}

// GetSecurityAnswerOk returns a tuple with the SecurityAnswer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PasswordLessEmailOTPModelCore) GetSecurityAnswerOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.SecurityAnswer) {
		return nil, false
	}
	return &o.SecurityAnswer, true
}

// HasSecurityAnswer returns a boolean if a field has been set.
func (o *PasswordLessEmailOTPModelCore) HasSecurityAnswer() bool {
	if o != nil && !IsNil(o.SecurityAnswer) {
		return true
	}

	return false
}

// SetSecurityAnswer gets a reference to the given map[string]string and assigns it to the SecurityAnswer field.
func (o *PasswordLessEmailOTPModelCore) SetSecurityAnswer(v map[string]string) {
	o.SecurityAnswer = v
}

// GetWelcomeEmailTemplate returns the WelcomeEmailTemplate field value if set, zero value otherwise.
func (o *PasswordLessEmailOTPModelCore) GetWelcomeEmailTemplate() string {
	if o == nil || IsNil(o.WelcomeEmailTemplate) {
		var ret string
		return ret
	}
	return *o.WelcomeEmailTemplate
}

// GetWelcomeEmailTemplateOk returns a tuple with the WelcomeEmailTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PasswordLessEmailOTPModelCore) GetWelcomeEmailTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.WelcomeEmailTemplate) {
		return nil, false
	}
	return o.WelcomeEmailTemplate, true
}

// HasWelcomeEmailTemplate returns a boolean if a field has been set.
func (o *PasswordLessEmailOTPModelCore) HasWelcomeEmailTemplate() bool {
	if o != nil && !IsNil(o.WelcomeEmailTemplate) {
		return true
	}

	return false
}

// SetWelcomeEmailTemplate gets a reference to the given string and assigns it to the WelcomeEmailTemplate field.
func (o *PasswordLessEmailOTPModelCore) SetWelcomeEmailTemplate(v string) {
	o.WelcomeEmailTemplate = &v
}

// GetOtp returns the Otp field value
func (o *PasswordLessEmailOTPModelCore) GetOtp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Otp
}

// GetOtpOk returns a tuple with the Otp field value
// and a boolean to check if the value has been set.
func (o *PasswordLessEmailOTPModelCore) GetOtpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Otp, true
}

// SetOtp sets field value
func (o *PasswordLessEmailOTPModelCore) SetOtp(v string) {
	o.Otp = v
}

// GetEmail returns the Email field value
func (o *PasswordLessEmailOTPModelCore) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *PasswordLessEmailOTPModelCore) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *PasswordLessEmailOTPModelCore) SetEmail(v string) {
	o.Email = v
}

func (o PasswordLessEmailOTPModelCore) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PasswordLessEmailOTPModelCore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.SecurityAnswer != nil {
		toSerialize["SecurityAnswer"] = o.SecurityAnswer
	}
	if !IsNil(o.WelcomeEmailTemplate) {
		toSerialize["WelcomeEmailTemplate"] = o.WelcomeEmailTemplate
	}
	toSerialize["Otp"] = o.Otp
	toSerialize["Email"] = o.Email
	return toSerialize, nil
}

func (o *PasswordLessEmailOTPModelCore) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Otp",
		"Email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPasswordLessEmailOTPModelCore := _PasswordLessEmailOTPModelCore{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPasswordLessEmailOTPModelCore)

	if err != nil {
		return err
	}

	*o = PasswordLessEmailOTPModelCore(varPasswordLessEmailOTPModelCore)

	return err
}

type NullablePasswordLessEmailOTPModelCore struct {
	value *PasswordLessEmailOTPModelCore
	isSet bool
}

func (v NullablePasswordLessEmailOTPModelCore) Get() *PasswordLessEmailOTPModelCore {
	return v.value
}

func (v *NullablePasswordLessEmailOTPModelCore) Set(val *PasswordLessEmailOTPModelCore) {
	v.value = val
	v.isSet = true
}

func (v NullablePasswordLessEmailOTPModelCore) IsSet() bool {
	return v.isSet
}

func (v *NullablePasswordLessEmailOTPModelCore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePasswordLessEmailOTPModelCore(val *PasswordLessEmailOTPModelCore) *NullablePasswordLessEmailOTPModelCore {
	return &NullablePasswordLessEmailOTPModelCore{value: val, isSet: true}
}

func (v NullablePasswordLessEmailOTPModelCore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePasswordLessEmailOTPModelCore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
