/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProfilePhoneNumbersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfilePhoneNumbersInner{}

// ProfilePhoneNumbersInner struct for ProfilePhoneNumbersInner
type ProfilePhoneNumbersInner struct {
	// The type of Phone (e.g., Mobile, Home).
	PhoneType *string `json:"PhoneType,omitempty"`
	// The Phone number.
	PhoneNumber *string `json:"PhoneNumber,omitempty"`
	// The operation performed on the Phone number.
	Operation *string `json:"Operation,omitempty"`
}

// NewProfilePhoneNumbersInner instantiates a new ProfilePhoneNumbersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfilePhoneNumbersInner() *ProfilePhoneNumbersInner {
	this := ProfilePhoneNumbersInner{}
	return &this
}

// NewProfilePhoneNumbersInnerWithDefaults instantiates a new ProfilePhoneNumbersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfilePhoneNumbersInnerWithDefaults() *ProfilePhoneNumbersInner {
	this := ProfilePhoneNumbersInner{}
	return &this
}

// GetPhoneType returns the PhoneType field value if set, zero value otherwise.
func (o *ProfilePhoneNumbersInner) GetPhoneType() string {
	if o == nil || IsNil(o.PhoneType) {
		var ret string
		return ret
	}
	return *o.PhoneType
}

// GetPhoneTypeOk returns a tuple with the PhoneType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfilePhoneNumbersInner) GetPhoneTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneType) {
		return nil, false
	}
	return o.PhoneType, true
}

// HasPhoneType returns a boolean if a field has been set.
func (o *ProfilePhoneNumbersInner) HasPhoneType() bool {
	if o != nil && !IsNil(o.PhoneType) {
		return true
	}

	return false
}

// SetPhoneType gets a reference to the given string and assigns it to the PhoneType field.
func (o *ProfilePhoneNumbersInner) SetPhoneType(v string) {
	o.PhoneType = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *ProfilePhoneNumbersInner) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfilePhoneNumbersInner) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *ProfilePhoneNumbersInner) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *ProfilePhoneNumbersInner) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetOperation returns the Operation field value if set, zero value otherwise.
func (o *ProfilePhoneNumbersInner) GetOperation() string {
	if o == nil || IsNil(o.Operation) {
		var ret string
		return ret
	}
	return *o.Operation
}

// GetOperationOk returns a tuple with the Operation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfilePhoneNumbersInner) GetOperationOk() (*string, bool) {
	if o == nil || IsNil(o.Operation) {
		return nil, false
	}
	return o.Operation, true
}

// HasOperation returns a boolean if a field has been set.
func (o *ProfilePhoneNumbersInner) HasOperation() bool {
	if o != nil && !IsNil(o.Operation) {
		return true
	}

	return false
}

// SetOperation gets a reference to the given string and assigns it to the Operation field.
func (o *ProfilePhoneNumbersInner) SetOperation(v string) {
	o.Operation = &v
}

func (o ProfilePhoneNumbersInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfilePhoneNumbersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PhoneType) {
		toSerialize["PhoneType"] = o.PhoneType
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["PhoneNumber"] = o.PhoneNumber
	}
	if !IsNil(o.Operation) {
		toSerialize["Operation"] = o.Operation
	}
	return toSerialize, nil
}

type NullableProfilePhoneNumbersInner struct {
	value *ProfilePhoneNumbersInner
	isSet bool
}

func (v NullableProfilePhoneNumbersInner) Get() *ProfilePhoneNumbersInner {
	return v.value
}

func (v *NullableProfilePhoneNumbersInner) Set(val *ProfilePhoneNumbersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProfilePhoneNumbersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProfilePhoneNumbersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfilePhoneNumbersInner(val *ProfilePhoneNumbersInner) *NullableProfilePhoneNumbersInner {
	return &NullableProfilePhoneNumbersInner{value: val, isSet: true}
}

func (v NullableProfilePhoneNumbersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfilePhoneNumbersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
