/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ReAuthTwoFAModelCore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReAuthTwoFAModelCore{}

// ReAuthTwoFAModelCore struct for ReAuthTwoFAModelCore
type ReAuthTwoFAModelCore struct {
	Googleauthenticatorcode *string
	Otp                     *string
	Backupcode              *string
	Authenticatorcode       *string
	SecurityAnswer          *map[string]string
}

// NewReAuthTwoFAModelCore instantiates a new ReAuthTwoFAModelCore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReAuthTwoFAModelCore() *ReAuthTwoFAModelCore {
	this := ReAuthTwoFAModelCore{}
	return &this
}

// NewReAuthTwoFAModelCoreWithDefaults instantiates a new ReAuthTwoFAModelCore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReAuthTwoFAModelCoreWithDefaults() *ReAuthTwoFAModelCore {
	this := ReAuthTwoFAModelCore{}
	return &this
}

// GetGoogleauthenticatorcode returns the Googleauthenticatorcode field value if set, zero value otherwise.
func (o *ReAuthTwoFAModelCore) GetGoogleauthenticatorcode() string {
	if o == nil || IsNil(o.Googleauthenticatorcode) {
		var ret string
		return ret
	}
	return *o.Googleauthenticatorcode
}

// GetGoogleauthenticatorcodeOk returns a tuple with the Googleauthenticatorcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReAuthTwoFAModelCore) GetGoogleauthenticatorcodeOk() (*string, bool) {
	if o == nil || IsNil(o.Googleauthenticatorcode) {
		return nil, false
	}
	return o.Googleauthenticatorcode, true
}

// HasGoogleauthenticatorcode returns a boolean if a field has been set.
func (o *ReAuthTwoFAModelCore) HasGoogleauthenticatorcode() bool {
	if o != nil && !IsNil(o.Googleauthenticatorcode) {
		return true
	}

	return false
}

// SetGoogleauthenticatorcode gets a reference to the given string and assigns it to the Googleauthenticatorcode field.
func (o *ReAuthTwoFAModelCore) SetGoogleauthenticatorcode(v string) {
	o.Googleauthenticatorcode = &v
}

// GetOtp returns the Otp field value if set, zero value otherwise.
func (o *ReAuthTwoFAModelCore) GetOtp() string {
	if o == nil || IsNil(o.Otp) {
		var ret string
		return ret
	}
	return *o.Otp
}

// GetOtpOk returns a tuple with the Otp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReAuthTwoFAModelCore) GetOtpOk() (*string, bool) {
	if o == nil || IsNil(o.Otp) {
		return nil, false
	}
	return o.Otp, true
}

// HasOtp returns a boolean if a field has been set.
func (o *ReAuthTwoFAModelCore) HasOtp() bool {
	if o != nil && !IsNil(o.Otp) {
		return true
	}

	return false
}

// SetOtp gets a reference to the given string and assigns it to the Otp field.
func (o *ReAuthTwoFAModelCore) SetOtp(v string) {
	o.Otp = &v
}

// GetBackupcode returns the Backupcode field value if set, zero value otherwise.
func (o *ReAuthTwoFAModelCore) GetBackupcode() string {
	if o == nil || IsNil(o.Backupcode) {
		var ret string
		return ret
	}
	return *o.Backupcode
}

// GetBackupcodeOk returns a tuple with the Backupcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReAuthTwoFAModelCore) GetBackupcodeOk() (*string, bool) {
	if o == nil || IsNil(o.Backupcode) {
		return nil, false
	}
	return o.Backupcode, true
}

// HasBackupcode returns a boolean if a field has been set.
func (o *ReAuthTwoFAModelCore) HasBackupcode() bool {
	if o != nil && !IsNil(o.Backupcode) {
		return true
	}

	return false
}

// SetBackupcode gets a reference to the given string and assigns it to the Backupcode field.
func (o *ReAuthTwoFAModelCore) SetBackupcode(v string) {
	o.Backupcode = &v
}

// GetAuthenticatorcode returns the Authenticatorcode field value if set, zero value otherwise.
func (o *ReAuthTwoFAModelCore) GetAuthenticatorcode() string {
	if o == nil || IsNil(o.Authenticatorcode) {
		var ret string
		return ret
	}
	return *o.Authenticatorcode
}

// GetAuthenticatorcodeOk returns a tuple with the Authenticatorcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReAuthTwoFAModelCore) GetAuthenticatorcodeOk() (*string, bool) {
	if o == nil || IsNil(o.Authenticatorcode) {
		return nil, false
	}
	return o.Authenticatorcode, true
}

// HasAuthenticatorcode returns a boolean if a field has been set.
func (o *ReAuthTwoFAModelCore) HasAuthenticatorcode() bool {
	if o != nil && !IsNil(o.Authenticatorcode) {
		return true
	}

	return false
}

// SetAuthenticatorcode gets a reference to the given string and assigns it to the Authenticatorcode field.
func (o *ReAuthTwoFAModelCore) SetAuthenticatorcode(v string) {
	o.Authenticatorcode = &v
}

// GetSecurityAnswer returns the SecurityAnswer field value if set, zero value otherwise.
func (o *ReAuthTwoFAModelCore) GetSecurityAnswer() map[string]string {
	if o == nil || IsNil(o.SecurityAnswer) {
		var ret map[string]string
		return ret
	}
	return *o.SecurityAnswer
}

// GetSecurityAnswerOk returns a tuple with the SecurityAnswer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReAuthTwoFAModelCore) GetSecurityAnswerOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.SecurityAnswer) {
		return nil, false
	}
	return o.SecurityAnswer, true
}

// HasSecurityAnswer returns a boolean if a field has been set.
func (o *ReAuthTwoFAModelCore) HasSecurityAnswer() bool {
	if o != nil && !IsNil(o.SecurityAnswer) {
		return true
	}

	return false
}

// SetSecurityAnswer gets a reference to the given map[string]string and assigns it to the SecurityAnswer field.
func (o *ReAuthTwoFAModelCore) SetSecurityAnswer(v map[string]string) {
	o.SecurityAnswer = &v
}

func (o ReAuthTwoFAModelCore) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReAuthTwoFAModelCore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Googleauthenticatorcode) {
		toSerialize["googleauthenticatorcode"] = o.Googleauthenticatorcode
	}
	if !IsNil(o.Otp) {
		toSerialize["otp"] = o.Otp
	}
	if !IsNil(o.Backupcode) {
		toSerialize["backupcode"] = o.Backupcode
	}
	if !IsNil(o.Authenticatorcode) {
		toSerialize["authenticatorcode"] = o.Authenticatorcode
	}
	if !IsNil(o.SecurityAnswer) {
		toSerialize["securityAnswer"] = o.SecurityAnswer
	}
	return toSerialize, nil
}

type NullableReAuthTwoFAModelCore struct {
	value *ReAuthTwoFAModelCore
	isSet bool
}

func (v NullableReAuthTwoFAModelCore) Get() *ReAuthTwoFAModelCore {
	return v.value
}

func (v *NullableReAuthTwoFAModelCore) Set(val *ReAuthTwoFAModelCore) {
	v.value = val
	v.isSet = true
}

func (v NullableReAuthTwoFAModelCore) IsSet() bool {
	return v.isSet
}

func (v *NullableReAuthTwoFAModelCore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReAuthTwoFAModelCore(val *ReAuthTwoFAModelCore) *NullableReAuthTwoFAModelCore {
	return &NullableReAuthTwoFAModelCore{value: val, isSet: true}
}

func (v NullableReAuthTwoFAModelCore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReAuthTwoFAModelCore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
