/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProfileRequestModelPatentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileRequestModelPatentsInner{}

// ProfileRequestModelPatentsInner struct for ProfileRequestModelPatentsInner
type ProfileRequestModelPatentsInner struct {
	Id    *string `json:"Id,omitempty"`
	Title *string `json:"Title,omitempty"`
	Date  *string `json:"Date,omitempty"`
}

// NewProfileRequestModelPatentsInner instantiates a new ProfileRequestModelPatentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileRequestModelPatentsInner() *ProfileRequestModelPatentsInner {
	this := ProfileRequestModelPatentsInner{}
	return &this
}

// NewProfileRequestModelPatentsInnerWithDefaults instantiates a new ProfileRequestModelPatentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileRequestModelPatentsInnerWithDefaults() *ProfileRequestModelPatentsInner {
	this := ProfileRequestModelPatentsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProfileRequestModelPatentsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileRequestModelPatentsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProfileRequestModelPatentsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProfileRequestModelPatentsInner) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ProfileRequestModelPatentsInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileRequestModelPatentsInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ProfileRequestModelPatentsInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ProfileRequestModelPatentsInner) SetTitle(v string) {
	o.Title = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *ProfileRequestModelPatentsInner) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileRequestModelPatentsInner) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *ProfileRequestModelPatentsInner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *ProfileRequestModelPatentsInner) SetDate(v string) {
	o.Date = &v
}

func (o ProfileRequestModelPatentsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileRequestModelPatentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["Title"] = o.Title
	}
	if !IsNil(o.Date) {
		toSerialize["Date"] = o.Date
	}
	return toSerialize, nil
}

type NullableProfileRequestModelPatentsInner struct {
	value *ProfileRequestModelPatentsInner
	isSet bool
}

func (v NullableProfileRequestModelPatentsInner) Get() *ProfileRequestModelPatentsInner {
	return v.value
}

func (v *NullableProfileRequestModelPatentsInner) Set(val *ProfileRequestModelPatentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileRequestModelPatentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileRequestModelPatentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileRequestModelPatentsInner(val *ProfileRequestModelPatentsInner) *NullableProfileRequestModelPatentsInner {
	return &NullableProfileRequestModelPatentsInner{value: val, isSet: true}
}

func (v NullableProfileRequestModelPatentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileRequestModelPatentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
