/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ManageRegisterModelPublicationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManageRegisterModelPublicationsInner{}

// ManageRegisterModelPublicationsInner struct for ManageRegisterModelPublicationsInner
type ManageRegisterModelPublicationsInner struct {
	// The ID of the publication.
	Id *string `json:"Id,omitempty"`
	// The title of the publication.
	Title *string `json:"Title,omitempty"`
	// The publisher of the publication.
	Publisher *string `json:"Publisher,omitempty"`
	// The date the publication was published.
	Date *string `json:"Date,omitempty"`
	// The URL of the publication.
	Url *string `json:"Url,omitempty"`
	// A brief summary of the publication.
	Summary *string `json:"Summary,omitempty"`
	// List of authors of the publication.
	Authors []ManageRegisterModelPublicationsInnerAuthorsInner `json:"Authors,omitempty"`
}

// NewManageRegisterModelPublicationsInner instantiates a new ManageRegisterModelPublicationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageRegisterModelPublicationsInner() *ManageRegisterModelPublicationsInner {
	this := ManageRegisterModelPublicationsInner{}
	return &this
}

// NewManageRegisterModelPublicationsInnerWithDefaults instantiates a new ManageRegisterModelPublicationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageRegisterModelPublicationsInnerWithDefaults() *ManageRegisterModelPublicationsInner {
	this := ManageRegisterModelPublicationsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ManageRegisterModelPublicationsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelPublicationsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ManageRegisterModelPublicationsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ManageRegisterModelPublicationsInner) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ManageRegisterModelPublicationsInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelPublicationsInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ManageRegisterModelPublicationsInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ManageRegisterModelPublicationsInner) SetTitle(v string) {
	o.Title = &v
}

// GetPublisher returns the Publisher field value if set, zero value otherwise.
func (o *ManageRegisterModelPublicationsInner) GetPublisher() string {
	if o == nil || IsNil(o.Publisher) {
		var ret string
		return ret
	}
	return *o.Publisher
}

// GetPublisherOk returns a tuple with the Publisher field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelPublicationsInner) GetPublisherOk() (*string, bool) {
	if o == nil || IsNil(o.Publisher) {
		return nil, false
	}
	return o.Publisher, true
}

// HasPublisher returns a boolean if a field has been set.
func (o *ManageRegisterModelPublicationsInner) HasPublisher() bool {
	if o != nil && !IsNil(o.Publisher) {
		return true
	}

	return false
}

// SetPublisher gets a reference to the given string and assigns it to the Publisher field.
func (o *ManageRegisterModelPublicationsInner) SetPublisher(v string) {
	o.Publisher = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *ManageRegisterModelPublicationsInner) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelPublicationsInner) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *ManageRegisterModelPublicationsInner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *ManageRegisterModelPublicationsInner) SetDate(v string) {
	o.Date = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ManageRegisterModelPublicationsInner) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelPublicationsInner) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ManageRegisterModelPublicationsInner) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ManageRegisterModelPublicationsInner) SetUrl(v string) {
	o.Url = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *ManageRegisterModelPublicationsInner) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelPublicationsInner) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *ManageRegisterModelPublicationsInner) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *ManageRegisterModelPublicationsInner) SetSummary(v string) {
	o.Summary = &v
}

// GetAuthors returns the Authors field value if set, zero value otherwise.
func (o *ManageRegisterModelPublicationsInner) GetAuthors() []ManageRegisterModelPublicationsInnerAuthorsInner {
	if o == nil || IsNil(o.Authors) {
		var ret []ManageRegisterModelPublicationsInnerAuthorsInner
		return ret
	}
	return o.Authors
}

// GetAuthorsOk returns a tuple with the Authors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelPublicationsInner) GetAuthorsOk() ([]ManageRegisterModelPublicationsInnerAuthorsInner, bool) {
	if o == nil || IsNil(o.Authors) {
		return nil, false
	}
	return o.Authors, true
}

// HasAuthors returns a boolean if a field has been set.
func (o *ManageRegisterModelPublicationsInner) HasAuthors() bool {
	if o != nil && !IsNil(o.Authors) {
		return true
	}

	return false
}

// SetAuthors gets a reference to the given []ManageRegisterModelPublicationsInnerAuthorsInner and assigns it to the Authors field.
func (o *ManageRegisterModelPublicationsInner) SetAuthors(v []ManageRegisterModelPublicationsInnerAuthorsInner) {
	o.Authors = v
}

func (o ManageRegisterModelPublicationsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManageRegisterModelPublicationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["Title"] = o.Title
	}
	if !IsNil(o.Publisher) {
		toSerialize["Publisher"] = o.Publisher
	}
	if !IsNil(o.Date) {
		toSerialize["Date"] = o.Date
	}
	if !IsNil(o.Url) {
		toSerialize["Url"] = o.Url
	}
	if !IsNil(o.Summary) {
		toSerialize["Summary"] = o.Summary
	}
	if !IsNil(o.Authors) {
		toSerialize["Authors"] = o.Authors
	}
	return toSerialize, nil
}

type NullableManageRegisterModelPublicationsInner struct {
	value *ManageRegisterModelPublicationsInner
	isSet bool
}

func (v NullableManageRegisterModelPublicationsInner) Get() *ManageRegisterModelPublicationsInner {
	return v.value
}

func (v *NullableManageRegisterModelPublicationsInner) Set(val *ManageRegisterModelPublicationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableManageRegisterModelPublicationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableManageRegisterModelPublicationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageRegisterModelPublicationsInner(val *ManageRegisterModelPublicationsInner) *NullableManageRegisterModelPublicationsInner {
	return &NullableManageRegisterModelPublicationsInner{value: val, isSet: true}
}

func (v NullableManageRegisterModelPublicationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageRegisterModelPublicationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
