/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserRolesModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserRolesModel{}

// UserRolesModel struct for UserRolesModel
type UserRolesModel struct {
	// List of User Roles.
	Roles []string `json:"Roles,omitempty"`
}

// NewUserRolesModel instantiates a new UserRolesModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserRolesModel() *UserRolesModel {
	this := UserRolesModel{}
	return &this
}

// NewUserRolesModelWithDefaults instantiates a new UserRolesModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserRolesModelWithDefaults() *UserRolesModel {
	this := UserRolesModel{}
	return &this
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *UserRolesModel) GetRoles() []string {
	if o == nil || IsNil(o.Roles) {
		var ret []string
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserRolesModel) GetRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *UserRolesModel) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []string and assigns it to the Roles field.
func (o *UserRolesModel) SetRoles(v []string) {
	o.Roles = v
}

func (o UserRolesModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserRolesModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Roles) {
		toSerialize["Roles"] = o.Roles
	}
	return toSerialize, nil
}

type NullableUserRolesModel struct {
	value *UserRolesModel
	isSet bool
}

func (v NullableUserRolesModel) Get() *UserRolesModel {
	return v.value
}

func (v *NullableUserRolesModel) Set(val *UserRolesModel) {
	v.value = val
	v.isSet = true
}

func (v NullableUserRolesModel) IsSet() bool {
	return v.isSet
}

func (v *NullableUserRolesModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserRolesModel(val *UserRolesModel) *NullableUserRolesModel {
	return &NullableUserRolesModel{value: val, isSet: true}
}

func (v NullableUserRolesModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserRolesModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
