/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProfileRequestModelFamilyInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileRequestModelFamilyInner{}

// ProfileRequestModelFamilyInner struct for ProfileRequestModelFamilyInner
type ProfileRequestModelFamilyInner struct {
	Id           *string `json:"Id,omitempty"`
	Name         *string `json:"Name,omitempty"`
	Relationship *string `json:"Relationship,omitempty"`
}

// NewProfileRequestModelFamilyInner instantiates a new ProfileRequestModelFamilyInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileRequestModelFamilyInner() *ProfileRequestModelFamilyInner {
	this := ProfileRequestModelFamilyInner{}
	return &this
}

// NewProfileRequestModelFamilyInnerWithDefaults instantiates a new ProfileRequestModelFamilyInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileRequestModelFamilyInnerWithDefaults() *ProfileRequestModelFamilyInner {
	this := ProfileRequestModelFamilyInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProfileRequestModelFamilyInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileRequestModelFamilyInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProfileRequestModelFamilyInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProfileRequestModelFamilyInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProfileRequestModelFamilyInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileRequestModelFamilyInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProfileRequestModelFamilyInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProfileRequestModelFamilyInner) SetName(v string) {
	o.Name = &v
}

// GetRelationship returns the Relationship field value if set, zero value otherwise.
func (o *ProfileRequestModelFamilyInner) GetRelationship() string {
	if o == nil || IsNil(o.Relationship) {
		var ret string
		return ret
	}
	return *o.Relationship
}

// GetRelationshipOk returns a tuple with the Relationship field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileRequestModelFamilyInner) GetRelationshipOk() (*string, bool) {
	if o == nil || IsNil(o.Relationship) {
		return nil, false
	}
	return o.Relationship, true
}

// HasRelationship returns a boolean if a field has been set.
func (o *ProfileRequestModelFamilyInner) HasRelationship() bool {
	if o != nil && !IsNil(o.Relationship) {
		return true
	}

	return false
}

// SetRelationship gets a reference to the given string and assigns it to the Relationship field.
func (o *ProfileRequestModelFamilyInner) SetRelationship(v string) {
	o.Relationship = &v
}

func (o ProfileRequestModelFamilyInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileRequestModelFamilyInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Relationship) {
		toSerialize["Relationship"] = o.Relationship
	}
	return toSerialize, nil
}

type NullableProfileRequestModelFamilyInner struct {
	value *ProfileRequestModelFamilyInner
	isSet bool
}

func (v NullableProfileRequestModelFamilyInner) Get() *ProfileRequestModelFamilyInner {
	return v.value
}

func (v *NullableProfileRequestModelFamilyInner) Set(val *ProfileRequestModelFamilyInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileRequestModelFamilyInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileRequestModelFamilyInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileRequestModelFamilyInner(val *ProfileRequestModelFamilyInner) *NullableProfileRequestModelFamilyInner {
	return &NullableProfileRequestModelFamilyInner{value: val, isSet: true}
}

func (v NullableProfileRequestModelFamilyInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileRequestModelFamilyInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
