/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OAuthDeviceCode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuthDeviceCode{}

// OAuthDeviceCode OAuth Device Code Request
type OAuthDeviceCode struct {
	ClientId string  `json:"client_id"`
	Scope    *string `json:"scope,omitempty"`
}

type _OAuthDeviceCode OAuthDeviceCode

// NewOAuthDeviceCode instantiates a new OAuthDeviceCode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuthDeviceCode(clientId string) *OAuthDeviceCode {
	this := OAuthDeviceCode{}
	this.ClientId = clientId
	return &this
}

// NewOAuthDeviceCodeWithDefaults instantiates a new OAuthDeviceCode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuthDeviceCodeWithDefaults() *OAuthDeviceCode {
	this := OAuthDeviceCode{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *OAuthDeviceCode) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *OAuthDeviceCode) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *OAuthDeviceCode) SetClientId(v string) {
	o.ClientId = v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *OAuthDeviceCode) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthDeviceCode) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *OAuthDeviceCode) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *OAuthDeviceCode) SetScope(v string) {
	o.Scope = &v
}

func (o OAuthDeviceCode) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuthDeviceCode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client_id"] = o.ClientId
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	return toSerialize, nil
}

func (o *OAuthDeviceCode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOAuthDeviceCode := _OAuthDeviceCode{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOAuthDeviceCode)

	if err != nil {
		return err
	}

	*o = OAuthDeviceCode(varOAuthDeviceCode)

	return err
}

type NullableOAuthDeviceCode struct {
	value *OAuthDeviceCode
	isSet bool
}

func (v NullableOAuthDeviceCode) Get() *OAuthDeviceCode {
	return v.value
}

func (v *NullableOAuthDeviceCode) Set(val *OAuthDeviceCode) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuthDeviceCode) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuthDeviceCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuthDeviceCode(val *OAuthDeviceCode) *NullableOAuthDeviceCode {
	return &NullableOAuthDeviceCode{value: val, isSet: true}
}

func (v NullableOAuthDeviceCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuthDeviceCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
