/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the OrganizationsConnectionSamlBaseIDPCertificate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsConnectionSamlBaseIDPCertificate{}

// OrganizationsConnectionSamlBaseIDPCertificate IdP certificate details, including the PEM value and its validity window.
type OrganizationsConnectionSamlBaseIDPCertificate struct {
	// The Identity Provider's certificate in PEM format.
	Certificate *string `json:"Certificate,omitempty"`
	// The expiration date of the IdP certificate.
	NotAfter *time.Time `json:"NotAfter,omitempty"`
	// The start date of the IdP certificate validity.
	NotBefore *time.Time `json:"NotBefore,omitempty"`
}

// NewOrganizationsConnectionSamlBaseIDPCertificate instantiates a new OrganizationsConnectionSamlBaseIDPCertificate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsConnectionSamlBaseIDPCertificate() *OrganizationsConnectionSamlBaseIDPCertificate {
	this := OrganizationsConnectionSamlBaseIDPCertificate{}
	return &this
}

// NewOrganizationsConnectionSamlBaseIDPCertificateWithDefaults instantiates a new OrganizationsConnectionSamlBaseIDPCertificate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsConnectionSamlBaseIDPCertificateWithDefaults() *OrganizationsConnectionSamlBaseIDPCertificate {
	this := OrganizationsConnectionSamlBaseIDPCertificate{}
	return &this
}

// GetCertificate returns the Certificate field value if set, zero value otherwise.
func (o *OrganizationsConnectionSamlBaseIDPCertificate) GetCertificate() string {
	if o == nil || IsNil(o.Certificate) {
		var ret string
		return ret
	}
	return *o.Certificate
}

// GetCertificateOk returns a tuple with the Certificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsConnectionSamlBaseIDPCertificate) GetCertificateOk() (*string, bool) {
	if o == nil || IsNil(o.Certificate) {
		return nil, false
	}
	return o.Certificate, true
}

// HasCertificate returns a boolean if a field has been set.
func (o *OrganizationsConnectionSamlBaseIDPCertificate) HasCertificate() bool {
	if o != nil && !IsNil(o.Certificate) {
		return true
	}

	return false
}

// SetCertificate gets a reference to the given string and assigns it to the Certificate field.
func (o *OrganizationsConnectionSamlBaseIDPCertificate) SetCertificate(v string) {
	o.Certificate = &v
}

// GetNotAfter returns the NotAfter field value if set, zero value otherwise.
func (o *OrganizationsConnectionSamlBaseIDPCertificate) GetNotAfter() time.Time {
	if o == nil || IsNil(o.NotAfter) {
		var ret time.Time
		return ret
	}
	return *o.NotAfter
}

// GetNotAfterOk returns a tuple with the NotAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsConnectionSamlBaseIDPCertificate) GetNotAfterOk() (*time.Time, bool) {
	if o == nil || IsNil(o.NotAfter) {
		return nil, false
	}
	return o.NotAfter, true
}

// HasNotAfter returns a boolean if a field has been set.
func (o *OrganizationsConnectionSamlBaseIDPCertificate) HasNotAfter() bool {
	if o != nil && !IsNil(o.NotAfter) {
		return true
	}

	return false
}

// SetNotAfter gets a reference to the given time.Time and assigns it to the NotAfter field.
func (o *OrganizationsConnectionSamlBaseIDPCertificate) SetNotAfter(v time.Time) {
	o.NotAfter = &v
}

// GetNotBefore returns the NotBefore field value if set, zero value otherwise.
func (o *OrganizationsConnectionSamlBaseIDPCertificate) GetNotBefore() time.Time {
	if o == nil || IsNil(o.NotBefore) {
		var ret time.Time
		return ret
	}
	return *o.NotBefore
}

// GetNotBeforeOk returns a tuple with the NotBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsConnectionSamlBaseIDPCertificate) GetNotBeforeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.NotBefore) {
		return nil, false
	}
	return o.NotBefore, true
}

// HasNotBefore returns a boolean if a field has been set.
func (o *OrganizationsConnectionSamlBaseIDPCertificate) HasNotBefore() bool {
	if o != nil && !IsNil(o.NotBefore) {
		return true
	}

	return false
}

// SetNotBefore gets a reference to the given time.Time and assigns it to the NotBefore field.
func (o *OrganizationsConnectionSamlBaseIDPCertificate) SetNotBefore(v time.Time) {
	o.NotBefore = &v
}

func (o OrganizationsConnectionSamlBaseIDPCertificate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsConnectionSamlBaseIDPCertificate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Certificate) {
		toSerialize["Certificate"] = o.Certificate
	}
	if !IsNil(o.NotAfter) {
		toSerialize["NotAfter"] = o.NotAfter
	}
	if !IsNil(o.NotBefore) {
		toSerialize["NotBefore"] = o.NotBefore
	}
	return toSerialize, nil
}

type NullableOrganizationsConnectionSamlBaseIDPCertificate struct {
	value *OrganizationsConnectionSamlBaseIDPCertificate
	isSet bool
}

func (v NullableOrganizationsConnectionSamlBaseIDPCertificate) Get() *OrganizationsConnectionSamlBaseIDPCertificate {
	return v.value
}

func (v *NullableOrganizationsConnectionSamlBaseIDPCertificate) Set(val *OrganizationsConnectionSamlBaseIDPCertificate) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsConnectionSamlBaseIDPCertificate) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsConnectionSamlBaseIDPCertificate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsConnectionSamlBaseIDPCertificate(val *OrganizationsConnectionSamlBaseIDPCertificate) *NullableOrganizationsConnectionSamlBaseIDPCertificate {
	return &NullableOrganizationsConnectionSamlBaseIDPCertificate{value: val, isSet: true}
}

func (v NullableOrganizationsConnectionSamlBaseIDPCertificate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsConnectionSamlBaseIDPCertificate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
