/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BigCommerceTokenPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BigCommerceTokenPostRequest{}

// BigCommerceTokenPostRequest struct for BigCommerceTokenPostRequest
type BigCommerceTokenPostRequest struct {
	// LoginRadius access token of the authenticated user.
	AccessToken string `json:"access_token"`
	// Optional password for BigCommerce customer creation.
	Password *string `json:"password,omitempty"`
	// URL to redirect the user to after login.
	ReturnUrl *string `json:"return_url,omitempty"`
}

type _BigCommerceTokenPostRequest BigCommerceTokenPostRequest

// NewBigCommerceTokenPostRequest instantiates a new BigCommerceTokenPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBigCommerceTokenPostRequest(accessToken string) *BigCommerceTokenPostRequest {
	this := BigCommerceTokenPostRequest{}
	this.AccessToken = accessToken
	return &this
}

// NewBigCommerceTokenPostRequestWithDefaults instantiates a new BigCommerceTokenPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBigCommerceTokenPostRequestWithDefaults() *BigCommerceTokenPostRequest {
	this := BigCommerceTokenPostRequest{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *BigCommerceTokenPostRequest) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *BigCommerceTokenPostRequest) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *BigCommerceTokenPostRequest) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *BigCommerceTokenPostRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BigCommerceTokenPostRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *BigCommerceTokenPostRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *BigCommerceTokenPostRequest) SetPassword(v string) {
	o.Password = &v
}

// GetReturnUrl returns the ReturnUrl field value if set, zero value otherwise.
func (o *BigCommerceTokenPostRequest) GetReturnUrl() string {
	if o == nil || IsNil(o.ReturnUrl) {
		var ret string
		return ret
	}
	return *o.ReturnUrl
}

// GetReturnUrlOk returns a tuple with the ReturnUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BigCommerceTokenPostRequest) GetReturnUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ReturnUrl) {
		return nil, false
	}
	return o.ReturnUrl, true
}

// HasReturnUrl returns a boolean if a field has been set.
func (o *BigCommerceTokenPostRequest) HasReturnUrl() bool {
	if o != nil && !IsNil(o.ReturnUrl) {
		return true
	}

	return false
}

// SetReturnUrl gets a reference to the given string and assigns it to the ReturnUrl field.
func (o *BigCommerceTokenPostRequest) SetReturnUrl(v string) {
	o.ReturnUrl = &v
}

func (o BigCommerceTokenPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BigCommerceTokenPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.ReturnUrl) {
		toSerialize["return_url"] = o.ReturnUrl
	}
	return toSerialize, nil
}

func (o *BigCommerceTokenPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBigCommerceTokenPostRequest := _BigCommerceTokenPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBigCommerceTokenPostRequest)

	if err != nil {
		return err
	}

	*o = BigCommerceTokenPostRequest(varBigCommerceTokenPostRequest)

	return err
}

type NullableBigCommerceTokenPostRequest struct {
	value *BigCommerceTokenPostRequest
	isSet bool
}

func (v NullableBigCommerceTokenPostRequest) Get() *BigCommerceTokenPostRequest {
	return v.value
}

func (v *NullableBigCommerceTokenPostRequest) Set(val *BigCommerceTokenPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBigCommerceTokenPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBigCommerceTokenPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBigCommerceTokenPostRequest(val *BigCommerceTokenPostRequest) *NullableBigCommerceTokenPostRequest {
	return &NullableBigCommerceTokenPostRequest{value: val, isSet: true}
}

func (v NullableBigCommerceTokenPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBigCommerceTokenPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
