/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ProfileJobBookmarksInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileJobBookmarksInner{}

// ProfileJobBookmarksInner struct for ProfileJobBookmarksInner
type ProfileJobBookmarksInner struct {
	// Indicates if the job has been applied for.
	IsApplied *bool `json:"IsApplied,omitempty"`
	// Indicates if the job has been saved.
	IsSaved *bool `json:"IsSaved,omitempty"`
	// The timestamp of the job application.
	ApplyTimestamp *time.Time `json:"ApplyTimestamp,omitempty"`
	// The timestamp of the job being saved.
	SavedTimestamp *time.Time                   `json:"SavedTimestamp,omitempty"`
	Job            *ProfileJobBookmarksInnerJob `json:"Job,omitempty"`
}

// NewProfileJobBookmarksInner instantiates a new ProfileJobBookmarksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileJobBookmarksInner() *ProfileJobBookmarksInner {
	this := ProfileJobBookmarksInner{}
	return &this
}

// NewProfileJobBookmarksInnerWithDefaults instantiates a new ProfileJobBookmarksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileJobBookmarksInnerWithDefaults() *ProfileJobBookmarksInner {
	this := ProfileJobBookmarksInner{}
	return &this
}

// GetIsApplied returns the IsApplied field value if set, zero value otherwise.
func (o *ProfileJobBookmarksInner) GetIsApplied() bool {
	if o == nil || IsNil(o.IsApplied) {
		var ret bool
		return ret
	}
	return *o.IsApplied
}

// GetIsAppliedOk returns a tuple with the IsApplied field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileJobBookmarksInner) GetIsAppliedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsApplied) {
		return nil, false
	}
	return o.IsApplied, true
}

// HasIsApplied returns a boolean if a field has been set.
func (o *ProfileJobBookmarksInner) HasIsApplied() bool {
	if o != nil && !IsNil(o.IsApplied) {
		return true
	}

	return false
}

// SetIsApplied gets a reference to the given bool and assigns it to the IsApplied field.
func (o *ProfileJobBookmarksInner) SetIsApplied(v bool) {
	o.IsApplied = &v
}

// GetIsSaved returns the IsSaved field value if set, zero value otherwise.
func (o *ProfileJobBookmarksInner) GetIsSaved() bool {
	if o == nil || IsNil(o.IsSaved) {
		var ret bool
		return ret
	}
	return *o.IsSaved
}

// GetIsSavedOk returns a tuple with the IsSaved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileJobBookmarksInner) GetIsSavedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSaved) {
		return nil, false
	}
	return o.IsSaved, true
}

// HasIsSaved returns a boolean if a field has been set.
func (o *ProfileJobBookmarksInner) HasIsSaved() bool {
	if o != nil && !IsNil(o.IsSaved) {
		return true
	}

	return false
}

// SetIsSaved gets a reference to the given bool and assigns it to the IsSaved field.
func (o *ProfileJobBookmarksInner) SetIsSaved(v bool) {
	o.IsSaved = &v
}

// GetApplyTimestamp returns the ApplyTimestamp field value if set, zero value otherwise.
func (o *ProfileJobBookmarksInner) GetApplyTimestamp() time.Time {
	if o == nil || IsNil(o.ApplyTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.ApplyTimestamp
}

// GetApplyTimestampOk returns a tuple with the ApplyTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileJobBookmarksInner) GetApplyTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ApplyTimestamp) {
		return nil, false
	}
	return o.ApplyTimestamp, true
}

// HasApplyTimestamp returns a boolean if a field has been set.
func (o *ProfileJobBookmarksInner) HasApplyTimestamp() bool {
	if o != nil && !IsNil(o.ApplyTimestamp) {
		return true
	}

	return false
}

// SetApplyTimestamp gets a reference to the given time.Time and assigns it to the ApplyTimestamp field.
func (o *ProfileJobBookmarksInner) SetApplyTimestamp(v time.Time) {
	o.ApplyTimestamp = &v
}

// GetSavedTimestamp returns the SavedTimestamp field value if set, zero value otherwise.
func (o *ProfileJobBookmarksInner) GetSavedTimestamp() time.Time {
	if o == nil || IsNil(o.SavedTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.SavedTimestamp
}

// GetSavedTimestampOk returns a tuple with the SavedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileJobBookmarksInner) GetSavedTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.SavedTimestamp) {
		return nil, false
	}
	return o.SavedTimestamp, true
}

// HasSavedTimestamp returns a boolean if a field has been set.
func (o *ProfileJobBookmarksInner) HasSavedTimestamp() bool {
	if o != nil && !IsNil(o.SavedTimestamp) {
		return true
	}

	return false
}

// SetSavedTimestamp gets a reference to the given time.Time and assigns it to the SavedTimestamp field.
func (o *ProfileJobBookmarksInner) SetSavedTimestamp(v time.Time) {
	o.SavedTimestamp = &v
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *ProfileJobBookmarksInner) GetJob() ProfileJobBookmarksInnerJob {
	if o == nil || IsNil(o.Job) {
		var ret ProfileJobBookmarksInnerJob
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileJobBookmarksInner) GetJobOk() (*ProfileJobBookmarksInnerJob, bool) {
	if o == nil || IsNil(o.Job) {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *ProfileJobBookmarksInner) HasJob() bool {
	if o != nil && !IsNil(o.Job) {
		return true
	}

	return false
}

// SetJob gets a reference to the given ProfileJobBookmarksInnerJob and assigns it to the Job field.
func (o *ProfileJobBookmarksInner) SetJob(v ProfileJobBookmarksInnerJob) {
	o.Job = &v
}

func (o ProfileJobBookmarksInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileJobBookmarksInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsApplied) {
		toSerialize["IsApplied"] = o.IsApplied
	}
	if !IsNil(o.IsSaved) {
		toSerialize["IsSaved"] = o.IsSaved
	}
	if !IsNil(o.ApplyTimestamp) {
		toSerialize["ApplyTimestamp"] = o.ApplyTimestamp
	}
	if !IsNil(o.SavedTimestamp) {
		toSerialize["SavedTimestamp"] = o.SavedTimestamp
	}
	if !IsNil(o.Job) {
		toSerialize["Job"] = o.Job
	}
	return toSerialize, nil
}

type NullableProfileJobBookmarksInner struct {
	value *ProfileJobBookmarksInner
	isSet bool
}

func (v NullableProfileJobBookmarksInner) Get() *ProfileJobBookmarksInner {
	return v.value
}

func (v *NullableProfileJobBookmarksInner) Set(val *ProfileJobBookmarksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileJobBookmarksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileJobBookmarksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileJobBookmarksInner(val *ProfileJobBookmarksInner) *NullableProfileJobBookmarksInner {
	return &NullableProfileJobBookmarksInner{value: val, isSet: true}
}

func (v NullableProfileJobBookmarksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileJobBookmarksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
