/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ProfileWithoutIdentitiesGamesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileWithoutIdentitiesGamesInner{}

// ProfileWithoutIdentitiesGamesInner struct for ProfileWithoutIdentitiesGamesInner
type ProfileWithoutIdentitiesGamesInner struct {
	Id          *string    `json:"Id,omitempty"`
	Category    *string    `json:"Category,omitempty"`
	Name        *string    `json:"Name,omitempty"`
	CreatedDate *time.Time `json:"CreatedDate,omitempty"`
}

// NewProfileWithoutIdentitiesGamesInner instantiates a new ProfileWithoutIdentitiesGamesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileWithoutIdentitiesGamesInner() *ProfileWithoutIdentitiesGamesInner {
	this := ProfileWithoutIdentitiesGamesInner{}
	return &this
}

// NewProfileWithoutIdentitiesGamesInnerWithDefaults instantiates a new ProfileWithoutIdentitiesGamesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileWithoutIdentitiesGamesInnerWithDefaults() *ProfileWithoutIdentitiesGamesInner {
	this := ProfileWithoutIdentitiesGamesInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProfileWithoutIdentitiesGamesInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileWithoutIdentitiesGamesInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProfileWithoutIdentitiesGamesInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProfileWithoutIdentitiesGamesInner) SetId(v string) {
	o.Id = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *ProfileWithoutIdentitiesGamesInner) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileWithoutIdentitiesGamesInner) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *ProfileWithoutIdentitiesGamesInner) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *ProfileWithoutIdentitiesGamesInner) SetCategory(v string) {
	o.Category = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProfileWithoutIdentitiesGamesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileWithoutIdentitiesGamesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProfileWithoutIdentitiesGamesInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProfileWithoutIdentitiesGamesInner) SetName(v string) {
	o.Name = &v
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise.
func (o *ProfileWithoutIdentitiesGamesInner) GetCreatedDate() time.Time {
	if o == nil || IsNil(o.CreatedDate) {
		var ret time.Time
		return ret
	}
	return *o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileWithoutIdentitiesGamesInner) GetCreatedDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedDate) {
		return nil, false
	}
	return o.CreatedDate, true
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *ProfileWithoutIdentitiesGamesInner) HasCreatedDate() bool {
	if o != nil && !IsNil(o.CreatedDate) {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given time.Time and assigns it to the CreatedDate field.
func (o *ProfileWithoutIdentitiesGamesInner) SetCreatedDate(v time.Time) {
	o.CreatedDate = &v
}

func (o ProfileWithoutIdentitiesGamesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileWithoutIdentitiesGamesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Category) {
		toSerialize["Category"] = o.Category
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.CreatedDate) {
		toSerialize["CreatedDate"] = o.CreatedDate
	}
	return toSerialize, nil
}

type NullableProfileWithoutIdentitiesGamesInner struct {
	value *ProfileWithoutIdentitiesGamesInner
	isSet bool
}

func (v NullableProfileWithoutIdentitiesGamesInner) Get() *ProfileWithoutIdentitiesGamesInner {
	return v.value
}

func (v *NullableProfileWithoutIdentitiesGamesInner) Set(val *ProfileWithoutIdentitiesGamesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileWithoutIdentitiesGamesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileWithoutIdentitiesGamesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileWithoutIdentitiesGamesInner(val *ProfileWithoutIdentitiesGamesInner) *NullableProfileWithoutIdentitiesGamesInner {
	return &NullableProfileWithoutIdentitiesGamesInner{value: val, isSet: true}
}

func (v NullableProfileWithoutIdentitiesGamesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileWithoutIdentitiesGamesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
