/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ForgotPinByPhone type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForgotPinByPhone{}

// ForgotPinByPhone This model is used in forgot PIN by Phone API
type ForgotPinByPhone struct {
	// The Phone number of the User.
	Phone string `json:"phone"`
}

type _ForgotPinByPhone ForgotPinByPhone

// NewForgotPinByPhone instantiates a new ForgotPinByPhone object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForgotPinByPhone(phone string) *ForgotPinByPhone {
	this := ForgotPinByPhone{}
	this.Phone = phone
	return &this
}

// NewForgotPinByPhoneWithDefaults instantiates a new ForgotPinByPhone object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForgotPinByPhoneWithDefaults() *ForgotPinByPhone {
	this := ForgotPinByPhone{}
	return &this
}

// GetPhone returns the Phone field value
func (o *ForgotPinByPhone) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *ForgotPinByPhone) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *ForgotPinByPhone) SetPhone(v string) {
	o.Phone = v
}

func (o ForgotPinByPhone) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForgotPinByPhone) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phone"] = o.Phone
	return toSerialize, nil
}

func (o *ForgotPinByPhone) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varForgotPinByPhone := _ForgotPinByPhone{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varForgotPinByPhone)

	if err != nil {
		return err
	}

	*o = ForgotPinByPhone(varForgotPinByPhone)

	return err
}

type NullableForgotPinByPhone struct {
	value *ForgotPinByPhone
	isSet bool
}

func (v NullableForgotPinByPhone) Get() *ForgotPinByPhone {
	return v.value
}

func (v *NullableForgotPinByPhone) Set(val *ForgotPinByPhone) {
	v.value = val
	v.isSet = true
}

func (v NullableForgotPinByPhone) IsSet() bool {
	return v.isSet
}

func (v *NullableForgotPinByPhone) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForgotPinByPhone(val *ForgotPinByPhone) *NullableForgotPinByPhone {
	return &NullableForgotPinByPhone{value: val, isSet: true}
}

func (v NullableForgotPinByPhone) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForgotPinByPhone) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
