/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProfileWithoutIdentitiesMoviesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileWithoutIdentitiesMoviesInner{}

// ProfileWithoutIdentitiesMoviesInner struct for ProfileWithoutIdentitiesMoviesInner
type ProfileWithoutIdentitiesMoviesInner struct {
	MovieName *string `json:"MovieName,omitempty"`
	Genre     *string `json:"Genre,omitempty"`
}

// NewProfileWithoutIdentitiesMoviesInner instantiates a new ProfileWithoutIdentitiesMoviesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileWithoutIdentitiesMoviesInner() *ProfileWithoutIdentitiesMoviesInner {
	this := ProfileWithoutIdentitiesMoviesInner{}
	return &this
}

// NewProfileWithoutIdentitiesMoviesInnerWithDefaults instantiates a new ProfileWithoutIdentitiesMoviesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileWithoutIdentitiesMoviesInnerWithDefaults() *ProfileWithoutIdentitiesMoviesInner {
	this := ProfileWithoutIdentitiesMoviesInner{}
	return &this
}

// GetMovieName returns the MovieName field value if set, zero value otherwise.
func (o *ProfileWithoutIdentitiesMoviesInner) GetMovieName() string {
	if o == nil || IsNil(o.MovieName) {
		var ret string
		return ret
	}
	return *o.MovieName
}

// GetMovieNameOk returns a tuple with the MovieName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileWithoutIdentitiesMoviesInner) GetMovieNameOk() (*string, bool) {
	if o == nil || IsNil(o.MovieName) {
		return nil, false
	}
	return o.MovieName, true
}

// HasMovieName returns a boolean if a field has been set.
func (o *ProfileWithoutIdentitiesMoviesInner) HasMovieName() bool {
	if o != nil && !IsNil(o.MovieName) {
		return true
	}

	return false
}

// SetMovieName gets a reference to the given string and assigns it to the MovieName field.
func (o *ProfileWithoutIdentitiesMoviesInner) SetMovieName(v string) {
	o.MovieName = &v
}

// GetGenre returns the Genre field value if set, zero value otherwise.
func (o *ProfileWithoutIdentitiesMoviesInner) GetGenre() string {
	if o == nil || IsNil(o.Genre) {
		var ret string
		return ret
	}
	return *o.Genre
}

// GetGenreOk returns a tuple with the Genre field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileWithoutIdentitiesMoviesInner) GetGenreOk() (*string, bool) {
	if o == nil || IsNil(o.Genre) {
		return nil, false
	}
	return o.Genre, true
}

// HasGenre returns a boolean if a field has been set.
func (o *ProfileWithoutIdentitiesMoviesInner) HasGenre() bool {
	if o != nil && !IsNil(o.Genre) {
		return true
	}

	return false
}

// SetGenre gets a reference to the given string and assigns it to the Genre field.
func (o *ProfileWithoutIdentitiesMoviesInner) SetGenre(v string) {
	o.Genre = &v
}

func (o ProfileWithoutIdentitiesMoviesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileWithoutIdentitiesMoviesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MovieName) {
		toSerialize["MovieName"] = o.MovieName
	}
	if !IsNil(o.Genre) {
		toSerialize["Genre"] = o.Genre
	}
	return toSerialize, nil
}

type NullableProfileWithoutIdentitiesMoviesInner struct {
	value *ProfileWithoutIdentitiesMoviesInner
	isSet bool
}

func (v NullableProfileWithoutIdentitiesMoviesInner) Get() *ProfileWithoutIdentitiesMoviesInner {
	return v.value
}

func (v *NullableProfileWithoutIdentitiesMoviesInner) Set(val *ProfileWithoutIdentitiesMoviesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileWithoutIdentitiesMoviesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileWithoutIdentitiesMoviesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileWithoutIdentitiesMoviesInner(val *ProfileWithoutIdentitiesMoviesInner) *NullableProfileWithoutIdentitiesMoviesInner {
	return &NullableProfileWithoutIdentitiesMoviesInner{value: val, isSet: true}
}

func (v NullableProfileWithoutIdentitiesMoviesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileWithoutIdentitiesMoviesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
