/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ConsentEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsentEvent{}

// ConsentEvent struct for ConsentEvent
type ConsentEvent struct {
	Event    string `json:"event"`
	Iscustom bool   `json:"iscustom"`
}

type _ConsentEvent ConsentEvent

// NewConsentEvent instantiates a new ConsentEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsentEvent(event string, iscustom bool) *ConsentEvent {
	this := ConsentEvent{}
	this.Event = event
	this.Iscustom = iscustom
	return &this
}

// NewConsentEventWithDefaults instantiates a new ConsentEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsentEventWithDefaults() *ConsentEvent {
	this := ConsentEvent{}
	return &this
}

// GetEvent returns the Event field value
func (o *ConsentEvent) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *ConsentEvent) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *ConsentEvent) SetEvent(v string) {
	o.Event = v
}

// GetIscustom returns the Iscustom field value
func (o *ConsentEvent) GetIscustom() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Iscustom
}

// GetIscustomOk returns a tuple with the Iscustom field value
// and a boolean to check if the value has been set.
func (o *ConsentEvent) GetIscustomOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Iscustom, true
}

// SetIscustom sets field value
func (o *ConsentEvent) SetIscustom(v bool) {
	o.Iscustom = v
}

func (o ConsentEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsentEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	toSerialize["iscustom"] = o.Iscustom
	return toSerialize, nil
}

func (o *ConsentEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
		"iscustom",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsentEvent := _ConsentEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsentEvent)

	if err != nil {
		return err
	}

	*o = ConsentEvent(varConsentEvent)

	return err
}

type NullableConsentEvent struct {
	value *ConsentEvent
	isSet bool
}

func (v NullableConsentEvent) Get() *ConsentEvent {
	return v.value
}

func (v *NullableConsentEvent) Set(val *ConsentEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableConsentEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableConsentEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsentEvent(val *ConsentEvent) *NullableConsentEvent {
	return &NullableConsentEvent{value: val, isSet: true}
}

func (v NullableConsentEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsentEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
