/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ManageRegisterModelPositionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManageRegisterModelPositionsInner{}

// ManageRegisterModelPositionsInner struct for ManageRegisterModelPositionsInner
type ManageRegisterModelPositionsInner struct {
	// The position held by the User.
	Position *string `json:"Position,omitempty"`
	// The company where the position was held.
	Company *string `json:"Company,omitempty"`
	// The start date of the position.
	StartDate *time.Time `json:"StartDate,omitempty"`
	// The end date of the position.
	EndDate *time.Time `json:"EndDate,omitempty"`
	// Indicates if the position is current.
	IsCurrent *bool `json:"IsCurrent,omitempty"`
}

// NewManageRegisterModelPositionsInner instantiates a new ManageRegisterModelPositionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageRegisterModelPositionsInner() *ManageRegisterModelPositionsInner {
	this := ManageRegisterModelPositionsInner{}
	return &this
}

// NewManageRegisterModelPositionsInnerWithDefaults instantiates a new ManageRegisterModelPositionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageRegisterModelPositionsInnerWithDefaults() *ManageRegisterModelPositionsInner {
	this := ManageRegisterModelPositionsInner{}
	return &this
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *ManageRegisterModelPositionsInner) GetPosition() string {
	if o == nil || IsNil(o.Position) {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelPositionsInner) GetPositionOk() (*string, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *ManageRegisterModelPositionsInner) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *ManageRegisterModelPositionsInner) SetPosition(v string) {
	o.Position = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *ManageRegisterModelPositionsInner) GetCompany() string {
	if o == nil || IsNil(o.Company) {
		var ret string
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelPositionsInner) GetCompanyOk() (*string, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *ManageRegisterModelPositionsInner) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given string and assigns it to the Company field.
func (o *ManageRegisterModelPositionsInner) SetCompany(v string) {
	o.Company = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *ManageRegisterModelPositionsInner) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelPositionsInner) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *ManageRegisterModelPositionsInner) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *ManageRegisterModelPositionsInner) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *ManageRegisterModelPositionsInner) GetEndDate() time.Time {
	if o == nil || IsNil(o.EndDate) {
		var ret time.Time
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelPositionsInner) GetEndDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *ManageRegisterModelPositionsInner) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given time.Time and assigns it to the EndDate field.
func (o *ManageRegisterModelPositionsInner) SetEndDate(v time.Time) {
	o.EndDate = &v
}

// GetIsCurrent returns the IsCurrent field value if set, zero value otherwise.
func (o *ManageRegisterModelPositionsInner) GetIsCurrent() bool {
	if o == nil || IsNil(o.IsCurrent) {
		var ret bool
		return ret
	}
	return *o.IsCurrent
}

// GetIsCurrentOk returns a tuple with the IsCurrent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelPositionsInner) GetIsCurrentOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCurrent) {
		return nil, false
	}
	return o.IsCurrent, true
}

// HasIsCurrent returns a boolean if a field has been set.
func (o *ManageRegisterModelPositionsInner) HasIsCurrent() bool {
	if o != nil && !IsNil(o.IsCurrent) {
		return true
	}

	return false
}

// SetIsCurrent gets a reference to the given bool and assigns it to the IsCurrent field.
func (o *ManageRegisterModelPositionsInner) SetIsCurrent(v bool) {
	o.IsCurrent = &v
}

func (o ManageRegisterModelPositionsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManageRegisterModelPositionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Position) {
		toSerialize["Position"] = o.Position
	}
	if !IsNil(o.Company) {
		toSerialize["Company"] = o.Company
	}
	if !IsNil(o.StartDate) {
		toSerialize["StartDate"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["EndDate"] = o.EndDate
	}
	if !IsNil(o.IsCurrent) {
		toSerialize["IsCurrent"] = o.IsCurrent
	}
	return toSerialize, nil
}

type NullableManageRegisterModelPositionsInner struct {
	value *ManageRegisterModelPositionsInner
	isSet bool
}

func (v NullableManageRegisterModelPositionsInner) Get() *ManageRegisterModelPositionsInner {
	return v.value
}

func (v *NullableManageRegisterModelPositionsInner) Set(val *ManageRegisterModelPositionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableManageRegisterModelPositionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableManageRegisterModelPositionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageRegisterModelPositionsInner(val *ManageRegisterModelPositionsInner) *NullableManageRegisterModelPositionsInner {
	return &NullableManageRegisterModelPositionsInner{value: val, isSet: true}
}

func (v NullableManageRegisterModelPositionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageRegisterModelPositionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
