/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProfileWithoutIdentitiesPhoneNumbersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileWithoutIdentitiesPhoneNumbersInner{}

// ProfileWithoutIdentitiesPhoneNumbersInner struct for ProfileWithoutIdentitiesPhoneNumbersInner
type ProfileWithoutIdentitiesPhoneNumbersInner struct {
	PhoneType   *string `json:"PhoneType,omitempty"`
	PhoneNumber *string `json:"PhoneNumber,omitempty"`
	Op          *string `json:"op,omitempty"`
}

// NewProfileWithoutIdentitiesPhoneNumbersInner instantiates a new ProfileWithoutIdentitiesPhoneNumbersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileWithoutIdentitiesPhoneNumbersInner() *ProfileWithoutIdentitiesPhoneNumbersInner {
	this := ProfileWithoutIdentitiesPhoneNumbersInner{}
	return &this
}

// NewProfileWithoutIdentitiesPhoneNumbersInnerWithDefaults instantiates a new ProfileWithoutIdentitiesPhoneNumbersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileWithoutIdentitiesPhoneNumbersInnerWithDefaults() *ProfileWithoutIdentitiesPhoneNumbersInner {
	this := ProfileWithoutIdentitiesPhoneNumbersInner{}
	return &this
}

// GetPhoneType returns the PhoneType field value if set, zero value otherwise.
func (o *ProfileWithoutIdentitiesPhoneNumbersInner) GetPhoneType() string {
	if o == nil || IsNil(o.PhoneType) {
		var ret string
		return ret
	}
	return *o.PhoneType
}

// GetPhoneTypeOk returns a tuple with the PhoneType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileWithoutIdentitiesPhoneNumbersInner) GetPhoneTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneType) {
		return nil, false
	}
	return o.PhoneType, true
}

// HasPhoneType returns a boolean if a field has been set.
func (o *ProfileWithoutIdentitiesPhoneNumbersInner) HasPhoneType() bool {
	if o != nil && !IsNil(o.PhoneType) {
		return true
	}

	return false
}

// SetPhoneType gets a reference to the given string and assigns it to the PhoneType field.
func (o *ProfileWithoutIdentitiesPhoneNumbersInner) SetPhoneType(v string) {
	o.PhoneType = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *ProfileWithoutIdentitiesPhoneNumbersInner) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileWithoutIdentitiesPhoneNumbersInner) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *ProfileWithoutIdentitiesPhoneNumbersInner) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *ProfileWithoutIdentitiesPhoneNumbersInner) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetOp returns the Op field value if set, zero value otherwise.
func (o *ProfileWithoutIdentitiesPhoneNumbersInner) GetOp() string {
	if o == nil || IsNil(o.Op) {
		var ret string
		return ret
	}
	return *o.Op
}

// GetOpOk returns a tuple with the Op field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileWithoutIdentitiesPhoneNumbersInner) GetOpOk() (*string, bool) {
	if o == nil || IsNil(o.Op) {
		return nil, false
	}
	return o.Op, true
}

// HasOp returns a boolean if a field has been set.
func (o *ProfileWithoutIdentitiesPhoneNumbersInner) HasOp() bool {
	if o != nil && !IsNil(o.Op) {
		return true
	}

	return false
}

// SetOp gets a reference to the given string and assigns it to the Op field.
func (o *ProfileWithoutIdentitiesPhoneNumbersInner) SetOp(v string) {
	o.Op = &v
}

func (o ProfileWithoutIdentitiesPhoneNumbersInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileWithoutIdentitiesPhoneNumbersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PhoneType) {
		toSerialize["PhoneType"] = o.PhoneType
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["PhoneNumber"] = o.PhoneNumber
	}
	if !IsNil(o.Op) {
		toSerialize["op"] = o.Op
	}
	return toSerialize, nil
}

type NullableProfileWithoutIdentitiesPhoneNumbersInner struct {
	value *ProfileWithoutIdentitiesPhoneNumbersInner
	isSet bool
}

func (v NullableProfileWithoutIdentitiesPhoneNumbersInner) Get() *ProfileWithoutIdentitiesPhoneNumbersInner {
	return v.value
}

func (v *NullableProfileWithoutIdentitiesPhoneNumbersInner) Set(val *ProfileWithoutIdentitiesPhoneNumbersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileWithoutIdentitiesPhoneNumbersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileWithoutIdentitiesPhoneNumbersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileWithoutIdentitiesPhoneNumbersInner(val *ProfileWithoutIdentitiesPhoneNumbersInner) *NullableProfileWithoutIdentitiesPhoneNumbersInner {
	return &NullableProfileWithoutIdentitiesPhoneNumbersInner{value: val, isSet: true}
}

func (v NullableProfileWithoutIdentitiesPhoneNumbersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileWithoutIdentitiesPhoneNumbersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
