/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PublicKeyCredentialRequestOptionsExtensions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicKeyCredentialRequestOptionsExtensions{}

// PublicKeyCredentialRequestOptionsExtensions Additional parameters requesting specific processing by the client or authenticator. These are optional and can be used to enable advanced features.
type PublicKeyCredentialRequestOptionsExtensions struct {
	// Used for backwards compatibility with FIDO U2F authenticators. Indicates the AppID for which the credential should be scoped.
	Appid *string `json:"appid,omitempty"`
	// Placeholder for other extension values (can be vendor-specific).
	ExampleExtension *string `json:"exampleExtension,omitempty"`
}

// NewPublicKeyCredentialRequestOptionsExtensions instantiates a new PublicKeyCredentialRequestOptionsExtensions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicKeyCredentialRequestOptionsExtensions() *PublicKeyCredentialRequestOptionsExtensions {
	this := PublicKeyCredentialRequestOptionsExtensions{}
	return &this
}

// NewPublicKeyCredentialRequestOptionsExtensionsWithDefaults instantiates a new PublicKeyCredentialRequestOptionsExtensions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicKeyCredentialRequestOptionsExtensionsWithDefaults() *PublicKeyCredentialRequestOptionsExtensions {
	this := PublicKeyCredentialRequestOptionsExtensions{}
	return &this
}

// GetAppid returns the Appid field value if set, zero value otherwise.
func (o *PublicKeyCredentialRequestOptionsExtensions) GetAppid() string {
	if o == nil || IsNil(o.Appid) {
		var ret string
		return ret
	}
	return *o.Appid
}

// GetAppidOk returns a tuple with the Appid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicKeyCredentialRequestOptionsExtensions) GetAppidOk() (*string, bool) {
	if o == nil || IsNil(o.Appid) {
		return nil, false
	}
	return o.Appid, true
}

// HasAppid returns a boolean if a field has been set.
func (o *PublicKeyCredentialRequestOptionsExtensions) HasAppid() bool {
	if o != nil && !IsNil(o.Appid) {
		return true
	}

	return false
}

// SetAppid gets a reference to the given string and assigns it to the Appid field.
func (o *PublicKeyCredentialRequestOptionsExtensions) SetAppid(v string) {
	o.Appid = &v
}

// GetExampleExtension returns the ExampleExtension field value if set, zero value otherwise.
func (o *PublicKeyCredentialRequestOptionsExtensions) GetExampleExtension() string {
	if o == nil || IsNil(o.ExampleExtension) {
		var ret string
		return ret
	}
	return *o.ExampleExtension
}

// GetExampleExtensionOk returns a tuple with the ExampleExtension field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicKeyCredentialRequestOptionsExtensions) GetExampleExtensionOk() (*string, bool) {
	if o == nil || IsNil(o.ExampleExtension) {
		return nil, false
	}
	return o.ExampleExtension, true
}

// HasExampleExtension returns a boolean if a field has been set.
func (o *PublicKeyCredentialRequestOptionsExtensions) HasExampleExtension() bool {
	if o != nil && !IsNil(o.ExampleExtension) {
		return true
	}

	return false
}

// SetExampleExtension gets a reference to the given string and assigns it to the ExampleExtension field.
func (o *PublicKeyCredentialRequestOptionsExtensions) SetExampleExtension(v string) {
	o.ExampleExtension = &v
}

func (o PublicKeyCredentialRequestOptionsExtensions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicKeyCredentialRequestOptionsExtensions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Appid) {
		toSerialize["appid"] = o.Appid
	}
	if !IsNil(o.ExampleExtension) {
		toSerialize["exampleExtension"] = o.ExampleExtension
	}
	return toSerialize, nil
}

type NullablePublicKeyCredentialRequestOptionsExtensions struct {
	value *PublicKeyCredentialRequestOptionsExtensions
	isSet bool
}

func (v NullablePublicKeyCredentialRequestOptionsExtensions) Get() *PublicKeyCredentialRequestOptionsExtensions {
	return v.value
}

func (v *NullablePublicKeyCredentialRequestOptionsExtensions) Set(val *PublicKeyCredentialRequestOptionsExtensions) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicKeyCredentialRequestOptionsExtensions) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicKeyCredentialRequestOptionsExtensions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicKeyCredentialRequestOptionsExtensions(val *PublicKeyCredentialRequestOptionsExtensions) *NullablePublicKeyCredentialRequestOptionsExtensions {
	return &NullablePublicKeyCredentialRequestOptionsExtensions{value: val, isSet: true}
}

func (v NullablePublicKeyCredentialRequestOptionsExtensions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicKeyCredentialRequestOptionsExtensions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
