/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProfileRequestModelSuggestionsCompaniesToFollowInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileRequestModelSuggestionsCompaniesToFollowInner{}

// ProfileRequestModelSuggestionsCompaniesToFollowInner struct for ProfileRequestModelSuggestionsCompaniesToFollowInner
type ProfileRequestModelSuggestionsCompaniesToFollowInner struct {
	Id   *string `json:"Id,omitempty"`
	Name *string `json:"Name,omitempty"`
}

// NewProfileRequestModelSuggestionsCompaniesToFollowInner instantiates a new ProfileRequestModelSuggestionsCompaniesToFollowInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileRequestModelSuggestionsCompaniesToFollowInner() *ProfileRequestModelSuggestionsCompaniesToFollowInner {
	this := ProfileRequestModelSuggestionsCompaniesToFollowInner{}
	return &this
}

// NewProfileRequestModelSuggestionsCompaniesToFollowInnerWithDefaults instantiates a new ProfileRequestModelSuggestionsCompaniesToFollowInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileRequestModelSuggestionsCompaniesToFollowInnerWithDefaults() *ProfileRequestModelSuggestionsCompaniesToFollowInner {
	this := ProfileRequestModelSuggestionsCompaniesToFollowInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProfileRequestModelSuggestionsCompaniesToFollowInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileRequestModelSuggestionsCompaniesToFollowInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProfileRequestModelSuggestionsCompaniesToFollowInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProfileRequestModelSuggestionsCompaniesToFollowInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProfileRequestModelSuggestionsCompaniesToFollowInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileRequestModelSuggestionsCompaniesToFollowInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProfileRequestModelSuggestionsCompaniesToFollowInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProfileRequestModelSuggestionsCompaniesToFollowInner) SetName(v string) {
	o.Name = &v
}

func (o ProfileRequestModelSuggestionsCompaniesToFollowInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileRequestModelSuggestionsCompaniesToFollowInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	return toSerialize, nil
}

type NullableProfileRequestModelSuggestionsCompaniesToFollowInner struct {
	value *ProfileRequestModelSuggestionsCompaniesToFollowInner
	isSet bool
}

func (v NullableProfileRequestModelSuggestionsCompaniesToFollowInner) Get() *ProfileRequestModelSuggestionsCompaniesToFollowInner {
	return v.value
}

func (v *NullableProfileRequestModelSuggestionsCompaniesToFollowInner) Set(val *ProfileRequestModelSuggestionsCompaniesToFollowInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileRequestModelSuggestionsCompaniesToFollowInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileRequestModelSuggestionsCompaniesToFollowInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileRequestModelSuggestionsCompaniesToFollowInner(val *ProfileRequestModelSuggestionsCompaniesToFollowInner) *NullableProfileRequestModelSuggestionsCompaniesToFollowInner {
	return &NullableProfileRequestModelSuggestionsCompaniesToFollowInner{value: val, isSet: true}
}

func (v NullableProfileRequestModelSuggestionsCompaniesToFollowInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileRequestModelSuggestionsCompaniesToFollowInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
