/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the PrivacyPolicyHistoryResponseHistoryInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivacyPolicyHistoryResponseHistoryInner{}

// PrivacyPolicyHistoryResponseHistoryInner struct for PrivacyPolicyHistoryResponseHistoryInner
type PrivacyPolicyHistoryResponseHistoryInner struct {
	// The version of the Privacy Policy.
	Version NullableString `json:"Version,omitempty"`
	// The source from which the Privacy Policy was accepted.
	AcceptSource NullableString `json:"AcceptSource,omitempty"`
	// The date and time when the Privacy Policy was accepted.
	AcceptDateTime NullableTime `json:"AcceptDateTime,omitempty"`
}

// NewPrivacyPolicyHistoryResponseHistoryInner instantiates a new PrivacyPolicyHistoryResponseHistoryInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivacyPolicyHistoryResponseHistoryInner() *PrivacyPolicyHistoryResponseHistoryInner {
	this := PrivacyPolicyHistoryResponseHistoryInner{}
	return &this
}

// NewPrivacyPolicyHistoryResponseHistoryInnerWithDefaults instantiates a new PrivacyPolicyHistoryResponseHistoryInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivacyPolicyHistoryResponseHistoryInnerWithDefaults() *PrivacyPolicyHistoryResponseHistoryInner {
	this := PrivacyPolicyHistoryResponseHistoryInner{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PrivacyPolicyHistoryResponseHistoryInner) GetVersion() string {
	if o == nil || IsNil(o.Version.Get()) {
		var ret string
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PrivacyPolicyHistoryResponseHistoryInner) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *PrivacyPolicyHistoryResponseHistoryInner) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableString and assigns it to the Version field.
func (o *PrivacyPolicyHistoryResponseHistoryInner) SetVersion(v string) {
	o.Version.Set(&v)
}

// SetVersionNil sets the value for Version to be an explicit nil
func (o *PrivacyPolicyHistoryResponseHistoryInner) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *PrivacyPolicyHistoryResponseHistoryInner) UnsetVersion() {
	o.Version.Unset()
}

// GetAcceptSource returns the AcceptSource field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PrivacyPolicyHistoryResponseHistoryInner) GetAcceptSource() string {
	if o == nil || IsNil(o.AcceptSource.Get()) {
		var ret string
		return ret
	}
	return *o.AcceptSource.Get()
}

// GetAcceptSourceOk returns a tuple with the AcceptSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PrivacyPolicyHistoryResponseHistoryInner) GetAcceptSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AcceptSource.Get(), o.AcceptSource.IsSet()
}

// HasAcceptSource returns a boolean if a field has been set.
func (o *PrivacyPolicyHistoryResponseHistoryInner) HasAcceptSource() bool {
	if o != nil && o.AcceptSource.IsSet() {
		return true
	}

	return false
}

// SetAcceptSource gets a reference to the given NullableString and assigns it to the AcceptSource field.
func (o *PrivacyPolicyHistoryResponseHistoryInner) SetAcceptSource(v string) {
	o.AcceptSource.Set(&v)
}

// SetAcceptSourceNil sets the value for AcceptSource to be an explicit nil
func (o *PrivacyPolicyHistoryResponseHistoryInner) SetAcceptSourceNil() {
	o.AcceptSource.Set(nil)
}

// UnsetAcceptSource ensures that no value is present for AcceptSource, not even an explicit nil
func (o *PrivacyPolicyHistoryResponseHistoryInner) UnsetAcceptSource() {
	o.AcceptSource.Unset()
}

// GetAcceptDateTime returns the AcceptDateTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PrivacyPolicyHistoryResponseHistoryInner) GetAcceptDateTime() time.Time {
	if o == nil || IsNil(o.AcceptDateTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.AcceptDateTime.Get()
}

// GetAcceptDateTimeOk returns a tuple with the AcceptDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PrivacyPolicyHistoryResponseHistoryInner) GetAcceptDateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.AcceptDateTime.Get(), o.AcceptDateTime.IsSet()
}

// HasAcceptDateTime returns a boolean if a field has been set.
func (o *PrivacyPolicyHistoryResponseHistoryInner) HasAcceptDateTime() bool {
	if o != nil && o.AcceptDateTime.IsSet() {
		return true
	}

	return false
}

// SetAcceptDateTime gets a reference to the given NullableTime and assigns it to the AcceptDateTime field.
func (o *PrivacyPolicyHistoryResponseHistoryInner) SetAcceptDateTime(v time.Time) {
	o.AcceptDateTime.Set(&v)
}

// SetAcceptDateTimeNil sets the value for AcceptDateTime to be an explicit nil
func (o *PrivacyPolicyHistoryResponseHistoryInner) SetAcceptDateTimeNil() {
	o.AcceptDateTime.Set(nil)
}

// UnsetAcceptDateTime ensures that no value is present for AcceptDateTime, not even an explicit nil
func (o *PrivacyPolicyHistoryResponseHistoryInner) UnsetAcceptDateTime() {
	o.AcceptDateTime.Unset()
}

func (o PrivacyPolicyHistoryResponseHistoryInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivacyPolicyHistoryResponseHistoryInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Version.IsSet() {
		toSerialize["Version"] = o.Version.Get()
	}
	if o.AcceptSource.IsSet() {
		toSerialize["AcceptSource"] = o.AcceptSource.Get()
	}
	if o.AcceptDateTime.IsSet() {
		toSerialize["AcceptDateTime"] = o.AcceptDateTime.Get()
	}
	return toSerialize, nil
}

type NullablePrivacyPolicyHistoryResponseHistoryInner struct {
	value *PrivacyPolicyHistoryResponseHistoryInner
	isSet bool
}

func (v NullablePrivacyPolicyHistoryResponseHistoryInner) Get() *PrivacyPolicyHistoryResponseHistoryInner {
	return v.value
}

func (v *NullablePrivacyPolicyHistoryResponseHistoryInner) Set(val *PrivacyPolicyHistoryResponseHistoryInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivacyPolicyHistoryResponseHistoryInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivacyPolicyHistoryResponseHistoryInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivacyPolicyHistoryResponseHistoryInner(val *PrivacyPolicyHistoryResponseHistoryInner) *NullablePrivacyPolicyHistoryResponseHistoryInner {
	return &NullablePrivacyPolicyHistoryResponseHistoryInner{value: val, isSet: true}
}

func (v NullablePrivacyPolicyHistoryResponseHistoryInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivacyPolicyHistoryResponseHistoryInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
