/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PhoneIdModelOptional type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PhoneIdModelOptional{}

// PhoneIdModelOptional This model is used while resending the OTP to Phone number.
type PhoneIdModelOptional struct {
	// The Phone number of the User.
	Phone *string `json:"phone,omitempty"`
}

// NewPhoneIdModelOptional instantiates a new PhoneIdModelOptional object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPhoneIdModelOptional() *PhoneIdModelOptional {
	this := PhoneIdModelOptional{}
	return &this
}

// NewPhoneIdModelOptionalWithDefaults instantiates a new PhoneIdModelOptional object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPhoneIdModelOptionalWithDefaults() *PhoneIdModelOptional {
	this := PhoneIdModelOptional{}
	return &this
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *PhoneIdModelOptional) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PhoneIdModelOptional) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *PhoneIdModelOptional) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *PhoneIdModelOptional) SetPhone(v string) {
	o.Phone = &v
}

func (o PhoneIdModelOptional) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PhoneIdModelOptional) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	return toSerialize, nil
}

type NullablePhoneIdModelOptional struct {
	value *PhoneIdModelOptional
	isSet bool
}

func (v NullablePhoneIdModelOptional) Get() *PhoneIdModelOptional {
	return v.value
}

func (v *NullablePhoneIdModelOptional) Set(val *PhoneIdModelOptional) {
	v.value = val
	v.isSet = true
}

func (v NullablePhoneIdModelOptional) IsSet() bool {
	return v.isSet
}

func (v *NullablePhoneIdModelOptional) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePhoneIdModelOptional(val *PhoneIdModelOptional) *NullablePhoneIdModelOptional {
	return &NullablePhoneIdModelOptional{value: val, isSet: true}
}

func (v NullablePhoneIdModelOptional) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePhoneIdModelOptional) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
