/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PublicKeyCredentialCreationOptionsUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicKeyCredentialCreationOptionsUser{}

// PublicKeyCredentialCreationOptionsUser Information about the User for whom the credential is being created. This information will be stored in the authenticator.
type PublicKeyCredentialCreationOptionsUser struct {
	// A unique identifier for the User. This should be opaque but stable across different sessions for the same User.
	Id string `json:"id"`
	// The User's Username or Email address, which may be displayed to the User by the authenticator.
	Name string `json:"name"`
	// The User's display name, which may be shown to the User by the authenticator during credential creation.
	DisplayName string `json:"displayName"`
	// Optional. A URL pointing to an image resource for the User, which may be displayed to the User by the authenticator.
	Icon *string `json:"icon,omitempty"`
}

type _PublicKeyCredentialCreationOptionsUser PublicKeyCredentialCreationOptionsUser

// NewPublicKeyCredentialCreationOptionsUser instantiates a new PublicKeyCredentialCreationOptionsUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicKeyCredentialCreationOptionsUser(id string, name string, displayName string) *PublicKeyCredentialCreationOptionsUser {
	this := PublicKeyCredentialCreationOptionsUser{}
	this.Id = id
	this.Name = name
	this.DisplayName = displayName
	return &this
}

// NewPublicKeyCredentialCreationOptionsUserWithDefaults instantiates a new PublicKeyCredentialCreationOptionsUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicKeyCredentialCreationOptionsUserWithDefaults() *PublicKeyCredentialCreationOptionsUser {
	this := PublicKeyCredentialCreationOptionsUser{}
	return &this
}

// GetId returns the Id field value
func (o *PublicKeyCredentialCreationOptionsUser) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PublicKeyCredentialCreationOptionsUser) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PublicKeyCredentialCreationOptionsUser) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *PublicKeyCredentialCreationOptionsUser) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PublicKeyCredentialCreationOptionsUser) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PublicKeyCredentialCreationOptionsUser) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *PublicKeyCredentialCreationOptionsUser) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *PublicKeyCredentialCreationOptionsUser) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *PublicKeyCredentialCreationOptionsUser) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *PublicKeyCredentialCreationOptionsUser) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicKeyCredentialCreationOptionsUser) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *PublicKeyCredentialCreationOptionsUser) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *PublicKeyCredentialCreationOptionsUser) SetIcon(v string) {
	o.Icon = &v
}

func (o PublicKeyCredentialCreationOptionsUser) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicKeyCredentialCreationOptionsUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	return toSerialize, nil
}

func (o *PublicKeyCredentialCreationOptionsUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"displayName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicKeyCredentialCreationOptionsUser := _PublicKeyCredentialCreationOptionsUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublicKeyCredentialCreationOptionsUser)

	if err != nil {
		return err
	}

	*o = PublicKeyCredentialCreationOptionsUser(varPublicKeyCredentialCreationOptionsUser)

	return err
}

type NullablePublicKeyCredentialCreationOptionsUser struct {
	value *PublicKeyCredentialCreationOptionsUser
	isSet bool
}

func (v NullablePublicKeyCredentialCreationOptionsUser) Get() *PublicKeyCredentialCreationOptionsUser {
	return v.value
}

func (v *NullablePublicKeyCredentialCreationOptionsUser) Set(val *PublicKeyCredentialCreationOptionsUser) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicKeyCredentialCreationOptionsUser) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicKeyCredentialCreationOptionsUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicKeyCredentialCreationOptionsUser(val *PublicKeyCredentialCreationOptionsUser) *NullablePublicKeyCredentialCreationOptionsUser {
	return &NullablePublicKeyCredentialCreationOptionsUser{value: val, isSet: true}
}

func (v NullablePublicKeyCredentialCreationOptionsUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicKeyCredentialCreationOptionsUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
