/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the WorkflowData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowData{}

// WorkflowData struct for WorkflowData
type WorkflowData struct {
	Tree       *WorkflowDataTree                       `json:"tree,omitempty"`
	Nodes      *map[string]WorkflowDataNodesValue      `json:"nodes,omitempty"`
	InnerNodes *map[string]WorkflowDataInnerNodesValue `json:"innerNodes,omitempty"`
	Policies   *map[string][]map[string]interface{}    `json:"policies,omitempty"`
	// The version ID of the workflow.
	VersionId *string `json:"versionId,omitempty"`
	// The creation date of the workflow version.
	CreatedDate *time.Time `json:"createdDate,omitempty"`
	// Description of the workflow version.
	Description *string `json:"description,omitempty"`
}

// NewWorkflowData instantiates a new WorkflowData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowData() *WorkflowData {
	this := WorkflowData{}
	return &this
}

// NewWorkflowDataWithDefaults instantiates a new WorkflowData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowDataWithDefaults() *WorkflowData {
	this := WorkflowData{}
	return &this
}

// GetTree returns the Tree field value if set, zero value otherwise.
func (o *WorkflowData) GetTree() WorkflowDataTree {
	if o == nil || IsNil(o.Tree) {
		var ret WorkflowDataTree
		return ret
	}
	return *o.Tree
}

// GetTreeOk returns a tuple with the Tree field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowData) GetTreeOk() (*WorkflowDataTree, bool) {
	if o == nil || IsNil(o.Tree) {
		return nil, false
	}
	return o.Tree, true
}

// HasTree returns a boolean if a field has been set.
func (o *WorkflowData) HasTree() bool {
	if o != nil && !IsNil(o.Tree) {
		return true
	}

	return false
}

// SetTree gets a reference to the given WorkflowDataTree and assigns it to the Tree field.
func (o *WorkflowData) SetTree(v WorkflowDataTree) {
	o.Tree = &v
}

// GetNodes returns the Nodes field value if set, zero value otherwise.
func (o *WorkflowData) GetNodes() map[string]WorkflowDataNodesValue {
	if o == nil || IsNil(o.Nodes) {
		var ret map[string]WorkflowDataNodesValue
		return ret
	}
	return *o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowData) GetNodesOk() (*map[string]WorkflowDataNodesValue, bool) {
	if o == nil || IsNil(o.Nodes) {
		return nil, false
	}
	return o.Nodes, true
}

// HasNodes returns a boolean if a field has been set.
func (o *WorkflowData) HasNodes() bool {
	if o != nil && !IsNil(o.Nodes) {
		return true
	}

	return false
}

// SetNodes gets a reference to the given map[string]WorkflowDataNodesValue and assigns it to the Nodes field.
func (o *WorkflowData) SetNodes(v map[string]WorkflowDataNodesValue) {
	o.Nodes = &v
}

// GetInnerNodes returns the InnerNodes field value if set, zero value otherwise.
func (o *WorkflowData) GetInnerNodes() map[string]WorkflowDataInnerNodesValue {
	if o == nil || IsNil(o.InnerNodes) {
		var ret map[string]WorkflowDataInnerNodesValue
		return ret
	}
	return *o.InnerNodes
}

// GetInnerNodesOk returns a tuple with the InnerNodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowData) GetInnerNodesOk() (*map[string]WorkflowDataInnerNodesValue, bool) {
	if o == nil || IsNil(o.InnerNodes) {
		return nil, false
	}
	return o.InnerNodes, true
}

// HasInnerNodes returns a boolean if a field has been set.
func (o *WorkflowData) HasInnerNodes() bool {
	if o != nil && !IsNil(o.InnerNodes) {
		return true
	}

	return false
}

// SetInnerNodes gets a reference to the given map[string]WorkflowDataInnerNodesValue and assigns it to the InnerNodes field.
func (o *WorkflowData) SetInnerNodes(v map[string]WorkflowDataInnerNodesValue) {
	o.InnerNodes = &v
}

// GetPolicies returns the Policies field value if set, zero value otherwise.
func (o *WorkflowData) GetPolicies() map[string][]map[string]interface{} {
	if o == nil || IsNil(o.Policies) {
		var ret map[string][]map[string]interface{}
		return ret
	}
	return *o.Policies
}

// GetPoliciesOk returns a tuple with the Policies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowData) GetPoliciesOk() (*map[string][]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Policies) {
		return nil, false
	}
	return o.Policies, true
}

// HasPolicies returns a boolean if a field has been set.
func (o *WorkflowData) HasPolicies() bool {
	if o != nil && !IsNil(o.Policies) {
		return true
	}

	return false
}

// SetPolicies gets a reference to the given map[string][]map[string]interface{} and assigns it to the Policies field.
func (o *WorkflowData) SetPolicies(v map[string][]map[string]interface{}) {
	o.Policies = &v
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *WorkflowData) GetVersionId() string {
	if o == nil || IsNil(o.VersionId) {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowData) GetVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *WorkflowData) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *WorkflowData) SetVersionId(v string) {
	o.VersionId = &v
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise.
func (o *WorkflowData) GetCreatedDate() time.Time {
	if o == nil || IsNil(o.CreatedDate) {
		var ret time.Time
		return ret
	}
	return *o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowData) GetCreatedDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedDate) {
		return nil, false
	}
	return o.CreatedDate, true
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *WorkflowData) HasCreatedDate() bool {
	if o != nil && !IsNil(o.CreatedDate) {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given time.Time and assigns it to the CreatedDate field.
func (o *WorkflowData) SetCreatedDate(v time.Time) {
	o.CreatedDate = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *WorkflowData) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowData) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *WorkflowData) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *WorkflowData) SetDescription(v string) {
	o.Description = &v
}

func (o WorkflowData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tree) {
		toSerialize["tree"] = o.Tree
	}
	if !IsNil(o.Nodes) {
		toSerialize["nodes"] = o.Nodes
	}
	if !IsNil(o.InnerNodes) {
		toSerialize["innerNodes"] = o.InnerNodes
	}
	if !IsNil(o.Policies) {
		toSerialize["policies"] = o.Policies
	}
	if !IsNil(o.VersionId) {
		toSerialize["versionId"] = o.VersionId
	}
	if !IsNil(o.CreatedDate) {
		toSerialize["createdDate"] = o.CreatedDate
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableWorkflowData struct {
	value *WorkflowData
	isSet bool
}

func (v NullableWorkflowData) Get() *WorkflowData {
	return v.value
}

func (v *NullableWorkflowData) Set(val *WorkflowData) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowData) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowData(val *WorkflowData) *NullableWorkflowData {
	return &NullableWorkflowData{value: val, isSet: true}
}

func (v NullableWorkflowData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
