/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConsentVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsentVersion{}

// ConsentVersion struct for ConsentVersion
type ConsentVersion struct {
	IsCustom *bool   `json:"IsCustom,omitempty"`
	Version  *int32  `json:"Version,omitempty"`
	Event    *string `json:"Event,omitempty"`
}

// NewConsentVersion instantiates a new ConsentVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsentVersion() *ConsentVersion {
	this := ConsentVersion{}
	return &this
}

// NewConsentVersionWithDefaults instantiates a new ConsentVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsentVersionWithDefaults() *ConsentVersion {
	this := ConsentVersion{}
	return &this
}

// GetIsCustom returns the IsCustom field value if set, zero value otherwise.
func (o *ConsentVersion) GetIsCustom() bool {
	if o == nil || IsNil(o.IsCustom) {
		var ret bool
		return ret
	}
	return *o.IsCustom
}

// GetIsCustomOk returns a tuple with the IsCustom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsentVersion) GetIsCustomOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCustom) {
		return nil, false
	}
	return o.IsCustom, true
}

// HasIsCustom returns a boolean if a field has been set.
func (o *ConsentVersion) HasIsCustom() bool {
	if o != nil && !IsNil(o.IsCustom) {
		return true
	}

	return false
}

// SetIsCustom gets a reference to the given bool and assigns it to the IsCustom field.
func (o *ConsentVersion) SetIsCustom(v bool) {
	o.IsCustom = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ConsentVersion) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsentVersion) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ConsentVersion) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *ConsentVersion) SetVersion(v int32) {
	o.Version = &v
}

// GetEvent returns the Event field value if set, zero value otherwise.
func (o *ConsentVersion) GetEvent() string {
	if o == nil || IsNil(o.Event) {
		var ret string
		return ret
	}
	return *o.Event
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsentVersion) GetEventOk() (*string, bool) {
	if o == nil || IsNil(o.Event) {
		return nil, false
	}
	return o.Event, true
}

// HasEvent returns a boolean if a field has been set.
func (o *ConsentVersion) HasEvent() bool {
	if o != nil && !IsNil(o.Event) {
		return true
	}

	return false
}

// SetEvent gets a reference to the given string and assigns it to the Event field.
func (o *ConsentVersion) SetEvent(v string) {
	o.Event = &v
}

func (o ConsentVersion) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsentVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsCustom) {
		toSerialize["IsCustom"] = o.IsCustom
	}
	if !IsNil(o.Version) {
		toSerialize["Version"] = o.Version
	}
	if !IsNil(o.Event) {
		toSerialize["Event"] = o.Event
	}
	return toSerialize, nil
}

type NullableConsentVersion struct {
	value *ConsentVersion
	isSet bool
}

func (v NullableConsentVersion) Get() *ConsentVersion {
	return v.value
}

func (v *NullableConsentVersion) Set(val *ConsentVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableConsentVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableConsentVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsentVersion(val *ConsentVersion) *NullableConsentVersion {
	return &NullableConsentVersion{value: val, isSet: true}
}

func (v NullableConsentVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsentVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
