/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the AuthResponseRequiredMfaCore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthResponseRequiredMfaCore{}

// AuthResponseRequiredMfaCore struct for AuthResponseRequiredMfaCore
type AuthResponseRequiredMfaCore struct {
	// Empty access_token
	AccessToken *string `json:"access_token,omitempty"`
	// Empty expires_in
	ExpiresIn *time.Time `json:"expires_in,omitempty"`
}

// NewAuthResponseRequiredMfaCore instantiates a new AuthResponseRequiredMfaCore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthResponseRequiredMfaCore() *AuthResponseRequiredMfaCore {
	this := AuthResponseRequiredMfaCore{}
	return &this
}

// NewAuthResponseRequiredMfaCoreWithDefaults instantiates a new AuthResponseRequiredMfaCore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthResponseRequiredMfaCoreWithDefaults() *AuthResponseRequiredMfaCore {
	this := AuthResponseRequiredMfaCore{}
	return &this
}

// GetAccessToken returns the AccessToken field value if set, zero value otherwise.
func (o *AuthResponseRequiredMfaCore) GetAccessToken() string {
	if o == nil || IsNil(o.AccessToken) {
		var ret string
		return ret
	}
	return *o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthResponseRequiredMfaCore) GetAccessTokenOk() (*string, bool) {
	if o == nil || IsNil(o.AccessToken) {
		return nil, false
	}
	return o.AccessToken, true
}

// HasAccessToken returns a boolean if a field has been set.
func (o *AuthResponseRequiredMfaCore) HasAccessToken() bool {
	if o != nil && !IsNil(o.AccessToken) {
		return true
	}

	return false
}

// SetAccessToken gets a reference to the given string and assigns it to the AccessToken field.
func (o *AuthResponseRequiredMfaCore) SetAccessToken(v string) {
	o.AccessToken = &v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *AuthResponseRequiredMfaCore) GetExpiresIn() time.Time {
	if o == nil || IsNil(o.ExpiresIn) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthResponseRequiredMfaCore) GetExpiresInOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *AuthResponseRequiredMfaCore) HasExpiresIn() bool {
	if o != nil && !IsNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given time.Time and assigns it to the ExpiresIn field.
func (o *AuthResponseRequiredMfaCore) SetExpiresIn(v time.Time) {
	o.ExpiresIn = &v
}

func (o AuthResponseRequiredMfaCore) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthResponseRequiredMfaCore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessToken) {
		toSerialize["access_token"] = o.AccessToken
	}
	if !IsNil(o.ExpiresIn) {
		toSerialize["expires_in"] = o.ExpiresIn
	}
	return toSerialize, nil
}

type NullableAuthResponseRequiredMfaCore struct {
	value *AuthResponseRequiredMfaCore
	isSet bool
}

func (v NullableAuthResponseRequiredMfaCore) Get() *AuthResponseRequiredMfaCore {
	return v.value
}

func (v *NullableAuthResponseRequiredMfaCore) Set(val *AuthResponseRequiredMfaCore) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthResponseRequiredMfaCore) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthResponseRequiredMfaCore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthResponseRequiredMfaCore(val *AuthResponseRequiredMfaCore) *NullableAuthResponseRequiredMfaCore {
	return &NullableAuthResponseRequiredMfaCore{value: val, isSet: true}
}

func (v NullableAuthResponseRequiredMfaCore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthResponseRequiredMfaCore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
