/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CustomFieldLimitResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomFieldLimitResponse{}

// CustomFieldLimitResponse struct for CustomFieldLimitResponse
type CustomFieldLimitResponse struct {
	// The limit for custom fields.
	CustomFieldLimit *int32 `json:"CustomFieldLimit,omitempty"`
}

// NewCustomFieldLimitResponse instantiates a new CustomFieldLimitResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomFieldLimitResponse() *CustomFieldLimitResponse {
	this := CustomFieldLimitResponse{}
	return &this
}

// NewCustomFieldLimitResponseWithDefaults instantiates a new CustomFieldLimitResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomFieldLimitResponseWithDefaults() *CustomFieldLimitResponse {
	this := CustomFieldLimitResponse{}
	return &this
}

// GetCustomFieldLimit returns the CustomFieldLimit field value if set, zero value otherwise.
func (o *CustomFieldLimitResponse) GetCustomFieldLimit() int32 {
	if o == nil || IsNil(o.CustomFieldLimit) {
		var ret int32
		return ret
	}
	return *o.CustomFieldLimit
}

// GetCustomFieldLimitOk returns a tuple with the CustomFieldLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomFieldLimitResponse) GetCustomFieldLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.CustomFieldLimit) {
		return nil, false
	}
	return o.CustomFieldLimit, true
}

// HasCustomFieldLimit returns a boolean if a field has been set.
func (o *CustomFieldLimitResponse) HasCustomFieldLimit() bool {
	if o != nil && !IsNil(o.CustomFieldLimit) {
		return true
	}

	return false
}

// SetCustomFieldLimit gets a reference to the given int32 and assigns it to the CustomFieldLimit field.
func (o *CustomFieldLimitResponse) SetCustomFieldLimit(v int32) {
	o.CustomFieldLimit = &v
}

func (o CustomFieldLimitResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomFieldLimitResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomFieldLimit) {
		toSerialize["CustomFieldLimit"] = o.CustomFieldLimit
	}
	return toSerialize, nil
}

type NullableCustomFieldLimitResponse struct {
	value *CustomFieldLimitResponse
	isSet bool
}

func (v NullableCustomFieldLimitResponse) Get() *CustomFieldLimitResponse {
	return v.value
}

func (v *NullableCustomFieldLimitResponse) Set(val *CustomFieldLimitResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomFieldLimitResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomFieldLimitResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomFieldLimitResponse(val *CustomFieldLimitResponse) *NullableCustomFieldLimitResponse {
	return &NullableCustomFieldLimitResponse{value: val, isSet: true}
}

func (v NullableCustomFieldLimitResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomFieldLimitResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
