/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the VerificationLinkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerificationLinkResponse{}

// VerificationLinkResponse struct for VerificationLinkResponse
type VerificationLinkResponse struct {
	// The generated Verification Token.
	VerificationToken *string `json:"VerificationToken,omitempty"`
	// The expiration time of the token.
	ExpiresIn *time.Time `json:"expires_in,omitempty"`
}

// NewVerificationLinkResponse instantiates a new VerificationLinkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerificationLinkResponse() *VerificationLinkResponse {
	this := VerificationLinkResponse{}
	return &this
}

// NewVerificationLinkResponseWithDefaults instantiates a new VerificationLinkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerificationLinkResponseWithDefaults() *VerificationLinkResponse {
	this := VerificationLinkResponse{}
	return &this
}

// GetVerificationToken returns the VerificationToken field value if set, zero value otherwise.
func (o *VerificationLinkResponse) GetVerificationToken() string {
	if o == nil || IsNil(o.VerificationToken) {
		var ret string
		return ret
	}
	return *o.VerificationToken
}

// GetVerificationTokenOk returns a tuple with the VerificationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerificationLinkResponse) GetVerificationTokenOk() (*string, bool) {
	if o == nil || IsNil(o.VerificationToken) {
		return nil, false
	}
	return o.VerificationToken, true
}

// HasVerificationToken returns a boolean if a field has been set.
func (o *VerificationLinkResponse) HasVerificationToken() bool {
	if o != nil && !IsNil(o.VerificationToken) {
		return true
	}

	return false
}

// SetVerificationToken gets a reference to the given string and assigns it to the VerificationToken field.
func (o *VerificationLinkResponse) SetVerificationToken(v string) {
	o.VerificationToken = &v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *VerificationLinkResponse) GetExpiresIn() time.Time {
	if o == nil || IsNil(o.ExpiresIn) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerificationLinkResponse) GetExpiresInOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *VerificationLinkResponse) HasExpiresIn() bool {
	if o != nil && !IsNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given time.Time and assigns it to the ExpiresIn field.
func (o *VerificationLinkResponse) SetExpiresIn(v time.Time) {
	o.ExpiresIn = &v
}

func (o VerificationLinkResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerificationLinkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VerificationToken) {
		toSerialize["VerificationToken"] = o.VerificationToken
	}
	if !IsNil(o.ExpiresIn) {
		toSerialize["expires_in"] = o.ExpiresIn
	}
	return toSerialize, nil
}

type NullableVerificationLinkResponse struct {
	value *VerificationLinkResponse
	isSet bool
}

func (v NullableVerificationLinkResponse) Get() *VerificationLinkResponse {
	return v.value
}

func (v *NullableVerificationLinkResponse) Set(val *VerificationLinkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerificationLinkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerificationLinkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerificationLinkResponse(val *VerificationLinkResponse) *NullableVerificationLinkResponse {
	return &NullableVerificationLinkResponse{value: val, isSet: true}
}

func (v NullableVerificationLinkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerificationLinkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
