/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the JwtIntegrationCreateCore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JwtIntegrationCreateCore{}

// JwtIntegrationCreateCore struct for JwtIntegrationCreateCore
type JwtIntegrationCreateCore struct {
	AppName string `json:"AppName"`
}

type _JwtIntegrationCreateCore JwtIntegrationCreateCore

// NewJwtIntegrationCreateCore instantiates a new JwtIntegrationCreateCore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJwtIntegrationCreateCore(appName string) *JwtIntegrationCreateCore {
	this := JwtIntegrationCreateCore{}
	this.AppName = appName
	return &this
}

// NewJwtIntegrationCreateCoreWithDefaults instantiates a new JwtIntegrationCreateCore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJwtIntegrationCreateCoreWithDefaults() *JwtIntegrationCreateCore {
	this := JwtIntegrationCreateCore{}
	return &this
}

// GetAppName returns the AppName field value
func (o *JwtIntegrationCreateCore) GetAppName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppName
}

// GetAppNameOk returns a tuple with the AppName field value
// and a boolean to check if the value has been set.
func (o *JwtIntegrationCreateCore) GetAppNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppName, true
}

// SetAppName sets field value
func (o *JwtIntegrationCreateCore) SetAppName(v string) {
	o.AppName = v
}

func (o JwtIntegrationCreateCore) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JwtIntegrationCreateCore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["AppName"] = o.AppName
	return toSerialize, nil
}

func (o *JwtIntegrationCreateCore) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"AppName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJwtIntegrationCreateCore := _JwtIntegrationCreateCore{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJwtIntegrationCreateCore)

	if err != nil {
		return err
	}

	*o = JwtIntegrationCreateCore(varJwtIntegrationCreateCore)

	return err
}

type NullableJwtIntegrationCreateCore struct {
	value *JwtIntegrationCreateCore
	isSet bool
}

func (v NullableJwtIntegrationCreateCore) Get() *JwtIntegrationCreateCore {
	return v.value
}

func (v *NullableJwtIntegrationCreateCore) Set(val *JwtIntegrationCreateCore) {
	v.value = val
	v.isSet = true
}

func (v NullableJwtIntegrationCreateCore) IsSet() bool {
	return v.isSet
}

func (v *NullableJwtIntegrationCreateCore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJwtIntegrationCreateCore(val *JwtIntegrationCreateCore) *NullableJwtIntegrationCreateCore {
	return &NullableJwtIntegrationCreateCore{value: val, isSet: true}
}

func (v NullableJwtIntegrationCreateCore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJwtIntegrationCreateCore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
