/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ManageRegisterModelCertificationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManageRegisterModelCertificationsInner{}

// ManageRegisterModelCertificationsInner struct for ManageRegisterModelCertificationsInner
type ManageRegisterModelCertificationsInner struct {
	// The ID of the certification.
	Id *string `json:"Id,omitempty"`
	// The name of the certification.
	Name *string `json:"Name,omitempty"`
	// The authority that issued the certification.
	Authority *string `json:"Authority,omitempty"`
	// The start date of the certification.
	StartDate *time.Time `json:"StartDate,omitempty"`
	// The end date of the certification.
	EndDate *time.Time `json:"EndDate,omitempty"`
}

// NewManageRegisterModelCertificationsInner instantiates a new ManageRegisterModelCertificationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageRegisterModelCertificationsInner() *ManageRegisterModelCertificationsInner {
	this := ManageRegisterModelCertificationsInner{}
	return &this
}

// NewManageRegisterModelCertificationsInnerWithDefaults instantiates a new ManageRegisterModelCertificationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageRegisterModelCertificationsInnerWithDefaults() *ManageRegisterModelCertificationsInner {
	this := ManageRegisterModelCertificationsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ManageRegisterModelCertificationsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelCertificationsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ManageRegisterModelCertificationsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ManageRegisterModelCertificationsInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ManageRegisterModelCertificationsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelCertificationsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ManageRegisterModelCertificationsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ManageRegisterModelCertificationsInner) SetName(v string) {
	o.Name = &v
}

// GetAuthority returns the Authority field value if set, zero value otherwise.
func (o *ManageRegisterModelCertificationsInner) GetAuthority() string {
	if o == nil || IsNil(o.Authority) {
		var ret string
		return ret
	}
	return *o.Authority
}

// GetAuthorityOk returns a tuple with the Authority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelCertificationsInner) GetAuthorityOk() (*string, bool) {
	if o == nil || IsNil(o.Authority) {
		return nil, false
	}
	return o.Authority, true
}

// HasAuthority returns a boolean if a field has been set.
func (o *ManageRegisterModelCertificationsInner) HasAuthority() bool {
	if o != nil && !IsNil(o.Authority) {
		return true
	}

	return false
}

// SetAuthority gets a reference to the given string and assigns it to the Authority field.
func (o *ManageRegisterModelCertificationsInner) SetAuthority(v string) {
	o.Authority = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *ManageRegisterModelCertificationsInner) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelCertificationsInner) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *ManageRegisterModelCertificationsInner) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *ManageRegisterModelCertificationsInner) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *ManageRegisterModelCertificationsInner) GetEndDate() time.Time {
	if o == nil || IsNil(o.EndDate) {
		var ret time.Time
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelCertificationsInner) GetEndDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *ManageRegisterModelCertificationsInner) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given time.Time and assigns it to the EndDate field.
func (o *ManageRegisterModelCertificationsInner) SetEndDate(v time.Time) {
	o.EndDate = &v
}

func (o ManageRegisterModelCertificationsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManageRegisterModelCertificationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Authority) {
		toSerialize["Authority"] = o.Authority
	}
	if !IsNil(o.StartDate) {
		toSerialize["StartDate"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["EndDate"] = o.EndDate
	}
	return toSerialize, nil
}

type NullableManageRegisterModelCertificationsInner struct {
	value *ManageRegisterModelCertificationsInner
	isSet bool
}

func (v NullableManageRegisterModelCertificationsInner) Get() *ManageRegisterModelCertificationsInner {
	return v.value
}

func (v *NullableManageRegisterModelCertificationsInner) Set(val *ManageRegisterModelCertificationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableManageRegisterModelCertificationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableManageRegisterModelCertificationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageRegisterModelCertificationsInner(val *ManageRegisterModelCertificationsInner) *NullableManageRegisterModelCertificationsInner {
	return &NullableManageRegisterModelCertificationsInner{value: val, isSet: true}
}

func (v NullableManageRegisterModelCertificationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageRegisterModelCertificationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
