/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SamlIdpMetadataResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SamlIdpMetadataResponse{}

// SamlIdpMetadataResponse Saml IdP Metadata Response
type SamlIdpMetadataResponse struct {
	DSNS             *string                                  `json:"DSNS,omitempty"`
	EntityId         *string                                  `json:"EntityId,omitempty"`
	IDPSSODescriptor *SamlIdpMetadataResponseIDPSSODescriptor `json:"IDPSSODescriptor,omitempty"`
	XMLNS            *string                                  `json:"XMLNS,omitempty"`
}

// NewSamlIdpMetadataResponse instantiates a new SamlIdpMetadataResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSamlIdpMetadataResponse() *SamlIdpMetadataResponse {
	this := SamlIdpMetadataResponse{}
	return &this
}

// NewSamlIdpMetadataResponseWithDefaults instantiates a new SamlIdpMetadataResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSamlIdpMetadataResponseWithDefaults() *SamlIdpMetadataResponse {
	this := SamlIdpMetadataResponse{}
	return &this
}

// GetDSNS returns the DSNS field value if set, zero value otherwise.
func (o *SamlIdpMetadataResponse) GetDSNS() string {
	if o == nil || IsNil(o.DSNS) {
		var ret string
		return ret
	}
	return *o.DSNS
}

// GetDSNSOk returns a tuple with the DSNS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SamlIdpMetadataResponse) GetDSNSOk() (*string, bool) {
	if o == nil || IsNil(o.DSNS) {
		return nil, false
	}
	return o.DSNS, true
}

// HasDSNS returns a boolean if a field has been set.
func (o *SamlIdpMetadataResponse) HasDSNS() bool {
	if o != nil && !IsNil(o.DSNS) {
		return true
	}

	return false
}

// SetDSNS gets a reference to the given string and assigns it to the DSNS field.
func (o *SamlIdpMetadataResponse) SetDSNS(v string) {
	o.DSNS = &v
}

// GetEntityId returns the EntityId field value if set, zero value otherwise.
func (o *SamlIdpMetadataResponse) GetEntityId() string {
	if o == nil || IsNil(o.EntityId) {
		var ret string
		return ret
	}
	return *o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SamlIdpMetadataResponse) GetEntityIdOk() (*string, bool) {
	if o == nil || IsNil(o.EntityId) {
		return nil, false
	}
	return o.EntityId, true
}

// HasEntityId returns a boolean if a field has been set.
func (o *SamlIdpMetadataResponse) HasEntityId() bool {
	if o != nil && !IsNil(o.EntityId) {
		return true
	}

	return false
}

// SetEntityId gets a reference to the given string and assigns it to the EntityId field.
func (o *SamlIdpMetadataResponse) SetEntityId(v string) {
	o.EntityId = &v
}

// GetIDPSSODescriptor returns the IDPSSODescriptor field value if set, zero value otherwise.
func (o *SamlIdpMetadataResponse) GetIDPSSODescriptor() SamlIdpMetadataResponseIDPSSODescriptor {
	if o == nil || IsNil(o.IDPSSODescriptor) {
		var ret SamlIdpMetadataResponseIDPSSODescriptor
		return ret
	}
	return *o.IDPSSODescriptor
}

// GetIDPSSODescriptorOk returns a tuple with the IDPSSODescriptor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SamlIdpMetadataResponse) GetIDPSSODescriptorOk() (*SamlIdpMetadataResponseIDPSSODescriptor, bool) {
	if o == nil || IsNil(o.IDPSSODescriptor) {
		return nil, false
	}
	return o.IDPSSODescriptor, true
}

// HasIDPSSODescriptor returns a boolean if a field has been set.
func (o *SamlIdpMetadataResponse) HasIDPSSODescriptor() bool {
	if o != nil && !IsNil(o.IDPSSODescriptor) {
		return true
	}

	return false
}

// SetIDPSSODescriptor gets a reference to the given SamlIdpMetadataResponseIDPSSODescriptor and assigns it to the IDPSSODescriptor field.
func (o *SamlIdpMetadataResponse) SetIDPSSODescriptor(v SamlIdpMetadataResponseIDPSSODescriptor) {
	o.IDPSSODescriptor = &v
}

// GetXMLNS returns the XMLNS field value if set, zero value otherwise.
func (o *SamlIdpMetadataResponse) GetXMLNS() string {
	if o == nil || IsNil(o.XMLNS) {
		var ret string
		return ret
	}
	return *o.XMLNS
}

// GetXMLNSOk returns a tuple with the XMLNS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SamlIdpMetadataResponse) GetXMLNSOk() (*string, bool) {
	if o == nil || IsNil(o.XMLNS) {
		return nil, false
	}
	return o.XMLNS, true
}

// HasXMLNS returns a boolean if a field has been set.
func (o *SamlIdpMetadataResponse) HasXMLNS() bool {
	if o != nil && !IsNil(o.XMLNS) {
		return true
	}

	return false
}

// SetXMLNS gets a reference to the given string and assigns it to the XMLNS field.
func (o *SamlIdpMetadataResponse) SetXMLNS(v string) {
	o.XMLNS = &v
}

func (o SamlIdpMetadataResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SamlIdpMetadataResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DSNS) {
		toSerialize["DSNS"] = o.DSNS
	}
	if !IsNil(o.EntityId) {
		toSerialize["EntityId"] = o.EntityId
	}
	if !IsNil(o.IDPSSODescriptor) {
		toSerialize["IDPSSODescriptor"] = o.IDPSSODescriptor
	}
	if !IsNil(o.XMLNS) {
		toSerialize["XMLNS"] = o.XMLNS
	}
	return toSerialize, nil
}

type NullableSamlIdpMetadataResponse struct {
	value *SamlIdpMetadataResponse
	isSet bool
}

func (v NullableSamlIdpMetadataResponse) Get() *SamlIdpMetadataResponse {
	return v.value
}

func (v *NullableSamlIdpMetadataResponse) Set(val *SamlIdpMetadataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSamlIdpMetadataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSamlIdpMetadataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSamlIdpMetadataResponse(val *SamlIdpMetadataResponse) *NullableSamlIdpMetadataResponse {
	return &NullableSamlIdpMetadataResponse{value: val, isSet: true}
}

func (v NullableSamlIdpMetadataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSamlIdpMetadataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
