/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the JwtValidation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JwtValidation{}

// JwtValidation struct for JwtValidation
type JwtValidation struct {
	IsMandatory *bool `json:"IsMandatory,omitempty"`
}

// NewJwtValidation instantiates a new JwtValidation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJwtValidation() *JwtValidation {
	this := JwtValidation{}
	return &this
}

// NewJwtValidationWithDefaults instantiates a new JwtValidation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJwtValidationWithDefaults() *JwtValidation {
	this := JwtValidation{}
	return &this
}

// GetIsMandatory returns the IsMandatory field value if set, zero value otherwise.
func (o *JwtValidation) GetIsMandatory() bool {
	if o == nil || IsNil(o.IsMandatory) {
		var ret bool
		return ret
	}
	return *o.IsMandatory
}

// GetIsMandatoryOk returns a tuple with the IsMandatory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JwtValidation) GetIsMandatoryOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMandatory) {
		return nil, false
	}
	return o.IsMandatory, true
}

// HasIsMandatory returns a boolean if a field has been set.
func (o *JwtValidation) HasIsMandatory() bool {
	if o != nil && !IsNil(o.IsMandatory) {
		return true
	}

	return false
}

// SetIsMandatory gets a reference to the given bool and assigns it to the IsMandatory field.
func (o *JwtValidation) SetIsMandatory(v bool) {
	o.IsMandatory = &v
}

func (o JwtValidation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JwtValidation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsMandatory) {
		toSerialize["IsMandatory"] = o.IsMandatory
	}
	return toSerialize, nil
}

type NullableJwtValidation struct {
	value *JwtValidation
	isSet bool
}

func (v NullableJwtValidation) Get() *JwtValidation {
	return v.value
}

func (v *NullableJwtValidation) Set(val *JwtValidation) {
	v.value = val
	v.isSet = true
}

func (v NullableJwtValidation) IsSet() bool {
	return v.isSet
}

func (v *NullableJwtValidation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJwtValidation(val *JwtValidation) *NullableJwtValidation {
	return &NullableJwtValidation{value: val, isSet: true}
}

func (v NullableJwtValidation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJwtValidation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
