/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WebhookAuthentication type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookAuthentication{}

// WebhookAuthentication struct for WebhookAuthentication
type WebhookAuthentication struct {
	// The type of authentication used for the webhook
	AuthType    *string           `json:"AuthType,omitempty"`
	BasicAuth   *BasicAuthWebhook `json:"BasicAuth,omitempty"`
	BearerToken *Bearertoken      `json:"BearerToken,omitempty"`
}

// NewWebhookAuthentication instantiates a new WebhookAuthentication object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookAuthentication() *WebhookAuthentication {
	this := WebhookAuthentication{}
	return &this
}

// NewWebhookAuthenticationWithDefaults instantiates a new WebhookAuthentication object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookAuthenticationWithDefaults() *WebhookAuthentication {
	this := WebhookAuthentication{}
	return &this
}

// GetAuthType returns the AuthType field value if set, zero value otherwise.
func (o *WebhookAuthentication) GetAuthType() string {
	if o == nil || IsNil(o.AuthType) {
		var ret string
		return ret
	}
	return *o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookAuthentication) GetAuthTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthType) {
		return nil, false
	}
	return o.AuthType, true
}

// HasAuthType returns a boolean if a field has been set.
func (o *WebhookAuthentication) HasAuthType() bool {
	if o != nil && !IsNil(o.AuthType) {
		return true
	}

	return false
}

// SetAuthType gets a reference to the given string and assigns it to the AuthType field.
func (o *WebhookAuthentication) SetAuthType(v string) {
	o.AuthType = &v
}

// GetBasicAuth returns the BasicAuth field value if set, zero value otherwise.
func (o *WebhookAuthentication) GetBasicAuth() BasicAuthWebhook {
	if o == nil || IsNil(o.BasicAuth) {
		var ret BasicAuthWebhook
		return ret
	}
	return *o.BasicAuth
}

// GetBasicAuthOk returns a tuple with the BasicAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookAuthentication) GetBasicAuthOk() (*BasicAuthWebhook, bool) {
	if o == nil || IsNil(o.BasicAuth) {
		return nil, false
	}
	return o.BasicAuth, true
}

// HasBasicAuth returns a boolean if a field has been set.
func (o *WebhookAuthentication) HasBasicAuth() bool {
	if o != nil && !IsNil(o.BasicAuth) {
		return true
	}

	return false
}

// SetBasicAuth gets a reference to the given BasicAuthWebhook and assigns it to the BasicAuth field.
func (o *WebhookAuthentication) SetBasicAuth(v BasicAuthWebhook) {
	o.BasicAuth = &v
}

// GetBearerToken returns the BearerToken field value if set, zero value otherwise.
func (o *WebhookAuthentication) GetBearerToken() Bearertoken {
	if o == nil || IsNil(o.BearerToken) {
		var ret Bearertoken
		return ret
	}
	return *o.BearerToken
}

// GetBearerTokenOk returns a tuple with the BearerToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookAuthentication) GetBearerTokenOk() (*Bearertoken, bool) {
	if o == nil || IsNil(o.BearerToken) {
		return nil, false
	}
	return o.BearerToken, true
}

// HasBearerToken returns a boolean if a field has been set.
func (o *WebhookAuthentication) HasBearerToken() bool {
	if o != nil && !IsNil(o.BearerToken) {
		return true
	}

	return false
}

// SetBearerToken gets a reference to the given Bearertoken and assigns it to the BearerToken field.
func (o *WebhookAuthentication) SetBearerToken(v Bearertoken) {
	o.BearerToken = &v
}

func (o WebhookAuthentication) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookAuthentication) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthType) {
		toSerialize["AuthType"] = o.AuthType
	}
	if !IsNil(o.BasicAuth) {
		toSerialize["BasicAuth"] = o.BasicAuth
	}
	if !IsNil(o.BearerToken) {
		toSerialize["BearerToken"] = o.BearerToken
	}
	return toSerialize, nil
}

type NullableWebhookAuthentication struct {
	value *WebhookAuthentication
	isSet bool
}

func (v NullableWebhookAuthentication) Get() *WebhookAuthentication {
	return v.value
}

func (v *NullableWebhookAuthentication) Set(val *WebhookAuthentication) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookAuthentication) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookAuthentication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookAuthentication(val *WebhookAuthentication) *NullableWebhookAuthentication {
	return &NullableWebhookAuthentication{value: val, isSet: true}
}

func (v NullableWebhookAuthentication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookAuthentication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
