/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BatchUploadErrorResponseErrorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchUploadErrorResponseErrorsInner{}

// BatchUploadErrorResponseErrorsInner struct for BatchUploadErrorResponseErrorsInner
type BatchUploadErrorResponseErrorsInner struct {
	// Identifier for the record that caused the error.
	FieldName string `json:"FieldName"`
	// Description of the specific error related to the field.
	ErrorMessage string `json:"ErrorMessage"`
}

type _BatchUploadErrorResponseErrorsInner BatchUploadErrorResponseErrorsInner

// NewBatchUploadErrorResponseErrorsInner instantiates a new BatchUploadErrorResponseErrorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchUploadErrorResponseErrorsInner(fieldName string, errorMessage string) *BatchUploadErrorResponseErrorsInner {
	this := BatchUploadErrorResponseErrorsInner{}
	this.FieldName = fieldName
	this.ErrorMessage = errorMessage
	return &this
}

// NewBatchUploadErrorResponseErrorsInnerWithDefaults instantiates a new BatchUploadErrorResponseErrorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchUploadErrorResponseErrorsInnerWithDefaults() *BatchUploadErrorResponseErrorsInner {
	this := BatchUploadErrorResponseErrorsInner{}
	return &this
}

// GetFieldName returns the FieldName field value
func (o *BatchUploadErrorResponseErrorsInner) GetFieldName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FieldName
}

// GetFieldNameOk returns a tuple with the FieldName field value
// and a boolean to check if the value has been set.
func (o *BatchUploadErrorResponseErrorsInner) GetFieldNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldName, true
}

// SetFieldName sets field value
func (o *BatchUploadErrorResponseErrorsInner) SetFieldName(v string) {
	o.FieldName = v
}

// GetErrorMessage returns the ErrorMessage field value
func (o *BatchUploadErrorResponseErrorsInner) GetErrorMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value
// and a boolean to check if the value has been set.
func (o *BatchUploadErrorResponseErrorsInner) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorMessage, true
}

// SetErrorMessage sets field value
func (o *BatchUploadErrorResponseErrorsInner) SetErrorMessage(v string) {
	o.ErrorMessage = v
}

func (o BatchUploadErrorResponseErrorsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchUploadErrorResponseErrorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["FieldName"] = o.FieldName
	toSerialize["ErrorMessage"] = o.ErrorMessage
	return toSerialize, nil
}

func (o *BatchUploadErrorResponseErrorsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"FieldName",
		"ErrorMessage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchUploadErrorResponseErrorsInner := _BatchUploadErrorResponseErrorsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchUploadErrorResponseErrorsInner)

	if err != nil {
		return err
	}

	*o = BatchUploadErrorResponseErrorsInner(varBatchUploadErrorResponseErrorsInner)

	return err
}

type NullableBatchUploadErrorResponseErrorsInner struct {
	value *BatchUploadErrorResponseErrorsInner
	isSet bool
}

func (v NullableBatchUploadErrorResponseErrorsInner) Get() *BatchUploadErrorResponseErrorsInner {
	return v.value
}

func (v *NullableBatchUploadErrorResponseErrorsInner) Set(val *BatchUploadErrorResponseErrorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchUploadErrorResponseErrorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchUploadErrorResponseErrorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchUploadErrorResponseErrorsInner(val *BatchUploadErrorResponseErrorsInner) *NullableBatchUploadErrorResponseErrorsInner {
	return &NullableBatchUploadErrorResponseErrorsInner{value: val, isSet: true}
}

func (v NullableBatchUploadErrorResponseErrorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchUploadErrorResponseErrorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
