/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MFAVerifyPhoneOtpModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MFAVerifyPhoneOtpModel{}

// MFAVerifyPhoneOtpModel struct for MFAVerifyPhoneOtpModel
type MFAVerifyPhoneOtpModel struct {
	// The Google reCAPTCHA response which is sent to the server for verification.
	GRecaptchaResponse NullableString `json:"g-recaptcha-response,omitempty"`
	// The QQ Captcha ticket which is sent to the server for verification.
	QqCaptchaTicket NullableString `json:"qq_captcha_ticket,omitempty"`
	// The QQ Captcha random string which is sent to the server for verification.
	QqCaptchaRandstr NullableString `json:"qq_captcha_randstr,omitempty"`
	// The hCaptcha response which is sent to the server for verification.
	HCaptchaResponse NullableString     `json:"h-captcha-response,omitempty"`
	SecurityAnswer   *map[string]string `json:"SecurityAnswer,omitempty"`
	// The one-time Password (OTP).
	Otp string `json:"otp"`
}

type _MFAVerifyPhoneOtpModel MFAVerifyPhoneOtpModel

// NewMFAVerifyPhoneOtpModel instantiates a new MFAVerifyPhoneOtpModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMFAVerifyPhoneOtpModel(otp string) *MFAVerifyPhoneOtpModel {
	this := MFAVerifyPhoneOtpModel{}
	this.Otp = otp
	return &this
}

// NewMFAVerifyPhoneOtpModelWithDefaults instantiates a new MFAVerifyPhoneOtpModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMFAVerifyPhoneOtpModelWithDefaults() *MFAVerifyPhoneOtpModel {
	this := MFAVerifyPhoneOtpModel{}
	return &this
}

// GetGRecaptchaResponse returns the GRecaptchaResponse field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MFAVerifyPhoneOtpModel) GetGRecaptchaResponse() string {
	if o == nil || IsNil(o.GRecaptchaResponse.Get()) {
		var ret string
		return ret
	}
	return *o.GRecaptchaResponse.Get()
}

// GetGRecaptchaResponseOk returns a tuple with the GRecaptchaResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MFAVerifyPhoneOtpModel) GetGRecaptchaResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GRecaptchaResponse.Get(), o.GRecaptchaResponse.IsSet()
}

// HasGRecaptchaResponse returns a boolean if a field has been set.
func (o *MFAVerifyPhoneOtpModel) HasGRecaptchaResponse() bool {
	if o != nil && o.GRecaptchaResponse.IsSet() {
		return true
	}

	return false
}

// SetGRecaptchaResponse gets a reference to the given NullableString and assigns it to the GRecaptchaResponse field.
func (o *MFAVerifyPhoneOtpModel) SetGRecaptchaResponse(v string) {
	o.GRecaptchaResponse.Set(&v)
}

// SetGRecaptchaResponseNil sets the value for GRecaptchaResponse to be an explicit nil
func (o *MFAVerifyPhoneOtpModel) SetGRecaptchaResponseNil() {
	o.GRecaptchaResponse.Set(nil)
}

// UnsetGRecaptchaResponse ensures that no value is present for GRecaptchaResponse, not even an explicit nil
func (o *MFAVerifyPhoneOtpModel) UnsetGRecaptchaResponse() {
	o.GRecaptchaResponse.Unset()
}

// GetQqCaptchaTicket returns the QqCaptchaTicket field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MFAVerifyPhoneOtpModel) GetQqCaptchaTicket() string {
	if o == nil || IsNil(o.QqCaptchaTicket.Get()) {
		var ret string
		return ret
	}
	return *o.QqCaptchaTicket.Get()
}

// GetQqCaptchaTicketOk returns a tuple with the QqCaptchaTicket field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MFAVerifyPhoneOtpModel) GetQqCaptchaTicketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QqCaptchaTicket.Get(), o.QqCaptchaTicket.IsSet()
}

// HasQqCaptchaTicket returns a boolean if a field has been set.
func (o *MFAVerifyPhoneOtpModel) HasQqCaptchaTicket() bool {
	if o != nil && o.QqCaptchaTicket.IsSet() {
		return true
	}

	return false
}

// SetQqCaptchaTicket gets a reference to the given NullableString and assigns it to the QqCaptchaTicket field.
func (o *MFAVerifyPhoneOtpModel) SetQqCaptchaTicket(v string) {
	o.QqCaptchaTicket.Set(&v)
}

// SetQqCaptchaTicketNil sets the value for QqCaptchaTicket to be an explicit nil
func (o *MFAVerifyPhoneOtpModel) SetQqCaptchaTicketNil() {
	o.QqCaptchaTicket.Set(nil)
}

// UnsetQqCaptchaTicket ensures that no value is present for QqCaptchaTicket, not even an explicit nil
func (o *MFAVerifyPhoneOtpModel) UnsetQqCaptchaTicket() {
	o.QqCaptchaTicket.Unset()
}

// GetQqCaptchaRandstr returns the QqCaptchaRandstr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MFAVerifyPhoneOtpModel) GetQqCaptchaRandstr() string {
	if o == nil || IsNil(o.QqCaptchaRandstr.Get()) {
		var ret string
		return ret
	}
	return *o.QqCaptchaRandstr.Get()
}

// GetQqCaptchaRandstrOk returns a tuple with the QqCaptchaRandstr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MFAVerifyPhoneOtpModel) GetQqCaptchaRandstrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QqCaptchaRandstr.Get(), o.QqCaptchaRandstr.IsSet()
}

// HasQqCaptchaRandstr returns a boolean if a field has been set.
func (o *MFAVerifyPhoneOtpModel) HasQqCaptchaRandstr() bool {
	if o != nil && o.QqCaptchaRandstr.IsSet() {
		return true
	}

	return false
}

// SetQqCaptchaRandstr gets a reference to the given NullableString and assigns it to the QqCaptchaRandstr field.
func (o *MFAVerifyPhoneOtpModel) SetQqCaptchaRandstr(v string) {
	o.QqCaptchaRandstr.Set(&v)
}

// SetQqCaptchaRandstrNil sets the value for QqCaptchaRandstr to be an explicit nil
func (o *MFAVerifyPhoneOtpModel) SetQqCaptchaRandstrNil() {
	o.QqCaptchaRandstr.Set(nil)
}

// UnsetQqCaptchaRandstr ensures that no value is present for QqCaptchaRandstr, not even an explicit nil
func (o *MFAVerifyPhoneOtpModel) UnsetQqCaptchaRandstr() {
	o.QqCaptchaRandstr.Unset()
}

// GetHCaptchaResponse returns the HCaptchaResponse field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MFAVerifyPhoneOtpModel) GetHCaptchaResponse() string {
	if o == nil || IsNil(o.HCaptchaResponse.Get()) {
		var ret string
		return ret
	}
	return *o.HCaptchaResponse.Get()
}

// GetHCaptchaResponseOk returns a tuple with the HCaptchaResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MFAVerifyPhoneOtpModel) GetHCaptchaResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HCaptchaResponse.Get(), o.HCaptchaResponse.IsSet()
}

// HasHCaptchaResponse returns a boolean if a field has been set.
func (o *MFAVerifyPhoneOtpModel) HasHCaptchaResponse() bool {
	if o != nil && o.HCaptchaResponse.IsSet() {
		return true
	}

	return false
}

// SetHCaptchaResponse gets a reference to the given NullableString and assigns it to the HCaptchaResponse field.
func (o *MFAVerifyPhoneOtpModel) SetHCaptchaResponse(v string) {
	o.HCaptchaResponse.Set(&v)
}

// SetHCaptchaResponseNil sets the value for HCaptchaResponse to be an explicit nil
func (o *MFAVerifyPhoneOtpModel) SetHCaptchaResponseNil() {
	o.HCaptchaResponse.Set(nil)
}

// UnsetHCaptchaResponse ensures that no value is present for HCaptchaResponse, not even an explicit nil
func (o *MFAVerifyPhoneOtpModel) UnsetHCaptchaResponse() {
	o.HCaptchaResponse.Unset()
}

// GetSecurityAnswer returns the SecurityAnswer field value if set, zero value otherwise.
func (o *MFAVerifyPhoneOtpModel) GetSecurityAnswer() map[string]string {
	if o == nil || IsNil(o.SecurityAnswer) {
		var ret map[string]string
		return ret
	}
	return *o.SecurityAnswer
}

// GetSecurityAnswerOk returns a tuple with the SecurityAnswer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MFAVerifyPhoneOtpModel) GetSecurityAnswerOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.SecurityAnswer) {
		return nil, false
	}
	return o.SecurityAnswer, true
}

// HasSecurityAnswer returns a boolean if a field has been set.
func (o *MFAVerifyPhoneOtpModel) HasSecurityAnswer() bool {
	if o != nil && !IsNil(o.SecurityAnswer) {
		return true
	}

	return false
}

// SetSecurityAnswer gets a reference to the given map[string]string and assigns it to the SecurityAnswer field.
func (o *MFAVerifyPhoneOtpModel) SetSecurityAnswer(v map[string]string) {
	o.SecurityAnswer = &v
}

// GetOtp returns the Otp field value
func (o *MFAVerifyPhoneOtpModel) GetOtp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Otp
}

// GetOtpOk returns a tuple with the Otp field value
// and a boolean to check if the value has been set.
func (o *MFAVerifyPhoneOtpModel) GetOtpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Otp, true
}

// SetOtp sets field value
func (o *MFAVerifyPhoneOtpModel) SetOtp(v string) {
	o.Otp = v
}

func (o MFAVerifyPhoneOtpModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MFAVerifyPhoneOtpModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.GRecaptchaResponse.IsSet() {
		toSerialize["g-recaptcha-response"] = o.GRecaptchaResponse.Get()
	}
	if o.QqCaptchaTicket.IsSet() {
		toSerialize["qq_captcha_ticket"] = o.QqCaptchaTicket.Get()
	}
	if o.QqCaptchaRandstr.IsSet() {
		toSerialize["qq_captcha_randstr"] = o.QqCaptchaRandstr.Get()
	}
	if o.HCaptchaResponse.IsSet() {
		toSerialize["h-captcha-response"] = o.HCaptchaResponse.Get()
	}
	if !IsNil(o.SecurityAnswer) {
		toSerialize["SecurityAnswer"] = o.SecurityAnswer
	}
	toSerialize["otp"] = o.Otp
	return toSerialize, nil
}

func (o *MFAVerifyPhoneOtpModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"otp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMFAVerifyPhoneOtpModel := _MFAVerifyPhoneOtpModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMFAVerifyPhoneOtpModel)

	if err != nil {
		return err
	}

	*o = MFAVerifyPhoneOtpModel(varMFAVerifyPhoneOtpModel)

	return err
}

type NullableMFAVerifyPhoneOtpModel struct {
	value *MFAVerifyPhoneOtpModel
	isSet bool
}

func (v NullableMFAVerifyPhoneOtpModel) Get() *MFAVerifyPhoneOtpModel {
	return v.value
}

func (v *NullableMFAVerifyPhoneOtpModel) Set(val *MFAVerifyPhoneOtpModel) {
	v.value = val
	v.isSet = true
}

func (v NullableMFAVerifyPhoneOtpModel) IsSet() bool {
	return v.isSet
}

func (v *NullableMFAVerifyPhoneOtpModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMFAVerifyPhoneOtpModel(val *MFAVerifyPhoneOtpModel) *NullableMFAVerifyPhoneOtpModel {
	return &NullableMFAVerifyPhoneOtpModel{value: val, isSet: true}
}

func (v NullableMFAVerifyPhoneOtpModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMFAVerifyPhoneOtpModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
