/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BigCommerceValidatePasswordResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BigCommerceValidatePasswordResponse{}

// BigCommerceValidatePasswordResponse struct for BigCommerceValidatePasswordResponse
type BigCommerceValidatePasswordResponse struct {
	// Whether the password is valid for the BigCommerce customer.
	Verified *bool `json:"verified,omitempty"`
}

// NewBigCommerceValidatePasswordResponse instantiates a new BigCommerceValidatePasswordResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBigCommerceValidatePasswordResponse() *BigCommerceValidatePasswordResponse {
	this := BigCommerceValidatePasswordResponse{}
	return &this
}

// NewBigCommerceValidatePasswordResponseWithDefaults instantiates a new BigCommerceValidatePasswordResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBigCommerceValidatePasswordResponseWithDefaults() *BigCommerceValidatePasswordResponse {
	this := BigCommerceValidatePasswordResponse{}
	return &this
}

// GetVerified returns the Verified field value if set, zero value otherwise.
func (o *BigCommerceValidatePasswordResponse) GetVerified() bool {
	if o == nil || IsNil(o.Verified) {
		var ret bool
		return ret
	}
	return *o.Verified
}

// GetVerifiedOk returns a tuple with the Verified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BigCommerceValidatePasswordResponse) GetVerifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.Verified) {
		return nil, false
	}
	return o.Verified, true
}

// HasVerified returns a boolean if a field has been set.
func (o *BigCommerceValidatePasswordResponse) HasVerified() bool {
	if o != nil && !IsNil(o.Verified) {
		return true
	}

	return false
}

// SetVerified gets a reference to the given bool and assigns it to the Verified field.
func (o *BigCommerceValidatePasswordResponse) SetVerified(v bool) {
	o.Verified = &v
}

func (o BigCommerceValidatePasswordResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BigCommerceValidatePasswordResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Verified) {
		toSerialize["verified"] = o.Verified
	}
	return toSerialize, nil
}

type NullableBigCommerceValidatePasswordResponse struct {
	value *BigCommerceValidatePasswordResponse
	isSet bool
}

func (v NullableBigCommerceValidatePasswordResponse) Get() *BigCommerceValidatePasswordResponse {
	return v.value
}

func (v *NullableBigCommerceValidatePasswordResponse) Set(val *BigCommerceValidatePasswordResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBigCommerceValidatePasswordResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBigCommerceValidatePasswordResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBigCommerceValidatePasswordResponse(val *BigCommerceValidatePasswordResponse) *NullableBigCommerceValidatePasswordResponse {
	return &NullableBigCommerceValidatePasswordResponse{value: val, isSet: true}
}

func (v NullableBigCommerceValidatePasswordResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBigCommerceValidatePasswordResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
