/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner{}

// SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner struct for SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner
type SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner struct {
	Binding  *string `json:"Binding,omitempty"`
	Location *string `json:"Location,omitempty"`
}

// NewSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner instantiates a new SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner() *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner {
	this := SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner{}
	return &this
}

// NewSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInnerWithDefaults instantiates a new SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInnerWithDefaults() *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner {
	this := SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner{}
	return &this
}

// GetBinding returns the Binding field value if set, zero value otherwise.
func (o *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) GetBinding() string {
	if o == nil || IsNil(o.Binding) {
		var ret string
		return ret
	}
	return *o.Binding
}

// GetBindingOk returns a tuple with the Binding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) GetBindingOk() (*string, bool) {
	if o == nil || IsNil(o.Binding) {
		return nil, false
	}
	return o.Binding, true
}

// HasBinding returns a boolean if a field has been set.
func (o *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) HasBinding() bool {
	if o != nil && !IsNil(o.Binding) {
		return true
	}

	return false
}

// SetBinding gets a reference to the given string and assigns it to the Binding field.
func (o *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) SetBinding(v string) {
	o.Binding = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) SetLocation(v string) {
	o.Location = &v
}

func (o SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Binding) {
		toSerialize["Binding"] = o.Binding
	}
	if !IsNil(o.Location) {
		toSerialize["Location"] = o.Location
	}
	return toSerialize, nil
}

type NullableSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner struct {
	value *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner
	isSet bool
}

func (v NullableSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) Get() *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner {
	return v.value
}

func (v *NullableSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) Set(val *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner(val *SamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) *NullableSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner {
	return &NullableSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner{value: val, isSet: true}
}

func (v NullableSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSamlIdpMetadataResponseIDPSSODescriptorSingleSignOnServiceInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
