/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BulkInsertErrorReport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkInsertErrorReport{}

// BulkInsertErrorReport struct for BulkInsertErrorReport
type BulkInsertErrorReport struct {
	// Row no of the record that failed.
	RecordNumber int32 `json:"RecordNumber"`
	// Description of the error encountered during insert or update.
	Message string `json:"Message"`
}

type _BulkInsertErrorReport BulkInsertErrorReport

// NewBulkInsertErrorReport instantiates a new BulkInsertErrorReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkInsertErrorReport(recordNumber int32, message string) *BulkInsertErrorReport {
	this := BulkInsertErrorReport{}
	this.RecordNumber = recordNumber
	this.Message = message
	return &this
}

// NewBulkInsertErrorReportWithDefaults instantiates a new BulkInsertErrorReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkInsertErrorReportWithDefaults() *BulkInsertErrorReport {
	this := BulkInsertErrorReport{}
	return &this
}

// GetRecordNumber returns the RecordNumber field value
func (o *BulkInsertErrorReport) GetRecordNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RecordNumber
}

// GetRecordNumberOk returns a tuple with the RecordNumber field value
// and a boolean to check if the value has been set.
func (o *BulkInsertErrorReport) GetRecordNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecordNumber, true
}

// SetRecordNumber sets field value
func (o *BulkInsertErrorReport) SetRecordNumber(v int32) {
	o.RecordNumber = v
}

// GetMessage returns the Message field value
func (o *BulkInsertErrorReport) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *BulkInsertErrorReport) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *BulkInsertErrorReport) SetMessage(v string) {
	o.Message = v
}

func (o BulkInsertErrorReport) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkInsertErrorReport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["RecordNumber"] = o.RecordNumber
	toSerialize["Message"] = o.Message
	return toSerialize, nil
}

func (o *BulkInsertErrorReport) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"RecordNumber",
		"Message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkInsertErrorReport := _BulkInsertErrorReport{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkInsertErrorReport)

	if err != nil {
		return err
	}

	*o = BulkInsertErrorReport(varBulkInsertErrorReport)

	return err
}

type NullableBulkInsertErrorReport struct {
	value *BulkInsertErrorReport
	isSet bool
}

func (v NullableBulkInsertErrorReport) Get() *BulkInsertErrorReport {
	return v.value
}

func (v *NullableBulkInsertErrorReport) Set(val *BulkInsertErrorReport) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkInsertErrorReport) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkInsertErrorReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkInsertErrorReport(val *BulkInsertErrorReport) *NullableBulkInsertErrorReport {
	return &NullableBulkInsertErrorReport{value: val, isSet: true}
}

func (v NullableBulkInsertErrorReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkInsertErrorReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
