/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAllWorkflows200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAllWorkflows200Response{}

// GetAllWorkflows200Response struct for GetAllWorkflows200Response
type GetAllWorkflows200Response struct {
	Data []WorkflowConfigWithoutData `json:"Data,omitempty"`
}

// NewGetAllWorkflows200Response instantiates a new GetAllWorkflows200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllWorkflows200Response() *GetAllWorkflows200Response {
	this := GetAllWorkflows200Response{}
	return &this
}

// NewGetAllWorkflows200ResponseWithDefaults instantiates a new GetAllWorkflows200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllWorkflows200ResponseWithDefaults() *GetAllWorkflows200Response {
	this := GetAllWorkflows200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetAllWorkflows200Response) GetData() []WorkflowConfigWithoutData {
	if o == nil || IsNil(o.Data) {
		var ret []WorkflowConfigWithoutData
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllWorkflows200Response) GetDataOk() ([]WorkflowConfigWithoutData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetAllWorkflows200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []WorkflowConfigWithoutData and assigns it to the Data field.
func (o *GetAllWorkflows200Response) SetData(v []WorkflowConfigWithoutData) {
	o.Data = v
}

func (o GetAllWorkflows200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAllWorkflows200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["Data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetAllWorkflows200Response struct {
	value *GetAllWorkflows200Response
	isSet bool
}

func (v NullableGetAllWorkflows200Response) Get() *GetAllWorkflows200Response {
	return v.value
}

func (v *NullableGetAllWorkflows200Response) Set(val *GetAllWorkflows200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllWorkflows200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllWorkflows200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllWorkflows200Response(val *GetAllWorkflows200Response) *NullableGetAllWorkflows200Response {
	return &NullableGetAllWorkflows200Response{value: val, isSet: true}
}

func (v NullableGetAllWorkflows200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAllWorkflows200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
