/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ManageRegisterModelVolunteerInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManageRegisterModelVolunteerInner{}

// ManageRegisterModelVolunteerInner struct for ManageRegisterModelVolunteerInner
type ManageRegisterModelVolunteerInner struct {
	// The ID of the volunteer experience.
	Id *string `json:"Id,omitempty"`
	// The Role of the User in the volunteer experience.
	Role *string `json:"Role,omitempty"`
	// The organization where the User volunteered.
	Organization *string `json:"Organization,omitempty"`
	// The cause supported by the volunteer experience.
	Cause *string `json:"Cause,omitempty"`
}

// NewManageRegisterModelVolunteerInner instantiates a new ManageRegisterModelVolunteerInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageRegisterModelVolunteerInner() *ManageRegisterModelVolunteerInner {
	this := ManageRegisterModelVolunteerInner{}
	return &this
}

// NewManageRegisterModelVolunteerInnerWithDefaults instantiates a new ManageRegisterModelVolunteerInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageRegisterModelVolunteerInnerWithDefaults() *ManageRegisterModelVolunteerInner {
	this := ManageRegisterModelVolunteerInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ManageRegisterModelVolunteerInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelVolunteerInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ManageRegisterModelVolunteerInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ManageRegisterModelVolunteerInner) SetId(v string) {
	o.Id = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *ManageRegisterModelVolunteerInner) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelVolunteerInner) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *ManageRegisterModelVolunteerInner) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *ManageRegisterModelVolunteerInner) SetRole(v string) {
	o.Role = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *ManageRegisterModelVolunteerInner) GetOrganization() string {
	if o == nil || IsNil(o.Organization) {
		var ret string
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelVolunteerInner) GetOrganizationOk() (*string, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *ManageRegisterModelVolunteerInner) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given string and assigns it to the Organization field.
func (o *ManageRegisterModelVolunteerInner) SetOrganization(v string) {
	o.Organization = &v
}

// GetCause returns the Cause field value if set, zero value otherwise.
func (o *ManageRegisterModelVolunteerInner) GetCause() string {
	if o == nil || IsNil(o.Cause) {
		var ret string
		return ret
	}
	return *o.Cause
}

// GetCauseOk returns a tuple with the Cause field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageRegisterModelVolunteerInner) GetCauseOk() (*string, bool) {
	if o == nil || IsNil(o.Cause) {
		return nil, false
	}
	return o.Cause, true
}

// HasCause returns a boolean if a field has been set.
func (o *ManageRegisterModelVolunteerInner) HasCause() bool {
	if o != nil && !IsNil(o.Cause) {
		return true
	}

	return false
}

// SetCause gets a reference to the given string and assigns it to the Cause field.
func (o *ManageRegisterModelVolunteerInner) SetCause(v string) {
	o.Cause = &v
}

func (o ManageRegisterModelVolunteerInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManageRegisterModelVolunteerInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Role) {
		toSerialize["Role"] = o.Role
	}
	if !IsNil(o.Organization) {
		toSerialize["Organization"] = o.Organization
	}
	if !IsNil(o.Cause) {
		toSerialize["Cause"] = o.Cause
	}
	return toSerialize, nil
}

type NullableManageRegisterModelVolunteerInner struct {
	value *ManageRegisterModelVolunteerInner
	isSet bool
}

func (v NullableManageRegisterModelVolunteerInner) Get() *ManageRegisterModelVolunteerInner {
	return v.value
}

func (v *NullableManageRegisterModelVolunteerInner) Set(val *ManageRegisterModelVolunteerInner) {
	v.value = val
	v.isSet = true
}

func (v NullableManageRegisterModelVolunteerInner) IsSet() bool {
	return v.isSet
}

func (v *NullableManageRegisterModelVolunteerInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageRegisterModelVolunteerInner(val *ManageRegisterModelVolunteerInner) *NullableManageRegisterModelVolunteerInner {
	return &NullableManageRegisterModelVolunteerInner{value: val, isSet: true}
}

func (v NullableManageRegisterModelVolunteerInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageRegisterModelVolunteerInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
