/*
LoginRadius API

This is a LoginRadius API server. Which you can use to authenticate and manage the user.

API version: 1.0.0
Contact: support@loginradius.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SocialIdentityAwardsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SocialIdentityAwardsInner{}

// SocialIdentityAwardsInner struct for SocialIdentityAwardsInner
type SocialIdentityAwardsInner struct {
	Id     *string `json:"Id,omitempty"`
	Name   *string `json:"Name,omitempty"`
	Issuer *string `json:"Issuer,omitempty"`
}

// NewSocialIdentityAwardsInner instantiates a new SocialIdentityAwardsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSocialIdentityAwardsInner() *SocialIdentityAwardsInner {
	this := SocialIdentityAwardsInner{}
	return &this
}

// NewSocialIdentityAwardsInnerWithDefaults instantiates a new SocialIdentityAwardsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSocialIdentityAwardsInnerWithDefaults() *SocialIdentityAwardsInner {
	this := SocialIdentityAwardsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SocialIdentityAwardsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialIdentityAwardsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SocialIdentityAwardsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SocialIdentityAwardsInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SocialIdentityAwardsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialIdentityAwardsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SocialIdentityAwardsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SocialIdentityAwardsInner) SetName(v string) {
	o.Name = &v
}

// GetIssuer returns the Issuer field value if set, zero value otherwise.
func (o *SocialIdentityAwardsInner) GetIssuer() string {
	if o == nil || IsNil(o.Issuer) {
		var ret string
		return ret
	}
	return *o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialIdentityAwardsInner) GetIssuerOk() (*string, bool) {
	if o == nil || IsNil(o.Issuer) {
		return nil, false
	}
	return o.Issuer, true
}

// HasIssuer returns a boolean if a field has been set.
func (o *SocialIdentityAwardsInner) HasIssuer() bool {
	if o != nil && !IsNil(o.Issuer) {
		return true
	}

	return false
}

// SetIssuer gets a reference to the given string and assigns it to the Issuer field.
func (o *SocialIdentityAwardsInner) SetIssuer(v string) {
	o.Issuer = &v
}

func (o SocialIdentityAwardsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SocialIdentityAwardsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Issuer) {
		toSerialize["Issuer"] = o.Issuer
	}
	return toSerialize, nil
}

type NullableSocialIdentityAwardsInner struct {
	value *SocialIdentityAwardsInner
	isSet bool
}

func (v NullableSocialIdentityAwardsInner) Get() *SocialIdentityAwardsInner {
	return v.value
}

func (v *NullableSocialIdentityAwardsInner) Set(val *SocialIdentityAwardsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSocialIdentityAwardsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSocialIdentityAwardsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSocialIdentityAwardsInner(val *SocialIdentityAwardsInner) *NullableSocialIdentityAwardsInner {
	return &NullableSocialIdentityAwardsInner{value: val, isSet: true}
}

func (v NullableSocialIdentityAwardsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSocialIdentityAwardsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
